#!/usr/bin/env python3
"""Generate the Germany luxury buyer/capital prospect CSV from verified research notes."""

from __future__ import annotations

import csv
from pathlib import Path

HEADERS = [
    "country",
    "city",
    "company_name",
    "type",
    "contact_name",
    "contact_role",
    "email",
    "phone",
    "website",
    "linkedin_company",
    "linkedin_contact",
    "investment_focus",
    "geographic_focus",
    "buyer_origin_relevance",
    "italy_interest",
    "amalfi_coast_relevance",
    "estimated_ticket",
    "luxury_real_estate",
    "hospitality_interest",
    "fit_score",
    "priority",
    "verification_status",
    "source_1",
    "source_2",
    "notes",
    "last_verified",
]

LAST_VERIFIED = "2026-08-27"
COUNTRY = "Germany"

ROWS = [
    {
        "city": "Hamburg",
        "company_name": "Engel & Völkers Private Office",
        "type": "private_office",
        "contact_name": "Lara Michaelsen",
        "contact_role": "Head of Private Office EMEA",
        "email": "contact@engelvoelkers.com",
        "phone": "+49 40 36131-0",
        "website": "https://www.engelvoelkers.com/de/en/company/private-office",
        "linkedin_company": "https://www.linkedin.com/company/engelvoelkers-global",
        "linkedin_contact": "https://www.linkedin.com/in/maierlara",
        "investment_focus": "UHNW private-office advisory for off-market and trophy residential worldwide; acquisition, sale and portfolio advisory for private clients and family offices",
        "geographic_focus": "Hamburg headquarters with a global Private Office advisor network including Germany, Italy, Spain, the US and the UAE",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.engelvoelkers.com/private-office/de/impressum",
        "source_2": "https://www.engelvoelkers.com/de/en/resources/real-estate-in-italy",
        "notes": "German-headquartered UHNW desk, not an Italian listing agency. Official Private Office imprint names Engel & Völkers Franchise and Trademark GmbH, Vancouverstrasse 2a, 20457 Hamburg; +49 40 36131-0; contact@engelvoelkers.com; Lara Michaelsen is the named editorial responsible for Private Office content and is publicly identified as Head of Private Office EMEA. Official Italy market report (with Nomisma) states international buyers account for about 35% of Italian premium purchases and that E&V has 100+ Italian locations plus the global network. Direct personal email is not published; the impressum inbox is used. Highest-probability German origin access to buyers who already purchase Italian luxury homes.",
    },
    {
        "city": "Munich",
        "company_name": "Engel & Völkers Private Office Munich",
        "type": "private_office",
        "contact_name": "Nicola Borghoff",
        "contact_role": "Private Office Advisor",
        "email": "nicola.borghoff@engelvoelkers.com",
        "phone": "+49 1525 1360628",
        "website": "https://www.engelvoelkers.com/private-office/en/advisors/nicola-borghoff",
        "linkedin_company": "https://www.linkedin.com/company/engelvoelkers-global",
        "linkedin_contact": "https://www.linkedin.com/in/nicola-borghoff",
        "investment_focus": "UHNW and luxury residential advisory; off-market and cross-border Private Office introductions for Munich-based private clients",
        "geographic_focus": "Munich UHNW client base with access to the Engel & Völkers Private Office network in about 300 advisors worldwide, including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.engelvoelkers.com/private-office/en/advisors/nicola-borghoff",
        "source_2": "https://www.engelvoelkers.com/private-office/it/advisors/nicola-borghoff",
        "notes": "Distinct from the Hamburg Private Office headquarters: this is a Munich-based Private Office advisor serving Bavarian UHNW clients who buy internationally. Official advisor page states she is one of about 300 Private Office advisors worldwide dedicated to UHNW clients, with off-market and cross-border collaboration. Official Italian-language advisor page publishes +49 1525 1360628. Email nicola.borghoff@engelvoelkers.com was published by Borghoff on her public LinkedIn post (not inferred from a pattern). Residenzstrasse 23, Munich. Kept as a separate row because the buyer book is Munich/Bavaria origin, not Hamburg corporate.",
    },
    {
        "city": "Munich",
        "company_name": "RIEDEL Immobilien (Christie's International Real Estate Munich)",
        "type": "luxury_agency",
        "contact_name": "Sabine Lenzer",
        "contact_role": "Head of International Real Estate Sales",
        "email": "info@riedel-immobilien.de",
        "phone": "+49 89 159455-75",
        "website": "https://www.riedel-immobilien.de/en/christies/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Munich luxury residential plus dedicated international sales and acquisitions through the Christie's International Real Estate network, including Italian listings",
        "geographic_focus": "Munich and Greater Munich UHNW clients; international referrals across the Christie's network including Italy, Spain, France, the UK and Austria",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "network listings include properties above €12M; unknown for a typical Munich-client Italy purchase",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.riedel-immobilien.de/en/christies/",
        "source_2": "https://www.riedel-immobilien.de/impressum/",
        "notes": "Official Christie's affiliate page for Munich names Sabine Lenzer as Head of International Real Estate Sales, +49 89 15 94 55-75, and states the firm helps clients buy/sell internationally including villas in Italy. The same page currently lists an Italian castle estate in Merano. Impressum: RIEDEL Immobilien GmbH, Tizianstrasse 50, 80638 Munich; info@riedel-immobilien.de; +49 89 159455-0. Personal email is not published; the official company inbox is used. Strong Munich UHNW origin plus an explicit Italy desk, not a domestic-only broker.",
    },
    {
        "city": "Munich",
        "company_name": "Bayern Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Michael Reiss",
        "contact_role": "Owner; Real Estate Professional",
        "email": "muenchen@bayern-sothebysrealty.com",
        "phone": "+49 89 744 24 189 0",
        "website": "https://muenchen-sothebysrealty.com/en/kontakt/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Luxury villas, estates and city properties for Bavarian private clients, with international Sotheby's International Realty referrals including an International Sales Coordinator",
        "geographic_focus": "Munich, Lake Tegernsee and Chiemgau UHNW clients; global Sotheby's network of 1,100+ offices in 84 countries including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://muenchen-sothebysrealty.com/en/kontakt/",
        "source_2": "https://bayern-sothebysrealty.com/en/",
        "notes": "Official Munich contact page names Michael Reiss as owner of Sotheby's International Realty Bavaria and Theresa Mund as Management Assistant / International Sales Coordinator. Offices: Maximilianstrasse 13, 80539 Munich; muenchen@bayern-sothebysrealty.com; +49 89 744 24 189 0. The firm states it brokers luxury real estate in top international destinations via the Sotheby's network and markets Bavarian properties to a global clientele. Italy is via the global network rather than a published Amalfi mandate. Direct personal emails are not published.",
    },
    {
        "city": "Hamburg",
        "company_name": "Hamburg Sotheby's International Realty (HIR Hamburg International Realty)",
        "type": "luxury_agency",
        "contact_name": "Alexander Stehle",
        "contact_role": "Managing Director",
        "email": "info@hir-immobilien.com",
        "phone": "+49 40 182 905 50",
        "website": "https://hir.immobilien/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Prime Hamburg residential and international Sotheby's International Realty referrals for northern-German private clients",
        "geographic_focus": "Hamburg UHNW and HNW clients, with access to the global Sotheby's International Realty network including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://hir.immobilien/impressum/",
        "source_2": "https://faz.koeln-sothebysrealty.com/privacy-policy/Sothebys-Wertermittlungsanfrage-Informationspflicht-Art-13-und-14-DSGVO-fuer-Immobilienkunden.pdf",
        "notes": "Official imprint of HIR Hamburg International Realty GmbH (the Hamburg Sotheby's International Realty operator) names Alexander Stehle as managing director; Große Elbstrasse 45, 22767 Hamburg; +49 40 182 905 50; info@hir-immobilien.com. A Sotheby's Germany GDPR notice also lists the Hamburg office under this company. Distinct Hamburg buyer book (shipping, family-office and private-wealth concentration). Italy/Amalfi not specifically evidenced; included as a northern-German UHNW introduction channel via the SIR network.",
    },
    {
        "city": "Berlin",
        "company_name": "Berlin Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Anita Gärtner",
        "contact_role": "Managing Director",
        "email": "office@berlin-sothebysrealty.com",
        "phone": "+49 30 887171800",
        "website": "https://berlin-sothebysrealty.com/en/contact/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Berlin luxury residential sales, rentals and development consulting with international Sotheby's International Realty referrals",
        "geographic_focus": "Berlin private clients, with access to the global Sotheby's International Realty network including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://berlin-sothebysrealty.com/en/contact/",
        "source_2": "https://faz.koeln-sothebysrealty.com/privacy-policy/Sothebys-Wertermittlungsanfrage-Informationspflicht-Art-13-und-14-DSGVO-fuer-Immobilienkunden.pdf",
        "notes": "Official contact page lists Pariser Strasse 23, 10707 Berlin; +49 30 887171800; office@berlin-sothebysrealty.com. A Sotheby's Germany GDPR notice names Anita Gärtner as managing director of Berlin Sotheby's International Realty. Independently owned office, distinct from Munich and Hamburg affiliates. Italy/Amalfi not specifically evidenced; included for Berlin-origin UHNW access via the SIR network.",
    },
    {
        "city": "Düsseldorf",
        "company_name": "NRW Sotheby's International Realty (Düsseldorf)",
        "type": "luxury_agency",
        "contact_name": "Harald Kaster",
        "contact_role": "Managing Director (Pantera Living Köln GmbH)",
        "email": "duesseldorf@nrw-sothebysrealty.com",
        "phone": "+49 211 1306540",
        "website": "https://nrw-sothebysrealty.com/duesseldorf/kontakt/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Luxury residential in North Rhine-Westphalia with international Sotheby's International Realty referrals",
        "geographic_focus": "Düsseldorf and Cologne UHNW/HNW clients; global Sotheby's network including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://nrw-sothebysrealty.com/duesseldorf/kontakt/",
        "source_2": "https://nrw-sothebysrealty-global.com/impressum/",
        "notes": "Official Düsseldorf contact page: Rethelstrasse 127, 40237 Düsseldorf; +49 211 1306540; duesseldorf@nrw-sothebysrealty.com. Imprint names Pantera Living Köln GmbH, managing directors Harald Kaster and Tobias Schulze. Separate Rhine-Ruhr buyer pool from the Bavarian and Hamburg SIR offices. Italy not specifically evidenced.",
    },
    {
        "city": "Frankfurt am Main",
        "company_name": "Knight Frank Germany (Frankfurt Residential)",
        "type": "luxury_agency",
        "contact_name": "Sven Henkes",
        "contact_role": "Managing Partner / Head of Capital Markets; Geschäftsführer Knight Frank (Frankfurt) Capital Markets GmbH",
        "email": "info@knightfrank.de",
        "phone": "+49 69 55 66 33-0",
        "website": "https://www.knightfrank.de/en/frankfurt/service/residential",
        "linkedin_company": "https://www.linkedin.com/company/knight-frank-germany",
        "linkedin_contact": "https://www.linkedin.com/in/sven-henkes-969304129",
        "investment_focus": "Prime and super-prime residential sales and acquisitions in the Rhine-Main region, with international marketing through Knight Frank's global network",
        "geographic_focus": "Frankfurt/Rhine-Main private clients; Knight Frank also operates in Italy and other European luxury markets",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.knightfrank.de/en/frankfurt/service/residential",
        "source_2": "https://www.knightfrank.de/frankfurt/impressum",
        "notes": "Official Frankfurt residential page states the department focuses on the national prime and super-prime segment and offers international and national marketing; key contacts include Sven Henkes. Impressum: Knight Frank Consult GmbH & Co. KG, An der Welle 3, 60322 Frankfurt; info@knightfrank.de; +49 69 55 66 33-0. Sven Henkes is also named as Geschäftsführer of Knight Frank (Frankfurt) Capital Markets GmbH. Personal email is not published on the people pages; the official Frankfurt inbox is used. Knight Frank separately maintains an Italy residential network; this row is the German-origin desk, not the Italian office. Berlin residential-investment (multi-family) is deliberately not listed because that book is institutional living, not UHNW homes.",
    },
    {
        "city": "Frankfurt am Main",
        "company_name": "VON POLL IMMOBILIEN",
        "type": "luxury_agency",
        "contact_name": "Daniel Ritter",
        "contact_role": "Managing Director",
        "email": "frankfurt@von-poll.com",
        "phone": "+49 69 26 91 57-0",
        "website": "https://www.von-poll.com/en",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Premium residential and commercial brokerage; European shop network and Luxury Portfolio / Leading Real Estate Companies of the World international referrals",
        "geographic_focus": "Frankfurt headquarters with 400+ shops across Germany and Europe, including Austria and Spain; international buyer access via Luxury Portfolio",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown; mix of premium and true luxury",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.von-poll.com/de/impressum",
        "source_2": "https://www.luxuryportfolio.com/en/brokers/von-poll-immobilien-gmbh",
        "notes": "Official imprint: von Poll Immobilien GmbH, Feldbergstrasse 35, 60323 Frankfurt; frankfurt@von-poll.com; +49 69 26 91 57-0; managing directors Daniel Ritter and Sassan Hilgendorf. Locations page also publishes info@von-poll.com. Luxury Portfolio / LeadingRE membership is the stated international-buyer channel. Included as a German-origin premium/UHNW introduction channel, not as a trophy-only specialist. Italy offices are not confirmed on the official locations materials reviewed (Spain and Austria are). Score capped because the network mixes mass-premium shops with high-end desks.",
    },
    {
        "city": "Frankfurt am Main",
        "company_name": "Fine & Country Germany (Heming Select DACH)",
        "type": "luxury_agency",
        "contact_name": "Michael Heming",
        "contact_role": "Managing Director",
        "email": "germany@fineandcountry.com",
        "phone": "+49 69 999 9880",
        "website": "https://www.fineandcountry.de/",
        "linkedin_company": "https://www.linkedin.com/company/fine-country-d-a-ch",
        "linkedin_contact": "",
        "investment_focus": "Exclusive residential brokerage with international Fine & Country marketing; DACH headquarters coordinating German private-client referrals into the global network including Italy",
        "geographic_focus": "German DACH offices with a global Fine & Country network of 300+ locations including Italy, Spain, France, Portugal and the UK",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown; published German listings include properties around €6.8M–€7.5M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.fineandcountry.de/en/legal-notice-2",
        "source_2": "https://www.fineandcountry.de/contact/find-an-agent",
        "notes": "Official legal notice: Heming Select DACH GmbH, Friedrich-Ebert-Strasse 48-50, 55286 Wörrstadt, represented by Managing Director Michael Heming; germany@fineandcountry.com; +49 69 999 9880. DACH headquarters is listed at Nextower, Thurn-und-Taxis-Platz 6, 60313 Frankfurt. Fine & Country's country selector includes Italy, supporting cross-border introductions. Mix of Berlin luxury listings and broader premium stock; included as a German-origin international luxury brand desk rather than a mass portal.",
    },
    {
        "city": "Munich",
        "company_name": "Duken & v. Wangenheim",
        "type": "luxury_agency",
        "contact_name": "Detlev Freiherr von Wangenheim",
        "contact_role": "Vorstand (CEO)",
        "email": "info@wangenheim.de",
        "phone": "+49 89 9984330",
        "website": "https://www.wangenheim.de/en/services/international-properties",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Munich luxury villas, penthouses and estates for HNWI, family offices and private clients; dedicated international-properties service for second homes abroad",
        "geographic_focus": "Munich, Starnberg and Tegernsee; international second-home advisory with an office in the Balearic Islands and listings in Mallorca, Ibiza and Kitzbühel",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "published international listings from about €1.1M to €15.9M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.wangenheim.de/en/services/international-properties",
        "source_2": "https://www.wangenheim.de/impressum",
        "notes": "Long-established Munich luxury house (since 1966) with an explicit international second-home offering. Official international page currently features Mallorca, Ibiza and Kitzbühel stock in the €1M–€16M range, i.e. ticket-compatible, and quotes Ludwig Wöhrl on advising German clients buying premium property abroad. Impressum: Duken & v. Wangenheim AG, Grosjeanstrasse 4, 81925 Munich; info@wangenheim.de; +49 89 99 84 33 0; Vorstand Detlev Frhr. v. Wangenheim. Italy is not evidenced on the international page reviewed, so Amalfi relevance is via the same German UHNW second-home buyer pool rather than an Italy desk. Southern-Munich GmbH uses mail@wangenheim.de.",
    },
    {
        "city": "Hamburg",
        "company_name": "DSR Hotel Holding / Deutsche Seereederei",
        "type": "hospitality_investor",
        "contact_name": "Horst Rahe",
        "contact_role": "Geschäftsführender Gesellschafter, Deutsche Seereederei GmbH",
        "email": "info@deutsche-seereederei.de",
        "phone": "+49 40 300 322 250",
        "website": "https://www.deutsche-seereederei.de/en/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Green-tech hospitality holding: leisure hotels and resorts (A-ROSA, aja, HENRI, Travel Charme) and Italian hotel-platform growth via MIRA Hotels & Resorts",
        "geographic_focus": "Hamburg/Rostock HQ; DACH leisure destinations plus Italy (Lake Garda, Adriatic, Tuscany, Alps and Italian cities named as growth markets)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "typical hotel/platform deals larger than €6M–€12M; unknown for a single mixed-use coastal asset",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.deutsche-seereederei.de/en/",
        "source_2": "https://www.deutsche-seereederei.de/impressum/",
        "notes": "Official DSR site states the 2023 JV DR Hospitality acquired 75% of Italian hotel company Mira Hotels & Resorts, entering the Italian hotel market. Contemporary Italian coverage names Lake Garda, the Adriatic, Tuscany, the Alps and major tourist cities as the expansion focus. Impressum: Deutsche Seereederei GmbH, Hamburg branch Am Kaiserkai 69, 20457 Hamburg; Geschäftsführung Horst Rahe and Thomas Pietzka; info@deutsche-seereederei.de; Hamburg phone +49 40 300 322 250. Karl J. Pojer has been publicly identified as CEO of DSR Hotel Holding in the 2023 Italy acquisition coverage. More likely as a hospitality/leisure capital source or operator partner than as a buyer of a pure private villa; Amalfi is adjacent to the stated Italian leisure geography but not named.",
    },
    {
        "city": "Düsseldorf",
        "company_name": "12.18. Group",
        "type": "hospitality_investor",
        "contact_name": "Uwe Drangmeister",
        "contact_role": "Geschäftsführer, 12.18. Investment Management GmbH",
        "email": "info@12-18.com",
        "phone": "+49 211 5808070",
        "website": "https://12-18.com/en/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Acquisition, development, repositioning and asset management of high-quality hotel and tourism real estate for institutional and private capital; European leisure destinations including Italian coastal resorts",
        "geographic_focus": "Düsseldorf HQ; track record in Sardinia (7Pines Resort Sardinia, Cone Club), Ibiza, Mallorca, Austria, UK, USA and German leisure destinations",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "group states hotel/leisure investment volume over €500M; typical resorts larger than €6M–€12M; unknown for a boutique coastal asset",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://12-18.com/en/",
        "source_2": "https://12-18.com/de/impressum",
        "notes": "Official site: 12.18. designs, realises and sells high-quality hotel and tourism properties; investment volume over €500M; Italian track record includes 7Pines Resort Sardinia (Destination by Hyatt) and Cone Club Sardinia. Impressum: 12.18. Investment Management GmbH, Königsallee 2b, 40212 Düsseldorf; info@12-18.com; +49 211 5 80 80 70; Geschäftsführer Uwe Drangmeister. Lindner family holds 50% of the group. After the 2024 operations merger, 12.18. focuses on acquiring and repositioning hotel real estate rather than operating. Strong German-origin leisure/coastal hospitality capital; ticket size of disclosed resorts is typically above this villa range, so fit is as a hospitality conversion/introduction path. Adrian Lindner is publicly identified as managing director of 12.18. Asset Management.",
    },
    {
        "city": "Düsseldorf",
        "company_name": "Lindner Hotel Group",
        "type": "hospitality_investor",
        "contact_name": "Adrian Lindner",
        "contact_role": "Member of the Board of Directors, Lindner Hotels AG",
        "email": "info@lindnerhotels.com",
        "phone": "+49 211 5997-310",
        "website": "https://www.lindnerhotelgroup.com/en/imprint",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Family-controlled hotel operator and lessee (Lindner, me and all, 7Pines, L-Collection); European leisure hotels including Sardinia",
        "geographic_focus": "Düsseldorf HQ; hotels in eight European countries and the USA, including 7Pines Resort Sardinia",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "operating portfolio far above €6M–€12M; unknown for a single boutique asset",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.lindnerhotelgroup.com/en/imprint",
        "source_2": "https://www.hospitalitynet.org/news/4121130/lindner-hotel-group-and-1218-group-merge-hotel-operations.html",
        "notes": "Official imprint: Lindner Hotels AG, Emanuel-Leutze-Strasse 17, 40547 Düsseldorf; info@lindnerhotels.com; +49 211 5997-310; board Adrian Lindner and Dr. Christoph Scherk. March 2024 hospitality coverage states LHG took over operation of five 12.18. hotels, adding Italy (7Pines Resort Sardinia), the UK and the USA; Arno Schwalie is named CEO of Lindner Hotel Group in that coverage. More relevant as a German family hospitality operator/brand for an Amalfi leisure conversion than as a likely bidder for a private villa. Sister relationship with 12.18. (separate row) — this row is the operating company.",
    },
    {
        "city": "Berlin",
        "company_name": "Gröner Family Office",
        "type": "family_office",
        "contact_name": "Christoph Gröner",
        "contact_role": "Management / Family Principal",
        "email": "info@groener-family.com",
        "phone": "+49 30 166 354 200",
        "website": "https://groener-family.de/en/home/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Single family office managing residential, commercial and hospitality real estate through the full property lifecycle; own hotel/hostel/F&B operating companies",
        "geographic_focus": "Berlin headquarters; properties in Germany, France and Italy, including South Tyrolean hospitality near Bruneck and Côte d'Azur assets",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://groener-family.de/en/home/",
        "source_2": "https://groener-family.de/en/imprint/",
        "notes": "Official family-office site states the portfolio includes residential, commercial and hospitality properties in Germany, France and Italy, and that GRONERS Hospitality operates recreation destinations including the South Tyrolean mountains near Bruneck. Imprint: Gröner Family Office Ltd, Binger Street 40, 14197 Berlin; info@groener-family.com; +49 30 166 354 200; management Christoph Gröner. Jean-Paul Albert is named Berlin location manager / authorised signatory. Italy exposure is evidenced (South Tyrol hospitality), not Amalfi specifically. Score capped because public materials emphasise operating hospitality and German development more than trophy coastal residences.",
    },
    {
        "city": "Baden-Baden",
        "company_name": "Oetker Collection (Oetker Hotel Management Company)",
        "type": "hospitality_investor",
        "contact_name": "Dr. Timo Grünert",
        "contact_role": "Chief Executive Officer",
        "email": "info@oetkerhotels.com",
        "phone": "+49 7221 900 8759",
        "website": "https://www.oetkercollection.com/legal/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Ultra-luxury 'Masterpiece' hotels; German family hospitality group operating trophy coastal and city hotels including Hotel La Palma, Capri",
        "geographic_focus": "Baden-Baden operating company; Masterpiece hotels in Europe and beyond, including Capri (Italy)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "strong",
        "estimated_ticket": "typical masterpiece hotels far above €6M–€12M; Hotel La Palma is owned by Reuben Brothers, not Oetker",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.oetkercollection.com/legal/",
        "source_2": "https://www.traveldailynews.com/hotels-lodging/oetker-collection-partners-with-reuben-brothers-to-open-first-italian-masterpiece-hotel/",
        "notes": "Official legal page for Oetker Hotel Management Company GmbH (Schillerstrasse 6, 76530 Baden-Baden) lists CEO Dr. Timo Grünert and CFO Jens Hackebeil; +49 7221 900 8759; info@oetkerhotels.com. Trade coverage confirms Hotel La Palma in Capri as Oetker Collection's first Italian Masterpiece Hotel (opened 2023), operated for owner Reuben Brothers. This is the strongest publicly evidenced German hospitality brand on the Capri/Amalfi doorstep. More likely as operator, brand partner or family-office introduction than as acquirer of a €6M–€12M private villa. Parent Oetker Collection KG in Bielefeld separately publishes contact@oetker-collection.com.",
    },
    {
        "city": "Mainz",
        "company_name": "LEOFF (Leoff Holding)",
        "type": "family_office",
        "contact_name": "Stephan Wollersheim",
        "contact_role": "Quoted principal / investment leadership (public site)",
        "email": "office@leoff.com",
        "phone": "+49 6131 33379-0",
        "website": "https://leoff.com/en/",
        "linkedin_company": "https://www.linkedin.com/company/leoff-asset-management",
        "linkedin_contact": "",
        "investment_focus": "Owner-managed investment house and family office for pan-European real estate investment, asset management, development and fund management",
        "geographic_focus": "Mainz HQ with offices in Munich, Berlin, Madrid and Milan",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown; recent disclosed deals are German retail, not trophy residential",
        "luxury_real_estate": "no",
        "hospitality_interest": "unclear",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "partially_verified",
        "source_1": "https://leoff.com/en/contact/",
        "source_2": "https://leoff.com/en/",
        "notes": "Official contact page lists Mainz HQ (Weissliliengasse 7, 55116 Mainz; office@leoff.com; +49 6131 33379-0) and a Milan office at Via San Raffaele 1. Company describes itself as an owner-managed investment house and family office for pan-European real estate. Homepage quotes Stephan Wollersheim. Recent news items on the same site are German retail acquisitions (Hörstel supermarket, Bramsche retail centre), so luxury/trophy fit is weak despite the Milan office. Included only as a German real-estate family office with an actual Italy location; not a Priority A buyer channel.",
    },
    {
        "city": "Bad Homburg",
        "company_name": "HQ Trust",
        "type": "family_office",
        "contact_name": "Jochen Butz",
        "contact_role": "Geschäftsführer",
        "email": "kontakt@hqtrust.de",
        "phone": "+49 6172 402 850",
        "website": "https://hqtrust.de/ueber-uns/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Multi-family office of the Harald Quandt family: family office, asset management and alternative investments including real estate, private equity, hedge funds and private debt",
        "geographic_focus": "Bad Homburg HQ with Düsseldorf and Berlin offices; German UHNW families, foundations and institutions; Wigmore Association international peer network",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "verified",
        "source_1": "https://hqtrust.de/impressum/",
        "source_2": "https://wigmoreassociation.com/member/hq-trust/",
        "notes": "Official imprint: HQ Trust GmbH, Harald Quandt Haus, Am Pilgerrain 17, 61352 Bad Homburg; kontakt@hqtrust.de; +49 6172 402 850; Geschäftsführung Jochen Butz, Christian Stadtmüller, Christian Subbe. Wigmore Association member page states alternative investments include real estate. No public evidence of Italian or Amalfi property allocations, so this is a German UHNW capital introducer rather than a demonstrated Italy buyer. Score capped accordingly; do not treat as a dedicated international-property desk.",
    },
    {
        "city": "Bad Homburg",
        "company_name": "FERI Family Office",
        "type": "family_office",
        "contact_name": "Michael Jänsch",
        "contact_role": "Bereichsvorstand, Wealth Management & Family Office",
        "email": "fag@feri.de",
        "phone": "+49 6172 916-0",
        "website": "https://www.feri.de/investment-advice/family-office",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Multi-family office and wealth management for entrepreneurial families, covering liquid and illiquid assets including reporting and controlling of real-estate holdings",
        "geographic_focus": "Bad Homburg; German and international family wealth (no public Italy real-estate mandate)",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "verified",
        "source_1": "https://www.feri.de/investment-advice/family-office",
        "source_2": "https://www.feri.de/impressum",
        "notes": "Official family-office page describes FERI as Germany's oldest multi-family office and names Michael Jänsch as Bereichsvorstand, Wealth Management & Family Office. Impressum: FERI AG, Rathausplatz 8-10, 61348 Bad Homburg; fag@feri.de; +49 6172 916-0. Included only because it advises substantial German family wealth that can include real estate; no public Italy, luxury-residential or hospitality mandate was found. Not a substitute for a dedicated international property advisor.",
    },
    {
        "city": "Munich",
        "company_name": "Savills Germany Hotels",
        "type": "international_property_advisor",
        "contact_name": "Tina Haller",
        "contact_role": "Head of Hotels Germany",
        "email": "",
        "phone": "+49 89 427 292 215",
        "website": "https://en.savills.de/people/munich/tina-haller.aspx",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Hotel investment sales, operator search, development advisory and asset management for German and international hotel owners and investors",
        "geographic_focus": "Munich-based German hotels team linked to Savills EMEA Hotels; Savills also has a luxury residential network in Italy",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "typical German hotel lots often larger than €6M–€12M; unknown for boutique assets",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://en.savills.de/people/munich/tina-haller.aspx",
        "source_2": "https://www.hotelbau.de/aktuelles/haller-wechselt-zu-savills/",
        "notes": "Official Savills people page: Tina Haller has led Hotels Germany from Munich since April 2026; direct +49 89 427 292 215; office +49 89 427 292 0, Rosental 4, 80331 Munich. She previously ran hotel asset management at the Dr. Hans Inselkammer family office (Hotel Königshof). No personal or hotels-desk email is published on the people page (Savills impressum webservices@savills.de is IT/web, so email is left empty). Fit is as an introducer to German hotel capital, not as a residential buyer representative. Italy interest is via the wider Savills network, not a published German-to-Amalfi mandate.",
    },
    {
        "city": "Munich",
        "company_name": "JLL Hotels & Hospitality Germany",
        "type": "international_property_advisor",
        "contact_name": "Heidi Schmidtke",
        "contact_role": "Managing Director Hotels & Hospitality Germany; Head of Operator Selection EMEA",
        "email": "",
        "phone": "+49 89 290 088 184",
        "website": "https://www.jll.com/de-de/people/bio-broker/heidi.schmidtke",
        "linkedin_company": "https://www.linkedin.com/company/jll",
        "linkedin_contact": "https://www.linkedin.com/in/heidi-schmidtke",
        "investment_focus": "Hotel investment sales, operator selection and advisory for owners and investors in the German-speaking countries; EMEA operator-selection leadership",
        "geographic_focus": "Munich; DACH hotel investors and EMEA operator search; biography notes early operational experience at a luxury hotel in Italy",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "typical institutional hotel tickets often larger than €6M–€12M",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.jll.com/de-de/people/bio-broker/heidi.schmidtke",
        "source_2": "https://www.jll.com/de-de",
        "notes": "Official JLL bio lists Heidi Schmidtke as Managing Director Hotels & Hospitality Germany and Head of Operator Selection EMEA, Munich, +49 89 290 088 184. The same bio states she previously worked in several departments of a luxury hotel in Italy. No public email is published on that bio, so email is empty. Relevant if the Amalfi asset is positioned as boutique hospitality to German hotel investors; not a residential UHNW agency. Stefan Giesemann is separately identified on LinkedIn as Managing Director in JLL's Hotels & Hospitality Group.",
    },
    {
        "city": "Hamburg",
        "company_name": "Kontora Family Office",
        "type": "family_office",
        "contact_name": "Stephan Buchwald",
        "contact_role": "Founder and Managing Director",
        "email": "",
        "phone": "",
        "website": "https://www.kontora.com/en/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Independent multi-family office and investment office for substantial German wealth, including private-markets access to real estate via a BaFin-regulated KVG; part of AlTi Tiedemann Global since 2025",
        "geographic_focus": "Hamburg; German families, foundations and institutions with expanded international private-markets access through AlTi",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "partially_verified",
        "source_1": "https://www.kontora.com/en/",
        "source_2": "https://www.kontora.com/en/investment-office/",
        "notes": "Official site: independent Hamburg multi-family office, now AlTi Tiedemann Global's German location; Investment Office covers private markets including real estate. FamilyOffice.de lists HQ at Jungfernstieg 51, 20354 Hamburg, and names Stephan Buchwald among managing directors. No public general sales/investment email or phone was taken from the pages reviewed (contact is form-based), so those fields are empty. No Italy or luxury-residential mandate is published. Included only as a German UHNW capital aggregator, not as a property specialist.",
    },
    {
        "city": "Munich",
        "company_name": "Inka / Inselkammer family hospitality investments",
        "type": "hospitality_investor",
        "contact_name": "Dr. Hans Inselkammer",
        "contact_role": "Family principal (Inka Karlsplatz / Hotel Königshof acquisition)",
        "email": "",
        "phone": "+49 89 237030",
        "website": "https://platzl.de/",
        "linkedin_company": "https://www.linkedin.com/company/platzl-hotels-muenchen",
        "linkedin_contact": "",
        "investment_focus": "Munich family hospitality ownership including Platzl Hotel and the acquisition of luxury Hotel Königshof; brewery and gastronomy assets",
        "geographic_focus": "Munich; no public Italian real-estate programme",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "no",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "Hotel Königshof is a large luxury hotel redevelopment, well above €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "partially_verified",
        "source_1": "https://www.immobilienmanager.de/hotel-koenigshof-bleibt-in-muenchener-familienbesitz-28102021",
        "source_2": "https://platzl.de/",
        "notes": "Immobilienmanager (2021) reported Inka Karlsplatz GmbH & Co. KG, associated with Dr. Hans Inselkammer, acquired the Hotel Königshof redevelopment in Munich. The family also owns Platzl Hotel (Platzl Hotel Inselkammer KG); LinkedIn lists +49 89 23 703 0. No investment email is published. Italy interest is not evidenced. Included only as a documented Munich luxury-hospitality family capital source; score capped because geography is domestic and tickets are hotel-scale.",
    },
    {
        "city": "Munich",
        "company_name": "Aigner Immobilien",
        "type": "luxury_agency",
        "contact_name": "Thomas Aigner",
        "contact_role": "Geschäftsführer and owner",
        "email": "",
        "phone": "+49 89 1787870",
        "website": "https://aigner-immobilien.de/",
        "linkedin_company": "https://www.linkedin.com/company/aigner-immobilien-gmbh",
        "linkedin_contact": "https://www.linkedin.com/in/thomas-aigner-a4800b82",
        "investment_focus": "Greater Munich residential brokerage including higher-value homes; strong local UHNW/HNW database",
        "geographic_focus": "Munich and surrounding districts; no evidenced international or Italy desk",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "no",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "4",
        "priority": "C",
        "verification_status": "partially_verified",
        "source_1": "https://aigner-immobilien.de/",
        "source_2": "https://www.linkedin.com/in/thomas-aigner-a4800b82",
        "notes": "Well-known Munich brokerage (Ruffininstrasse 26; +49 89 1787870) with owner Thomas Aigner. Included only as a possible Munich UHNW introducer. Public materials reviewed are Greater-Munich domestic; no international-property or Italy mandate was found, so this is a weak buyer-origin channel versus RIEDEL/Sotheby's/E&V Private Office. No public sales email was captured from the pages reviewed. Score deliberately low under the buyer-origin principle.",
    },
    {
        "city": "Potsdam",
        "company_name": "Sabine Lanz Finest Real Estate",
        "type": "luxury_agency",
        "contact_name": "Sabine Lanz",
        "contact_role": "Founder",
        "email": "",
        "phone": "",
        "website": "https://www.sabinelanz.de/en/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Top-end private residential in Potsdam and Berlin plus second-home markets; former Engel & Völkers Private Office partner",
        "geographic_focus": "Potsdam/Berlin primary homes; published second-home markets are Mallorca, Ibiza and Kitzbühel",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.sabinelanz.de/en/",
        "source_2": "https://www.sabinelanz.de/en/",
        "notes": "Official site positions the firm in first-class Potsdam/Berlin private real estate and second-home markets (Mallorca, Ibiza, Kitzbühel), with national and international partner networks. Founder states prior partnership with Engel & Völkers Private Office. No public email or phone was extracted from the homepage (contact is form/personal meeting). Italy is not listed among the named second-home markets. Fit is as a Berlin/Potsdam UHNW second-home advisor whose clients already buy European leisure property.",
    },
    {
        "city": "Hamburg",
        "company_name": "DR Hospitality (DSR / DER Touristik joint venture)",
        "type": "hospitality_investor",
        "contact_name": "Karl J. Pojer",
        "contact_role": "CEO, DSR Hotel Holding (publicly quoted on the Italy entry)",
        "email": "info@deutsche-seereederei.de",
        "phone": "+49 40 300 322 100",
        "website": "https://www.deutsche-seereederei.de/en/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Joint-venture hotel platform of DSR Hotel Holding and DER Touristik Group (REWE); Italian growth via majority stake in MIRA Hotels & Resorts",
        "geographic_focus": "German leisure source market plus Italy (Lake Garda, Adriatic, Tuscany, Alps, Italian cities)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "platform/hotel deals typically larger than €6M–€12M",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://italiabsolutely.com/tourism-industry/business/german-dsr-hotel-holding-acquires-75-of-the-mira-group",
        "source_2": "https://www.deutsche-seereederei.de/en/",
        "notes": "DSR's own history timeline and Italian trade press document DR Hospitality as the DSR–DER Touristik JV that bought 75% of MIRA in 2023. Karl Pojer is quoted as CEO of DSR Hotel Holding on that transaction. Wer-zu-wem lists DSR Hotel Holding at Am Kaiserkai 69, Hamburg, +49 40 300 322 100, with Karl J. Pojer among Geschäftsführer. Email used is the parent DSR inbox (no separate DR Hospitality inbox found). Related to, but commercially distinct from, the DSR holding row: this is the Italy-facing hotel JV with tour-operator capital. Qualitytravel (2025/26) reports a later MIRA management change under DSR ownership, confirming the Italian platform remains active.",
    },
    {
        "city": "Munich",
        "company_name": "Lake Tegernsee Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Michael Reiss",
        "contact_role": "Owner, Sotheby's International Realty Bavaria",
        "email": "tegernsee@bayern-sothebysrealty.com",
        "phone": "+49 89 744 24 189 0",
        "website": "https://muenchen-sothebysrealty.com/en/kontakt/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Alpine and lakeside luxury villas, country houses and second homes for southern-Bavarian UHNW clients, with international Sotheby's referrals",
        "geographic_focus": "Lake Tegernsee, Schliersee, Bad Tölz; same Bavarian ownership as Munich SIR, serving a leisure/second-home buyer pool",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://muenchen-sothebysrealty.com/en/kontakt/",
        "source_2": "https://bayern-sothebysrealty.com/en/",
        "notes": "Same ownership as Bayern Sotheby's Munich but a distinct leisure/second-home desk at Seestrasse 10, 83700 Rottach-Egern; tegernsee@bayern-sothebysrealty.com. Alpine-lake UHNW clients are a plausible origin market for Mediterranean trophy homes. Kept as a separate row because the Tegernsee book is second-home/leisure rather than Munich city primary homes. Not a duplicate of the Munich city office.",
    },
    {
        "city": "Hamburg",
        "company_name": "Colliers Hotels Germany",
        "type": "international_property_advisor",
        "contact_name": "Andreas Ewald",
        "contact_role": "Geschäftsführer, Head of Hotel Germany; EMEA Hospitality Practice Group",
        "email": "Andreas.Ewald@colliers.com",
        "phone": "+49 40 328701 195",
        "website": "https://www.colliers.com/en-de/experts/andreas-ewald",
        "linkedin_company": "https://www.linkedin.com/company/colliers",
        "linkedin_contact": "https://www.linkedin.com/in/andreas-ewald-5957835",
        "investment_focus": "Hotel capital markets, transactions and advisory for institutional investors, developers and operators; previously founded Engel & Völkers Hotel Consulting",
        "geographic_focus": "Hamburg-based German hotel desk within Colliers EMEA Hospitality; public commentary includes luxury hospitality in Mediterranean destinations",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "typical institutional hotel lots often larger than €6M–€12M",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.colliers.com/en-de/experts/andreas-ewald",
        "source_2": "https://www.hotelbau.de/aktuelles/colliers-hotelsparte-deutschland/",
        "notes": "Official Colliers expert page names Andreas Ewald as Geschäftsführer, Head of Hotel | Germany; office +49 40 328701 195; Andreas.Ewald@colliers.com. Hotelbau (Feb 2026) confirms he took Head of Hotel Germany from 1 Feb 2026, based in Hamburg, after founding Engel & Völkers Hotel Consulting. A Hospitality Investor interview quotes him on investor interest in luxury hospitality in Mediterranean destinations as well as German operational hotels. Fit is as an introducer of German/European hotel capital to a coastal hospitality reading of the Amalfi asset, not as a residential UHNW broker. Ticket sizes of institutional hotel deals are often above this range.",
    },
]


def main() -> None:
    out = Path("/workspace/data/real-estate-prospects/germany.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for row in ROWS:
            full = {h: row.get(h, "") for h in HEADERS}
            full["country"] = COUNTRY
            full["last_verified"] = LAST_VERIFIED
            writer.writerow(full)
    print(f"Wrote {len(ROWS)} rows to {out}")


if __name__ == "__main__":
    main()
