#!/usr/bin/env python3
"""Generate the China luxury real-estate prospect CSV from verified research notes.

Buyer-origin principle: every row must provide realistic access to Chinese
(including Hong Kong SAR) buyers or Chinese capital for a €6M–€12M Amalfi Coast
luxury/trophy asset. Generic domestic PRC brokerages, mass overseas new-home
platforms, distressed developers, and incompatible institutional funds are excluded.
"""

from __future__ import annotations

import csv
from pathlib import Path

HEADERS = [
    "country",
    "city",
    "company_name",
    "type",
    "contact_name",
    "contact_role",
    "email",
    "phone",
    "website",
    "linkedin_company",
    "linkedin_contact",
    "investment_focus",
    "geographic_focus",
    "buyer_origin_relevance",
    "italy_interest",
    "amalfi_coast_relevance",
    "estimated_ticket",
    "luxury_real_estate",
    "hospitality_interest",
    "fit_score",
    "priority",
    "verification_status",
    "source_1",
    "source_2",
    "notes",
    "last_verified",
]

LAST_VERIFIED = "2026-08-27"
COUNTRY = "China"

ROWS = [
    {
        "city": "Hong Kong",
        "company_name": "Knight Frank Private Office (Hong Kong)",
        "type": "private_office",
        "contact_name": "Ho-Pin Tung",
        "contact_role": "Director, Head of Private Office",
        "email": "info@hk.knightfrank.com",
        "phone": "+852 2846 4828",
        "website": "https://www.knightfrank.com.hk/private-office",
        "linkedin_company": "https://www.linkedin.com/company/knight-frank-greaterchina",
        "linkedin_contact": "https://www.linkedin.com/in/hopin",
        "investment_focus": "UHNW and family-office advisory across prime residential and commercial; off-market global villas, penthouses, chalets and islands",
        "geographic_focus": "Hong Kong Private Office hub serving Greater China clients into Knight Frank's global network, including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "UHNW / compatible with €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.knightfrank.com.hk/private-office",
        "source_2": "https://www.knightfrank.co.uk/newsroom/article/2026/1/knight-frank-strengthens-italian-presence-with-new-preferred-agency-in-milan",
        "notes": "Official HK Private Office page names Ho-Pin Tung as Director, Head of Private Office, one of Knight Frank's dedicated Private Office hubs (with London, Dubai, New York and Singapore). The page states the team advises HNW clients and family offices on prime residences in Hong Kong and global opportunities including London penthouses and European capital markets, with off-market villas, chalets and islands. Direct personal email is not published; info@hk.knightfrank.com is the official HQ mailbox on the leadership page (4/F Shui On Centre, 6-8 Harbour Road, Wan Chai; +852 2840 1177). People-page office line for Tung is +852 2846 4828. January 2026 Knight Frank newsroom states the firm is established across Lake Como, Florence, Lucca, Umbria, Sardinia, Portofino and Venice and has added Lincs Estate as Milan preferred agency. Amalfi Coast is not named among those Italian destinations, so Amalfi relevance is unclear rather than strong. Distinct from the Greater China International Project Marketing desk (Samantha Yu).",
    },
    {
        "city": "Shanghai",
        "company_name": "Knight Frank International Residential (Greater China)",
        "type": "luxury_agency",
        "contact_name": "Samantha Yu",
        "contact_role": "Senior Director, Head of International Project Marketing, Greater China",
        "email": "info@hk.knightfrank.com",
        "phone": "+86 137 6178 7912",
        "website": "https://www.knightfrank.com.hk/residential/international-properties/buying",
        "linkedin_company": "https://www.linkedin.com/company/knightfrankhk-international-properties",
        "linkedin_contact": "https://www.linkedin.com/in/samantha-yu-03648899",
        "investment_focus": "International residential project marketing and buyer representation for Greater China clients acquiring homes and investment property outside their home market",
        "geographic_focus": "Shanghai-based Greater China desk; Knight Frank International Residential Sales Limited sells non-Hong Kong property worldwide, with a dedicated UK-properties line in Hong Kong",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.knightfrank.com.hk/residential/international-properties/buying",
        "source_2": "https://www.knightfrank.co.uk/contact/people/samantha-yu-cnkfsh00329",
        "notes": "Official HK international-buying page lists Samantha Yu as the key contact: Senior Director, Head of International Project Marketing, Greater China. The trading entity Knight Frank International Residential Sales Limited works exclusively on properties outside Hong Kong. Official people page publishes mobile +86 137 6178 7912 and locates her in Shanghai. Personal email is not published (enquiry forms only); the verified generic mailbox is info@hk.knightfrank.com. Company LinkedIn for Knight Frank HK International Properties also publishes +852 2846 7418 for non-US property enquiries. Italy access is via Knight Frank's Italian associate network (Lake Como, Florence, Lucca, Umbria, Sardinia, Portofino, Venice, Milan/Lincs), not a published Amalfi mandate. This row is the mainland-China originator desk; do not treat as a duplicate of the Hong Kong Private Office.",
    },
    {
        "city": "Hong Kong",
        "company_name": "Savills Hong Kong International Residential",
        "type": "luxury_agency",
        "contact_name": "Mark Elliott",
        "contact_role": "Head of International Residential Sales",
        "email": "",
        "phone": "+852 2842 4294",
        "website": "https://www.savills.com.hk/people/mark-elliott.aspx",
        "linkedin_company": "https://www.linkedin.com/company/savills-hong-kong",
        "linkedin_contact": "https://www.linkedin.com/in/mark-elliott-942b4011b",
        "investment_focus": "Overseas residential sales to Hong Kong and Asia-based buyers; prime international houses, apartments and development stock",
        "geographic_focus": "Hong Kong IRS desk; published project experience in UK (Prime Central London), USA, Canada, Australia and New Zealand, with routing into Savills Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.savills.com.hk/people/mark-elliott.aspx",
        "source_2": "https://en.savills.it/offices/milan-residential.aspx",
        "notes": "Official Savills HK people page and management page confirm Mark Elliott as Head of International Residential Sales. Direct line +852 2842 4294; office 23/F Two Exchange Square, 8 Connaught Place, Central; switchboard +852 2842 4400. Official JSON-LD AgentEmailAddress is blank, so email is left empty rather than patterned. His published markets are UK/USA/Canada/Australia/New Zealand, with Prime Central London as a core market; he is not licensed for Hong Kong property. Italy interest is at firm level: Savills Italia operates a Milan residential office (Via Brera 3, +39 02 83 97 80 80) plus Rome, so a Greater China IRS client can be routed into Italian prime residential. Amalfi is not named on the HK people page.",
    },
    {
        "city": "Shanghai",
        "company_name": "Savills China International Property",
        "type": "luxury_agency",
        "contact_name": "Michelle Zhou",
        "contact_role": "Head of International Property China (中国区国际地产部)",
        "email": "",
        "phone": "+86 21 6391 6688 ext. 8685",
        "website": "https://www.savills.com.cn/people/shanghai/michelle-zhou.aspx",
        "linkedin_company": "https://www.linkedin.com/company/savills",
        "linkedin_contact": "https://www.linkedin.com/in/michelle-zhou-b3434938",
        "investment_focus": "Outbound international residential and mid/high-end assets for high-net-worth Chinese investors; marketing of overseas developments into mainland China",
        "geographic_focus": "Shanghai HQ covering Chinese Mainland clients into Savills' global network, including Savills Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.savills.com.cn/people/shanghai/michelle-zhou.aspx",
        "source_2": "https://www.savills.com.cn/services/international-property.aspx",
        "notes": "Official Savills China people page names 周玉 (Michelle Zhou) as head of 中国区国际地产部, with direct +86 21 6391 6688 ext. 8685 and office at 25/F Two ICC, 288 South Shaanxi Road, Xuhui, Shanghai. Official AgentEmailAddress is blank, so email is empty. The International Property service page states the team selects high-end residential and commercial projects for Chinese investors and cross-sells overseas property through Savills' China network. Italy is not named on the Shanghai pages; relevance is the Savills Italy residential platform, not a published Amalfi mandate. Distinct from the Hong Kong IRS desk (Mark Elliott): this is the mainland-China originator.",
    },
    {
        "city": "Hong Kong",
        "company_name": "List Sotheby's International Realty Hong Kong",
        "type": "luxury_agency",
        "contact_name": "Sakura Hirayama",
        "contact_role": "Associate Director, International Business",
        "email": "sakurah@listsirhk.com",
        "phone": "+852 6090 8558",
        "website": "https://www.listsothebysrealtyhk.com/our-team/sakura-hirayama",
        "linkedin_company": "https://www.linkedin.com/company/sothebysrealtyhk",
        "linkedin_contact": "",
        "investment_focus": "Overseas residential and commercial assets for Greater China private investors, corporates and investment groups, plus Hong Kong luxury brokerage via the Sotheby's International Realty network",
        "geographic_focus": "Hong Kong affiliate (Causeway Bay) with SIR coverage in 80+ countries including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.listsothebysrealtyhk.com/our-team/sakura-hirayama",
        "source_2": "https://www.listsothebysrealtyhk.com/our-team/may-teng",
        "notes": "Official agent page publishes sakurah@listsirhk.com and +852 6090 8558. Bio states she leads international project and client development for overseas residential and commercial assets and works with private investors, corporates and investment groups across Greater China; prior role was Deputy GM of Overseas Business Development at QFang. Licence: List International Realty Limited C-073987. Parallel official referral contact May Teng (Manager), mayt@listsirhk.com, +852 9504 7597, is named as the Sotheby's Global Referral Network Hong Kong contact. Italy is via the SIR affiliate network, not a named HK Italy desk. Woody Mah is listed as Managing Director on LinkedIn but his live agent URL redirects, so he is not used as the contact. Office published on the contact page: 3604-06, 36/F, Tower Two, Times Square, 1 Matheson Street, Causeway Bay; also +852 6063 9364.",
    },
    {
        "city": "Hong Kong",
        "company_name": "Christie's International Real Estate Hong Kong",
        "type": "luxury_agency",
        "contact_name": "Samson Law",
        "contact_role": "Managing Director",
        "email": "info@cirehk.com",
        "phone": "+852 6203 6369",
        "website": "https://christiesrealestatehk.com/en/about-us/contact",
        "linkedin_company": "https://www.linkedin.com/company/cirehk",
        "linkedin_contact": "https://www.linkedin.com/in/samson-law-32537014",
        "investment_focus": "Hong Kong trophy residential plus CIRE global luxury referrals for HNW buyers and investors",
        "geographic_focus": "Admiralty, Hong Kong, with Christie's International Real Estate affiliates in ~50 countries including Mediterranean/European luxury markets",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://christiesrealestatehk.com/en/about-us/contact",
        "source_2": "https://finance.yahoo.com/news/christie-international-real-estate-enters-030000879.html",
        "notes": "Official contact page publishes info@cirehk.com, +852 6203 6369 and Unit 56, Level 35, Two Pacific Place, 88 Queensway, Admiralty (EAA C-102075-A000). GlobeNewswire 29 Jan 2025 names Hong Kong native Samson Law as MD, citing a two-decade private-client database and mainland-China spillover into Hong Kong. CIRE network-level Italy/Mediterranean coverage is the Italy hook; Amalfi is not a named HK desk. This 2025 affiliate is the current CIRE brand in Hong Kong and is distinct from historic Landscope Christie's (2012). Individual agent emails are not published on the agents grid.",
    },
    {
        "city": "Chongqing",
        "company_name": "Chongqing Tianci Hot Spring Group",
        "type": "hospitality_investor",
        "contact_name": "Yang Changlin",
        "contact_role": "Chairman",
        "email": "Office@tiancihotspring.com",
        "phone": "+86 23 4155 5555",
        "website": "https://en.tiancihotsprings.com/contact.html",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Hot-spring resorts, tourism real estate and European heritage hospitality (chateau and thermal spa)",
        "geographic_focus": "Chongqing/Sichuan operating base; France (Château d'Esclimont); Italy (Bracciano / Vicarello thermal spa estate)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "documented Italian acquisition about US$18M (2018); compatible with €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "partially_verified",
        "source_1": "https://en.tiancihotsprings.com/contact.html",
        "source_2": "https://www.ichongqing.info/2018/11/06/chongqing-tianci-hot-springs-will-build-a-town-with-italian-vicarello/",
        "notes": "Official English site still lists Bracciano Thermal Spa Resort and Bracciano Castle among subsidiaries and publishes Office@tiancihotspring.com plus Chongqing Huatang +86 23 4155 5555 and France Château d'Esclimont +33 (0)2 3731 1515. 2018 CIIE coverage (iChongqing / CRI) reported a US$18 million acquisition of the Vicarello project ~40 km from Rome, with Chairman Yang Changlin (杨长林) and President Yang Yunfan (杨云帆) named. Personal emails are not published. Follow-through on the Italian spa-town plan is not evidenced in 2023–2026 English-language construction coverage, so verification is partial. Closest documented Chinese corporate analogue to a €6M–€12M Italian hospitality/heritage estate. Amalfi relevance is weak (Lazio lakes, not Campania coast).",
    },
    {
        "city": "Guangzhou",
        "company_name": "Seedland (Shidi Group)",
        "type": "private_capital",
        "contact_name": "Zhang Liang",
        "contact_role": "Founder and Chairman",
        "email": "",
        "phone": "",
        "website": "https://www.seedland.cc/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Principal family capital; documented Italian Riviera trophy-villa purchase; domestic China real-estate development via Seedland",
        "geographic_focus": "Guangzhou-headquartered group; personal Ligurian coastal trophy asset in Portofino",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "documented Portofino villa about €30–35M (2019); capacity above €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "partially_verified",
        "source_1": "https://www.ansa.it/english/news/lifestyle/travel/2019/02/18/chinese-buys-iconic-portofino-villa_b01d3edc-6249-4810-afe4-cb49ca13ef65.html",
        "source_2": "https://www.ilsole24ore.com/art/villa-portofino-un-cinese-35-milioni-aumento-case-lusso-vendute-stranieri-ABaU2ZVB",
        "notes": "ANSA (18 Feb 2019) and Il Sole 24 Ore reported that Zhang Liang (Johnson Zhang), founder of Guangzhou's Seedland / Shidi Group and son of R&F Properties founder Zhang Li, bought Villa Buonaccordo / Villa Pagani in Portofino for about €30–35 million — the only named Chinese buyer of an iconic Italian coastal trophy villa in the public record reviewed. No public investment or personal email is published, so those fields are empty. Official website is seedland.cc. Credit caution: R&F has been in distressed overseas retreat and Seedland faced leverage stress after 2021, so 2019 capacity is not proof of a 2026 bid. Included as family/principal capital with proven Ligurian-coast trophy DNA, not as a corporate fund. Amalfi relevance is moderate (Italian coastal trophy precedent, different coastline).",
    },
    {
        "city": "Hong Kong",
        "company_name": "JLL Hong Kong International Residential",
        "type": "luxury_agency",
        "contact_name": "Felix Cheung",
        "contact_role": "Head of International Residential, Hong Kong",
        "email": "",
        "phone": "+852 2156 3472",
        "website": "https://www.jll.com/en-hk/people/bio-broker/felix.cheung",
        "linkedin_company": "https://www.linkedin.com/company/jll-greater-china",
        "linkedin_contact": "https://www.linkedin.com/in/felix-k-m-cheung-49024a2b",
        "investment_focus": "Overseas residential project sales and advisory for Hong Kong HNW clients, family offices and real-estate funds",
        "geographic_focus": "Hong Kong originator desk; published markets UK, US, Japan and Dubai",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.jll.com/en-hk/people/bio-broker/felix.cheung",
        "source_2": "https://www.jll.com/en-hk/newsroom/jll-promotes-felix-cheung-to-head-of-international-residential-hong-kong",
        "notes": "Official JLL people page and 27 Mar 2025 promotion release confirm Felix Cheung (章覺文) as Head of International Residential, Hong Kong, with +852 2156 3472. Bio states he maintains a network of HNW clients, family offices and real-estate funds across Asia and has marketed UK/US/Japan (and, in the release, Dubai) residential projects. Official people page does not publish an email, so email is empty. Italy is not named among published markets, which caps the score despite strong Hong Kong buyer-origin access. JLL's wider Italian commercial platform is not treated as proof of a luxury coastal residential desk.",
    },
    {
        "city": "Hong Kong",
        "company_name": "Landscope International",
        "type": "luxury_agency",
        "contact_name": "Keng Shing Koh",
        "contact_role": "Founder and Chief Executive",
        "email": "info@landscope.com",
        "phone": "+852 2866 0022",
        "website": "https://www.landscope-international.com/aboutus",
        "linkedin_company": "https://www.linkedin.com/company/landscopehk",
        "linkedin_contact": "https://www.linkedin.com/in/keng-shing-koh-6908356b",
        "investment_focus": "Hong Kong luxury residential plus overseas new-homes marketing to an affluent Hong Kong and mainland-China client database",
        "geographic_focus": "Wan Chai HQ; live international inventory concentrated on UK, US, Canada, Germany, Malaysia and Thailand",
        "buyer_origin_relevance": "strong",
        "italy_interest": "no",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.landscope-international.com/aboutus",
        "source_2": "https://www.landscope.com/privacy-policy",
        "notes": "Official about page claims a database of 130,000 affluent Hong Kong clients and China's 2,000 billionaires, and an international sales team marketing residential, commercial and investment property across key global markets. Contact: Units 1201-3, 12/F Siu On Centre, 188 Lockhart Road, Wan Chai; +852 2866 0022; info@landscope.com (privacy policy plaintext). K.S. Koh is the publicly identified founder/CEO. Landscope was the 2012 exclusive CIRE Hong Kong affiliate; the current CIRE brand in Hong Kong is the 2025 Samson Law office, so this row is Landscope's own luxury/overseas desk, not Christie's. Italy is not among live marketed countries on the international site, which is why italy_interest is no despite strong Greater China UHNW access.",
    },
    {
        "city": "Hong Kong",
        "company_name": "Gaw Capital Partners",
        "type": "private_equity_real_estate",
        "contact_name": "Goodwin Gaw",
        "contact_role": "Chairman and Managing Principal",
        "email": "info@gawcapital.com",
        "phone": "+852 2583 7700",
        "website": "https://www.gawcapital.com/zh/contact-us/",
        "linkedin_company": "https://www.linkedin.com/company/gaw-capital",
        "linkedin_contact": "",
        "investment_focus": "Family-backed real-estate private equity including hospitality; historic European hospitality fund now marked exited",
        "geographic_focus": "Hong Kong HQ with Shanghai, Guangzhou, London and Lisbon offices; live book is predominantly APAC",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "commingled hospitality deals typically far above €6M–€12M; family cheque unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.gawcapital.com/zh/contact-us/",
        "source_2": "https://www.gawcapital.com/services/real-estate-funds/hospitality-fund/european-hospitality-fund/",
        "notes": "Official Chinese/English contact pages publish 18/F, 68 Yee Wo Street, Causeway Bay; +852 2583 7700; info@gawcapital.com (career@gawcapital.com is HR-only). Founders Goodwin and Kenneth Gaw also control Pioneer Global Group from the same building. Gaw European Hospitality Fund I (Hospes Spain, InterContinental Porto and related assets) is marked exited on the official fund page; press rumours that Gaw would buy Sofitel Roma Villa Borghese did not complete (EXTENDAM closed Rome and Lisbon Sofitels in 2024). Included as Hong Kong family real-estate capital with a documented European hospitality track record, not as a live Italy fund. A €6M–€12M villa is below typical fund tickets; a Gaw family lifestyle cheque is more plausible than the PE vehicle. GCP Hospitality (Bangkok) is the operating platform, not a separate row.",
    },
    {
        "city": "Hong Kong",
        "company_name": "Langham Hospitality Group",
        "type": "hospitality_investor",
        "contact_name": "Josh Littman",
        "contact_role": "Head of Development – EMEA",
        "email": "",
        "phone": "+852 2186 2388",
        "website": "https://www.langhamhospitalitygroup.com/en/media/latest-news/langham-hospitality-group-names-josh-littman-as-emea-development-lead/",
        "linkedin_company": "https://www.linkedin.com/company/langham-hospitality-group",
        "linkedin_contact": "",
        "investment_focus": "Luxury hotels and branded residences; Great Eagle family ownership of selected assets plus management-contract growth",
        "geographic_focus": "Hong Kong parent (Great Eagle Holdings) with EMEA development led from London; Italian coastal/lagoon project in Venice/Murano",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "Venice site acquired 2019 for about €32.5M; typical hotels larger than €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.langhamhospitalitygroup.com/en/media/latest-news/langham-hospitality-group-names-josh-littman-as-emea-development-lead/",
        "source_2": "https://www.ilsole24ore.com/art/hotel-via-lavori-il-langham-venice-AE3fbkZD",
        "notes": "Wholly owned by Hong Kong's Great Eagle Holdings (Lo family). Official 1 June 2026 release appoints Josh Littman as Head of Development – EMEA to secure hotel and branded-residence contracts, citing The Langham, Venice. Il Sole 24 Ore reported Rio dei Vetrai Srl (Great Eagle) bought the Murano site in 2019 for about €32.5 million. Direct development email is not published; Rick.Gangwani@langhamhotels.com and Katie.A.Forster@langhamhotels.com are media contacts and are not used here. Phone is the published Hong Kong corporate range. Relevant as Hong Kong family hospitality capital with a live Italian luxury-hotel project, not as a likely bidder for a single €6M–€12M residence unless positioned as a small hotel or branded-residence conversion. Amalfi is not named.",
    },
    {
        "city": "Hong Kong",
        "company_name": "BARNES Mekong (Hong Kong)",
        "type": "luxury_agency",
        "contact_name": "Soreasmey Ke Bin",
        "contact_role": "Managing Partner",
        "email": "",
        "phone": "",
        "website": "https://www.barnes-international.com/en/contact/china/barnes-mekong.html",
        "linkedin_company": "https://www.linkedin.com/showcase/barnes-international/",
        "linkedin_contact": "",
        "investment_focus": "Ultra-luxury residential; international private-client referrals through the BARNES network including Italy",
        "geographic_focus": "Quarry Bay, Hong Kong, plus Mekong-region coverage; BARNES offices across France, Italy and other European luxury destinations",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.barnes-international.com/en/contact/china/barnes-mekong.html",
        "source_2": "https://www.barnes-international.com/en/about-barnes/find-an-agency.html",
        "notes": "Official BARNES agency page lists Wing Wah Building, 677 King's Road, Quarry Bay, Hong Kong, and names Soreasmey Ke Bin as Managing Partner and Ludovic Hautin as Head of Development. No public sales email or Hong Kong phone is published on that page (the network finder shows a Cambodia mobile for the Mekong shop, which is not used here). FAQ copy emphasises international buyers, particularly French clients investing in Hong Kong, so Greater China buyer-origin is scored moderate rather than strong. Italy interest is via BARNES Italian offices and the Paris Private Office UHNW network, not a published Hong Kong-to-Amalfi mandate.",
    },
    {
        "city": "Shanghai",
        "company_name": "Fosun Tourism Group",
        "type": "hospitality_investor",
        "contact_name": "",
        "contact_role": "Investment and Business Partners (Group)",
        "email": "investment@fosun.com",
        "phone": "",
        "website": "https://en.fosun.com/other/contact.html",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Global upscale all-inclusive resorts (Club Med) and vacation-asset management; asset-light/asset-right tourism",
        "geographic_focus": "Shanghai-headquartered Fosun; Club Med operating in Italy (Cefalù, Pragelato) with San Sicario pipeline",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "Italian resort projects far above €6M–€12M (San Sicario about €135M)",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://en.fosun.com/other/contact.html",
        "source_2": "https://en.ilsole24ore.com/art/club-med-bets-on-italy-and-opens-in-san-sicario-AHMLAywC",
        "notes": "Fosun has owned Club Med since 2015. Official Fosun contact page publishes investment@fosun.com for investment and business partners (ir@fosun.com is equity-investor IR and is not used). Il Sole 24 Ore and REAM SGR confirm Club Med Cefalù (Exclusive Collection) and Pragelato Sestriere in operation, plus Club Med San Sicario (~400 rooms, opening 2028, ~€135M) where Italian fund REAM SGR/Fondo Itera owns the land and Club Med is operator. Club Med has discussed further Italian sun destinations (Sardinia/Sicily). A €6M–€12M Amalfi villa does not match Club Med's published resort size criteria, so this is a Chinese hospitality-capital introduction path, not a likely bidder. Named Italy development principal with a deal email is not published. Do not use ethics/whistleblowing addresses.",
    },
    {
        "city": "Hong Kong",
        "company_name": "Rosewood Hotel Group",
        "type": "hospitality_investor",
        "contact_name": "Sonia Cheng",
        "contact_role": "Chief Executive Officer",
        "email": "",
        "phone": "+852 2138 2222",
        "website": "https://rosewoodhotelgroup.com/en-us/contact-us",
        "linkedin_company": "https://www.linkedin.com/company/rosewood-hotel-group",
        "linkedin_contact": "https://www.linkedin.com/in/soniachengrosewood",
        "investment_focus": "Ultra-luxury hotel management (Rosewood) owned by the Cheng family's Chow Tai Fook Enterprises; typically manager not propco",
        "geographic_focus": "Hong Kong HQ (Quarry Bay) plus Shanghai, Dallas and Amsterdam offices; operating Italian asset at Castiglion del Bosco, Tuscany",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown; managed hotels far above €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://rosewoodhotelgroup.com/en-us/contact-us",
        "source_2": "https://www.prnewswire.com/news-releases/rosewood-milan-to-open-in-2025-301660303.html",
        "notes": "Official contact page lists 21/F K11 Atelier, 728 King's Road, Quarry Bay, Hong Kong SAR and +852 2138 2222; the property-development email field on that page is not published, so email is empty. Sonia Cheng is publicly identified as CEO and as a Cheng/Chow Tai Fook family principal. Rosewood Castiglion del Bosco in Tuscany is an operating Italian luxury hospitality asset; Rosewood Milan is a management deal with Gruppo Statuto as owner. Lake Como Rosewood rumours were not confirmed. Useful as Hong Kong family luxury-hospitality access and an Italy operator, not as a likely equity buyer of a €6M–€12M house. Buyer-origin is moderate because the listed vehicle manages rather than buys the real estate; a Cheng family personal cheque is unpublished.",
    },
    {
        "city": "Kunming",
        "company_name": "China Multi Service",
        "type": "international_property_advisor",
        "contact_name": "Marco Conti",
        "contact_role": "Founder and President",
        "email": "info@chinamultiservice.com",
        "phone": "+86 871 6362 8227",
        "website": "https://www.chinamultiservice.com/en/contact-us/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Italy–China advisory for Chinese companies seeking Italian hotels and tourism real estate",
        "geographic_focus": "Published China office in Kunming, Yunnan, with long-running Italy activity",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.chinamultiservice.com/en/contact-us/",
        "source_2": "https://www.chinamultiservice.com/en/invest-in-italy-the-best-opportunity-is-in-hotel-development/",
        "notes": "Official contact page publishes Apt. 103, Bld. 2 Binjiang Junyuan, Panlong District, Kunming; info@chinamultiservice.com; +86 (0)871 6362 8227. Site copy states the team has followed two Chinese-company hotel investments in Italy and helps Chinese principals find Italian hotels. Those two deals were not independently named in this pass, so verification is partial. Introducer, not a principal buyer. Fit is as a China-side hospitality-capital introducer into Italy rather than as an Amalfi trophy specialist.",
    },
    {
        "city": "Hong Kong",
        "company_name": "The Hongkong and Shanghai Hotels (Peninsula)",
        "type": "hospitality_investor",
        "contact_name": "Benjamin Vuchot",
        "contact_role": "Chief Executive Officer",
        "email": "corpaffairs@peninsula.com",
        "phone": "+852 2840 7788",
        "website": "https://www.hshgroup.com/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Owner-operator of a short list of Peninsula luxury hotels; branded-residence concepts under discussion",
        "geographic_focus": "Hong Kong (Kadoorie family); Europe hotels in London, Paris and Istanbul; no Peninsula hotel in Italy",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "flagship hotels far above €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.hshgroup.com/en/media/press-releases/2026/the-hongkong-and-shanghai-hotels-limited-annual-results-for-the-year-ended-31-december-2025",
        "source_2": "https://worth.com/peninsulas-long-game/",
        "notes": "Official 2025 results release publishes corpaffairs@peninsula.com plus lynnemulholland@peninsula.com and lilianlau@peninsula.com as corporate-affairs contacts (not a development inbox). Group switchboard +852 2840 7788 is the published corporate line. CEO Benjamin Vuchot (from March 2025) discussed branded residences in Southern Italy, Southern Spain and Japanese ski lodges in a Worth profile — aspiration, not a signed deal — which is why italy_interest is unclear. No Peninsula hotel in Italy. Included only as Kadoorie-family luxury hospitality capital that has publicly mentioned Southern Italy branded residences. Ticket size of a Peninsula hotel is incompatible with a €6M–€12M house.",
    },
    {
        "city": "Hong Kong",
        "company_name": "Invest Hong Kong Family Office",
        "type": "other_relevant",
        "contact_name": "Jason Fong",
        "contact_role": "Global Head of Family Office",
        "email": "jasonfong@investhk.gov.hk",
        "phone": "+852 3107 1085",
        "website": "https://tel.directory.gov.hk/0240006837_ENG.html",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Official HKSAR gateway to single-family offices setting up in or operating from Hong Kong; not a real-estate brokerage",
        "geographic_focus": "Hong Kong family-office community, including mainland-China principals using Hong Kong structures",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "verified",
        "source_1": "https://tel.directory.gov.hk/0240006837_ENG.html",
        "source_2": "https://www.investhk.gov.hk/",
        "notes": "HKSAR telephone directory (updated 27 Aug 2026) publishes Jason Fong as Global Head of Family Office, jasonfong@investhk.gov.hk, +852 3107 1085, with deputies Jolly Yip (jollycfyip@investhk.gov.hk) and several SVPs. Mandate is attracting and serving family offices in Hong Kong, not selling Italian property. Included only as a documented door into unnamed Hong Kong/Chinese family offices that may allocate to European lifestyle real estate. Do not treat as a qualified Amalfi buyer or luxury agency. Score capped because there is no published Italy or real-estate-advisory function.",
    },
    {
        "city": "Beijing",
        "company_name": "Reignwood Group",
        "type": "family_office",
        "contact_name": "Chanchai Ruayrungruang",
        "contact_role": "Founder and Chairman",
        "email": "",
        "phone": "+86 10 8528 8528",
        "website": "http://reignwood.com/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Family-controlled trophy hospitality and lifestyle real estate (golf clubs, branded residences)",
        "geographic_focus": "Beijing HQ with Hong Kong and London offices; documented UK trophies (Wentworth Club, Ten Trinity Square / Four Seasons London)",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "no",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "disclosed European trophies well above €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "partially_verified",
        "source_1": "https://www.wentworthclub.com/reignwood/",
        "source_2": "http://reignwood.com/",
        "notes": "Reignwood (华彬), founded by Dr Chanchai Ruayrungruang / Yan Bin, owns Wentworth Club in Surrey and Ten Trinity Square in London (Four Seasons Hotel, residences and private club). Those are European trophy hospitality/residential assets and evidence of UHNW lifestyle capital from a Beijing-based group. No Italy evidence was found. Pine Cliffs (Algarve) is not a Reignwood asset. Official contact page phones include Beijing +86 10 8528 8528 and Hong Kong +852 2396 1638; no investment email was confirmed on a fully rendered official page, so email is empty. Score capped: strong European trophy DNA but no Italy and tickets far above this asset.",
    },
]


def validate_rows(rows: list[dict]) -> None:
    allowed_type = {
        "luxury_agency",
        "private_office",
        "family_office",
        "real_estate_investor",
        "real_estate_fund",
        "private_equity_real_estate",
        "hospitality_investor",
        "private_capital",
        "international_property_advisor",
        "other_relevant",
    }
    allowed_bor = {"strong", "moderate", "weak", "unclear"}
    allowed_italy = {"yes", "no", "unclear"}
    allowed_amalfi = {"strong", "moderate", "weak", "unclear"}
    allowed_lux = {"yes", "no", "unclear"}
    allowed_hosp = {"yes", "no", "unclear"}
    allowed_pri = {"A", "B", "C"}
    allowed_ver = {"verified", "partially_verified", "needs_review"}
    keys: set[tuple[str, str, str]] = set()
    for i, row in enumerate(rows, start=1):
        missing = [h for h in HEADERS if h not in ("country", "last_verified") and h not in row]
        if missing:
            raise SystemExit(f"Row {i} missing {missing}")
        if row["type"] not in allowed_type:
            raise SystemExit(f"Row {i} bad type {row['type']}")
        if row["buyer_origin_relevance"] not in allowed_bor:
            raise SystemExit(f"Row {i} bad buyer_origin_relevance")
        if row["italy_interest"] not in allowed_italy:
            raise SystemExit(f"Row {i} bad italy_interest")
        if row["amalfi_coast_relevance"] not in allowed_amalfi:
            raise SystemExit(f"Row {i} bad amalfi_coast_relevance")
        if row["luxury_real_estate"] not in allowed_lux:
            raise SystemExit(f"Row {i} bad luxury_real_estate")
        if row["hospitality_interest"] not in allowed_hosp:
            raise SystemExit(f"Row {i} bad hospitality_interest")
        if row["priority"] not in allowed_pri:
            raise SystemExit(f"Row {i} bad priority")
        if row["verification_status"] not in allowed_ver:
            raise SystemExit(f"Row {i} bad verification_status")
        score = int(row["fit_score"])
        if not 1 <= score <= 10:
            raise SystemExit(f"Row {i} bad fit_score")
        if row["priority"] == "A" and score < 8:
            raise SystemExit(f"Row {i} priority A requires fit_score 8–10")
        if row["priority"] == "B" and not (6 <= score <= 7):
            raise SystemExit(f"Row {i} priority B should be 6–7")
        if row["priority"] == "C" and not (1 <= score <= 5):
            raise SystemExit(f"Row {i} priority C should be 1–5")
        email = row["email"].strip()
        if email and ("@" not in email or "." not in email.split("@")[-1]):
            raise SystemExit(f"Row {i} invalid email: {email}")
        key = (
            row["company_name"].strip().lower(),
            row["website"].strip().lower(),
            row["contact_name"].strip().lower(),
        )
        if key in keys:
            raise SystemExit(f"Row {i} duplicate key {key}")
        keys.add(key)


def main() -> None:
    validate_rows(ROWS)
    out = Path("/workspace/data/real-estate-prospects/china.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for row in ROWS:
            full = {h: row.get(h, "") for h in HEADERS}
            full["country"] = COUNTRY
            full["last_verified"] = LAST_VERIFIED
            writer.writerow(full)
    print(f"Wrote {len(ROWS)} rows to {out}")


if __name__ == "__main__":
    main()
