#!/usr/bin/env python3
"""Generate the Russia buyer/capital-access prospect CSV from verified research notes."""

from __future__ import annotations

import csv
from pathlib import Path

HEADERS = [
    "country",
    "city",
    "company_name",
    "type",
    "contact_name",
    "contact_role",
    "email",
    "phone",
    "website",
    "linkedin_company",
    "linkedin_contact",
    "investment_focus",
    "geographic_focus",
    "buyer_origin_relevance",
    "italy_interest",
    "amalfi_coast_relevance",
    "estimated_ticket",
    "luxury_real_estate",
    "hospitality_interest",
    "fit_score",
    "priority",
    "verification_status",
    "source_1",
    "source_2",
    "notes",
    "last_verified",
]

LAST_VERIFIED = "2026-08-27"
COUNTRY = "Russia"

ROWS = [
    {
        "city": "Moscow",
        "company_name": "BARNES Moscow",
        "type": "luxury_agency",
        "contact_name": "Denis Perkovskiy",
        "contact_role": "Head of International Property Department",
        "email": "moscow@barn-estate.com",
        "phone": "+7 499 272-48-72",
        "website": "https://barnes-moscow.com",
        "linkedin_company": "https://www.linkedin.com/company/barnes-moscow",
        "linkedin_contact": "",
        "investment_focus": "UHNW lifestyle and trophy residential; international property; art, wine/vineyards and yachts",
        "geographic_focus": "Moscow and St Petersburg luxury stock plus overseas including Italy, France, Spain, Portugal, UAE, Turkey and Thailand; BARNES International network",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://barnes-moscow.com/team/",
        "source_2": "https://barnes-moscow.com/italiya/",
        "notes": "Official team page names Denis Perkovskiy as Head of International Property Department, with Igor Bocharov as Deputy Director and Mikhail Ilin-Diachkov as International Real Estate Consultant. Italy catalog on the Russia site lists 139 objects including Forte dei Marmi, Lake Como, Lake Garda and Costa Smeralda/Porto Cervo villas; first-party Italy copy explicitly discusses pricing on the Amalfi Coast. Contacts page publishes moscow@barn-estate.com, Petrovka 19 bldg 1, Moscow, plus a St Petersburg office at Paradaya 9 (also referred to as Sotsialisticheskaya 21 on the homepage) and a Moscow-region country office. Additional published phones: +7 495 106-87-98 (contacts), +7 495 182-50-79 and +7 495 783-00-00 (site footer). moscow@barnes-international.com also appears on some site pages; the contacts/Italy footer address moscow@barn-estate.com is used here. No personal email for Perkovskiy is published. Strongest Russia-office lifestyle/trophy match for a EUR 6-12m coastal villa; Amalfi is named in guidance rather than evidenced as a closed-transaction cluster. Approach the Moscow international desk, not BARNES Italy shops, for Russian buyer origination.",
    },
    {
        "city": "Moscow",
        "company_name": "Intermark Real Estate",
        "type": "luxury_agency",
        "contact_name": "Olga Katrich",
        "contact_role": "Director, International Projects Department (Intermark Investments)",
        "email": "info@intermark.ru",
        "phone": "+7 495 252 00 99",
        "website": "https://intermark.ru/en",
        "linkedin_company": "https://www.linkedin.com/company/intermark-realestate",
        "linkedin_contact": "https://www.linkedin.com/in/olga-katrich-a88959346",
        "investment_focus": "Prime Moscow residential plus overseas living, investment and European/Caribbean/US immigration-linked property for HNWI clients",
        "geographic_focus": "Moscow (formerly Savills Russia 2006-2022); official international buy list includes Italy, UK, France, Austria, Monaco, Switzerland, Spain, Germany, Turkey and Croatia",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://intermark.ru/en/company/our-managers/olga-katrich",
        "source_2": "https://intermark.ru/en/international-property/buy-italy",
        "notes": "Moscow prime agency since 1993; operated as Savills in Russia 2006-2022. Official Katrich page states personal knowledge of Italy, France and the Netherlands and publishes +7 495 252 00 99; no personal email is published. Official contacts pages publish info@intermark.ru and sales_web@intermark.ru; family-office/sales line +7 495 255 44 26 also appears in the site header. Italy is a live country desk. Related investment contact on the same managers roster: Ekaterina Orlova, Director of the International Investment Department, advising HNWI clients on Western Europe/US/Asia (same switchboard). Intermark Family Office page still names Julia Ovchinnikova, but her LinkedIn shows she left in Aug 2024 to found Blesk estate, so she is not used as the Intermark contact. No public Amalfi closing evidenced; public Italy inventory historically skews Como/Sardinia rather than Campania. Offices: Barykovsky per. 4 bldg 2 and Kropotkinsky per. 7 bldg 1.",
    },
    {
        "city": "Moscow",
        "company_name": "Kalinka Ecosystem",
        "type": "luxury_agency",
        "contact_name": "Ekaterina Rumyantseva",
        "contact_role": "Founder; Chairman of the Board of Directors",
        "email": "kalinka@kalinka-realty.ru",
        "phone": "+7 495 725-25-81",
        "website": "https://www.kalinka-realty.ru",
        "linkedin_company": "https://www.linkedin.com/company/kalinka-realty-llc",
        "linkedin_contact": "https://www.linkedin.com/in/ekaterina-rumyantseva-89a92682",
        "investment_focus": "UHNW and trophy residential, commercial and investment property; citizenship/residency support; yacht and lifestyle services",
        "geographic_focus": "Moscow HQ with offices/representation in UAE, Turkey, Thailand, Bali, UK (London office from Dec 2023, marketed at GBP 3m+) and Saudi Arabia; live Italy residential catalog",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.kalinka-realty.ru/zarubezh/italiya/",
        "source_2": "https://www.kalinka-realty.ru/contacts/",
        "notes": "Founded 1999. Official Italy page is a live residential catalog (about 138 objects when checked), with filters for elite villas, apartments and hotels. Contacts page: Moscow office at 1st Kazachy pereulok 7, BC House of German Economy; kalinka@kalinka-realty.ru (published as non-property weekday inbox); property line +7 958 762-96-00 (24/7); office +7 495 023-45-85; PR pr@kalinka-realty.ru. English site kalinka-realty.com. Do not confuse with Kalinka Immobiliare in Sanremo, an Italy-based Ligurian agency not evidenced as this Moscow origination node. Amalfi/Positano not verified in current villa geo filters (Italy coverage is stronger on Tuscany, lakes, Liguria, Forte dei Marmi, Capri in some taxonomies). Deputy GM International Alina Aleshina is named on company LinkedIn; founder remains the UHNW door. Personal email for Rumyantseva is not published.",
    },
    {
        "city": "Moscow",
        "company_name": "NF GROUP",
        "type": "international_property_advisor",
        "contact_name": "Anna Larina",
        "contact_role": "Director, International and Resort Real Estate Department",
        "email": "ms@nfgroup.ru",
        "phone": "+7 495 151-90-00",
        "website": "https://nf.group",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Overseas and resort residential brokerage, villas, commercial including hotels, and EU residence-by-investment advice for private and corporate clients",
        "geographic_focus": "Moscow HQ (Mercury Tower); offices in St Petersburg, Dubai, Istanbul, Cyprus and Bali; international department lists Italy among 70+ countries",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://nf.group/department-international",
        "source_2": "https://kf.expert/en/about",
        "notes": "Former Knight Frank Russia. Official international/resort department is led by Anna Larina and lists Italy in its country set. kf.expert about page publishes ms@nfgroup.ru next to Larina; general inbox nf@nfgroup.ru; Dubai sales@nfgroup.ae; SPb spb@nfgroup.ru. Larina expert page also lists property selection in Italy among other countries. CREDO awards for best luxury brokerage in Moscow. Published exclusive international examples on the department page are Spain, London, Cyprus, Turkey, UAE, Bali and Maldives rather than Amalfi, and the mix includes CBI/developer inventory. Buyer-rep into Russian UHNW, not principal capital. Telegram channel @annalarinanfgroup_rf is public; no verified personal LinkedIn used. Additional Moscow phone on nf.group: +7 495 021-70-17.",
    },
    {
        "city": "Dubai",
        "company_name": "Intermark Global",
        "type": "international_property_advisor",
        "contact_name": "Irina Mosheva",
        "contact_role": "Managing Partner, Intermark Investments",
        "email": "client@intermark.global",
        "phone": "+971 4 439 6368",
        "website": "https://intermark.global",
        "linkedin_company": "https://www.linkedin.com/company/intermark-global",
        "linkedin_contact": "https://www.linkedin.com/in/irina-mosheva-0ba53a14",
        "investment_focus": "Overseas residential for living, investment and immigration; Global Investment Department; European residence-permit routes including Italy",
        "geographic_focus": "Dubai HQ serving Russian-speaking clients; claimed offices in UK, Indonesia, China, Thailand and Turkey; partner network in 70 countries",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://intermark.global/contacts",
        "source_2": "https://events.intermark.global/partner-en",
        "notes": "Same Intermark heritage as the Moscow agency, listed separately because the Dubai/global arm is the practical door to Russian-origin capital that has already relocated (UAE/Turkey/Cyprus/UK). Official contacts page publishes client@intermark.global and +971 4 439 6368. Partner portal publishes invest@intermark.global and names Irina Mosheva among partners, Nina Reznichenko as CEO Intermark Global, Ekaterina Orlova as Director of International Investment, Olga Katrich as Director of Immigration Programs, and Elena Pinkhasik as Head of the EU Countries Direction; Italy residence-permit routes (representative office / property purchase) are listed. Mosheva is Managing Partner of Intermark Investments on intermark.ru. Public commentary (Izvestia, Jan 2025) discussed Russians increasing demand for European property. Product mix is weighted to investment/immigration tickets, not Amalfi trophies. Treat as one introducer group with Intermark Real Estate, not two unrelated capital sources.",
    },
    {
        "city": "Moscow",
        "company_name": "UFG Wealth Management",
        "type": "family_office",
        "contact_name": "Andrey Rozov",
        "contact_role": "Head of Real Estate",
        "email": "info@ufgwm.com",
        "phone": "+7 495 230 09 04",
        "website": "https://www.ufgwm.com",
        "linkedin_company": "https://www.linkedin.com/company/ufg-w-m",
        "linkedin_contact": "https://www.linkedin.com/in/andrey-rozov-05411182",
        "investment_focus": "Independent multi-family office for Russian UHNW clients; commercial real-estate search, purchase, sale and management in Europe",
        "geographic_focus": "Moscow office (Tsvetnoy Blvd 2); legal HQ listed as Umm Al Quwain; also Cyprus, UK and the Netherlands; published European commercial case in Luxembourg",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.ufgwm.com/commercial-real-estate",
        "source_2": "https://www.ufgwm.com/about-ufg",
        "notes": "Best evidenced Russian-origin multi-family office with a dedicated international real-estate desk. Official commercial-RE page states clients invested approximately EUR 700 million in European commercial property over 7 years and describes off-market search, bank negotiation and asset management; published case is a Class A Luxembourg office. Official site publishes info@ufgwm.com and a UN/EU/OFAC/OFSI compliance statement. Phone is from the company LinkedIn, not the website. Sergey Belyaev is Managing Director; Artyom Korsovskiy is listed as Investment Director, Real Estate on company LinkedIn. Not found as an EU/US/UK designated entity in this review. Caveat: published product is European commercial real estate, not Italian trophy residential. Fit is as a Russian UHNW introducer/allocator into European property, not as a proven Amalfi buyer. Distinct from an unrelated Andrey Rozov who appears as CFO at Yango.",
    },
    {
        "city": "Amsterdam",
        "company_name": "Stanley Hospitality Group",
        "type": "hospitality_investor",
        "contact_name": "Stan Zingel",
        "contact_role": "Founder and Managing Partner",
        "email": "info@stanley-hotels.com",
        "phone": "+31 6 244 71242",
        "website": "https://stanley-hotels.com",
        "linkedin_company": "",
        "linkedin_contact": "https://www.linkedin.com/in/stan-zingel-294537150",
        "investment_focus": "European luxury hotels, boutique city hotels and eco-resorts; family-office and institutional real-estate transactions",
        "geographic_focus": "EU operating base (Amsterdam); Italy expansion (Florence Palazzo Morrocchi; stated Tuscany, Milan, Rome and Puglia pipeline) plus Portugal",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://stanley-hotels.com/about-us/people/",
        "source_2": "https://wwd.com/eye/lifestyle/florence-luxury-hotel-boom-2026-high-end-tourism-growth-1239003992/",
        "notes": "Russian-origin hospitality principal (historically Gordon Rock in Moscow) now running Stanley Hospitality Group from Amsterdam. Official people page: Stan Zingel, Founder & Managing Partner, cites more than EUR 1bn of family-office/institutional transactions over 10 years and private development experience including Italy; co-founder Boris Egorov. Imprint: Stanley HGR BV, Herengracht 269, Amsterdam; info@stanley-hotels.com; tel +31 6 244 71242; managing director Carole Kabantsov. WWD reports Palazzo Morrocchi, Via Cavour 21, Florence (31 rooms + 10 suites) opening after a multi-year restoration, with Zingel quoted as founder and managing partner. Travel industry coverage describes a wider Italy/Portugal eco-resort push (Tuscany, Puglia, Algarve). Relevant if the Amalfi asset is positioned as boutique hospitality/leisure rather than a pure private villa. A 41-key city hotel is not proof of a EUR 6-12m residential ticket. Gordon Rock moscow site looks stale and is not used as a separate row.",
    },
    {
        "city": "Camaiore",
        "company_name": "Vers Italia",
        "type": "hospitality_investor",
        "contact_name": "Vitaly Bezrodnykh",
        "contact_role": "Beneficial owner (press); Vers Italia administrator of record is Marco D'Ascoli",
        "email": "",
        "phone": "",
        "website": "",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Italian coastal hotels and related tourism assets in Versilia; Tuscan wine estate",
        "geographic_focus": "Tuscany / Versilia (Camaiore, Forte dei Marmi, Lido di Camaiore, Viareggio, Marina di Massa); holding via Luxembourg Vers Properties",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "about EUR 5.5 million evidenced for Tenuta del Buonamico (2026); hotel-portfolio tickets unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.iltirreno.it/lucca/cronaca/2026/04/30/news/lucca-la-mani-russe-sulla-tenuta-da-sogno-chi-e-il-nuovo-proprietario-1.100863258",
        "source_2": "",
        "notes": "Il Tirreno (30 Apr 2026) reports Vers Italia (Camaiore) acquired Tenuta del Buonamico for about EUR 5.5 million; 100% of Vers Italia is held by Luxembourg Vers Properties; press identifies Russian-origin financier Vitaly Bezrodnykh as the principal, with Marco D'Ascoli as sole administrator. Same reporting attributes a Versilia hotel/beach-club basket (Hotel Tirreno and Hotel Belvedere in Forte dei Marmi, Alba sul Mare and Valdinievole in Lido di Camaiore, a Viareggio hotel, a Poveromo villa). Ticket size and coastal-hospitality use are relevant; Amalfi is not evidenced. No official company website, email or phone was found; Fulgur Ventures (contact@fulgur.ventures) is Bezrodnykh's bitcoin-infrastructure VC and is not used as a real-estate inbox. Do not treat this as a brokerage introducer. Independent KYC required before any approach.",
    },
    {
        "city": "Moscow",
        "company_name": "Russia Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Ksenia Sorokina",
        "contact_role": "Head of Sales, International Department",
        "email": "ksorokina@sothebys-realty.ru",
        "phone": "+7 495 215-50-05",
        "website": "https://www.sothebys-realty.ru",
        "linkedin_company": "https://www.linkedin.com/company/russia-sothebys-international-realty",
        "linkedin_contact": "https://www.linkedin.com/in/ksenia-sorokina-21b721a5",
        "investment_focus": "Overseas luxury residential and hotel-project marketing plus residence/citizenship-by-investment advisory for Russian-speaking clients",
        "geographic_focus": "Moscow office; Italy is an active content/product line (webinars, elective-residency copy); also Europe, US, Caribbean and other CBI markets",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://france.sothebys-realty.ru/page36506413.html",
        "source_2": "https://events.sothebys-realty.ru/web-italy-20062024",
        "notes": "Firm Italy residency page publishes Ksenia Sorokina as Head of Sales, International Department, office +7 495 215-50-05, mobile +7 925 128-31-01, ksorokina@sothebys-realty.ru. June 2024 webinar covered premium real estate in Italy / how RF citizens buy in Italy. Related consultant Elena Bashkatova (investment migration) is published on events.sothebys-realty.ru with ebashkatova@sothebys-realty.ru and +7 903 709-5493; general inboxes info@sothebys-realty.ru and request@sothebys-realty.ru also appear. Do not confuse with Italy Sotheby's International Realty (Milan), which is an Italian affiliate. Caveat: Sotheby's auction house liquidated its Russian legal entity (Forbes 2024); current official affiliation of this Moscow boutique with the global Sotheby's International Realty network was not independently confirmed in this pass. Treat as a Moscow international advisor with documented Italy programming, not as guaranteed access to the global SIR referral engine. No Amalfi closing evidenced. CBI weighting reduces fit versus BARNES/Intermark/Kalinka.",
    },
    {
        "city": "Moscow",
        "company_name": "Blesk estate",
        "type": "private_office",
        "contact_name": "Julia Ovchinnikova",
        "contact_role": "Founder",
        "email": "info@bleskestate.ru",
        "phone": "+7 996 710 9390",
        "website": "https://bleskestate.ru",
        "linkedin_company": "https://www.linkedin.com/company/blesk-estate",
        "linkedin_contact": "https://www.linkedin.com/in/julia-ovchinnikova-a9a4665",
        "investment_focus": "Bespoke international property advisory for private clients; founder describes the role as a real-estate family office across diversified cross-border portfolios",
        "geographic_focus": "Moscow plus partners worldwide; public portfolio includes Moscow prime, Marbella and UAE; LinkedIn states acquisitions/sales in Europe, the UAE and Moscow",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://bleskestate.ru",
        "source_2": "https://intermark.ru/en/company/our-managers/yuliya-ovchinnikova",
        "notes": "Former Director of Intermark Private Office (Aug 2022-Aug 2024) and previously Director of International Property at Savills Russia. Official site publishes +7 996 710 9390 and info@bleskestate.ru. Public listings are mostly Moscow luxury plus a Marbella villa marketed at about RUB 1.27bn and UAE branded residences; Italy is not in the public catalog. LinkedIn (May 2026) states she supports acquisitions and sales in Europe, the UAE and Moscow and structures cross-border transactions and residency programmes. Small one-person boutique; relevant as a UHNW introducer with a genuine Intermark/Savills Russia private-office track record, not as an Amalfi specialist.",
    },
    {
        "city": "London",
        "company_name": "VIY Management",
        "type": "private_equity_real_estate",
        "contact_name": "Andrey Yakunin",
        "contact_role": "Co-founder",
        "email": "",
        "phone": "",
        "website": "https://www.andreyyakunin.com/about",
        "linkedin_company": "https://www.linkedin.com/company/viy-management-llp",
        "linkedin_contact": "",
        "investment_focus": "European branded hospitality and mixed-use resorts",
        "geographic_focus": "Europe; documented Italian hospitality estate in Umbria (Antognolla / Six Senses project) sold in 2025",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.andreyyakunin.com/about",
        "source_2": "https://www.perugiatomorrow.it/2025/10/22/passaggio-di-proprieta-di-antognolla-mohamed-alabbar-acquista-il-complesso-da-andrey-yakunin/",
        "notes": "Russian-origin hospitality PE principal with a documented Italian trophy-hospitality history: Antognolla in Umbria was sold in Oct 2025 to Mohamed Alabbar / Eagle Hills (press estimates of the consideration vary widely). Official personal site and LinkedIn company page confirm the hospitality platform. Historic viym.co.uk contact details were not re-verified on a live first-party page in this pass, so email and phone are left empty. Not found on EU/US/UK designation lists in this review (OpenSanctions Q19975571); father Vladimir Yakunin is designated. Yakunin is a PEP/close associate; independent legal screening is required before any approach. Current acquisition appetite after the 2025 sale is unknown. Ticket history is hospitality-estate scale, not a demonstrated EUR 6-12m residential bid. Amalfi is not evidenced.",
    },
    {
        "city": "Moscow",
        "company_name": "Ashtons International Realty",
        "type": "luxury_agency",
        "contact_name": "Roman Kuzmin",
        "contact_role": "Commercial Director",
        "email": "ashtons@ashtons.ru",
        "phone": "+7 495 120-99-00",
        "website": "https://www.ashtons.ru",
        "linkedin_company": "https://www.linkedin.com/company/ashtons-international-realty",
        "linkedin_contact": "",
        "investment_focus": "Moscow and St Petersburg prime residential, country and commercial brokerage; site also lists overseas sale and letting",
        "geographic_focus": "Moscow (Presnenskaya nab. 10, block B) and St Petersburg; homepage claims a partner network in Russia, Europe, Asia and the Middle East; evidenced overseas partnership is UAE (BNW Developments)",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "partially_verified",
        "source_1": "https://www.ashtons.ru/ru/contacts/",
        "source_2": "https://www.ashtons.ru/en/blog/most-mezhdu-moskvoj-i-dubaem-ashtons-international-realty-i-bnw-developments-zaklyuchili-strategicheskoe-partnerstvo.htm",
        "notes": "Long-standing Moscow/SPb luxury consultancy with a genuine UHNW domestic rolodex and an official overseas section. Contacts page publishes ashtons@ashtons.ru and +7 495 120-99-00. Roman Kuzmin is named as Commercial Director on the official BNW Developments partnership announcement (UAE project sales into Russia). Homepage language includes Europe, but the only documented recent international mandate found is Dubai developer representation. No Italy desk or Amalfi evidence. Included conservatively as a possible introducer into Moscow UHNW clients who already buy overseas, not as an Italy specialist. Andrey Posakov is named as general director on third-party directories; that title was not taken from an Ashtons people page in this pass.",
    },
]


def main() -> None:
    out = Path("/workspace/data/real-estate-prospects/russia.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for row in ROWS:
            full = {h: row.get(h, "") for h in HEADERS}
            full["country"] = COUNTRY
            full["last_verified"] = LAST_VERIFIED
            writer.writerow(full)
    print(f"Wrote {len(ROWS)} rows to {out}")


if __name__ == "__main__":
    main()
