#!/usr/bin/env python3
"""Generate the UAE buyer-origin prospect CSV from verified research notes.

Buyer-origin test for every row:
Can this organisation or person realistically bring, represent, introduce,
advise, or be a buyer/investor FROM the UAE for a €6M–€12M Amalfi Coast
luxury property?
"""

from __future__ import annotations

import csv
import re
from pathlib import Path

HEADERS = [
    "country",
    "city",
    "company_name",
    "type",
    "contact_name",
    "contact_role",
    "email",
    "phone",
    "website",
    "linkedin_company",
    "linkedin_contact",
    "investment_focus",
    "geographic_focus",
    "buyer_origin_relevance",
    "italy_interest",
    "amalfi_coast_relevance",
    "estimated_ticket",
    "luxury_real_estate",
    "hospitality_interest",
    "fit_score",
    "priority",
    "verification_status",
    "source_1",
    "source_2",
    "notes",
    "last_verified",
]

ALLOWED_TYPE = {
    "luxury_agency",
    "private_office",
    "family_office",
    "real_estate_investor",
    "real_estate_fund",
    "private_equity_real_estate",
    "hospitality_investor",
    "private_capital",
    "international_property_advisor",
    "other_relevant",
}
ALLOWED_BUYER_ORIGIN = {"strong", "moderate", "weak", "unclear"}
ALLOWED_ITALY = {"yes", "no", "unclear"}
ALLOWED_AMALFI = {"strong", "moderate", "weak", "unclear"}
ALLOWED_LUXURY = {"yes", "no", "unclear"}
ALLOWED_HOSP = {"yes", "no", "unclear"}
ALLOWED_VERIF = {"verified", "partially_verified", "needs_review"}
ALLOWED_PRIORITY = {"A", "B", "C"}

LAST_VERIFIED = "2026-08-27"
COUNTRY = "United Arab Emirates"

EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
URL_RE = re.compile(r"^https://", re.I)

# Fit scoring used in notes:
# +3 strong UAE UHNW/private/institutional capital access
# +2 demonstrated international luxury real-estate activity
# +2 demonstrated Italy/Europe relevance
# +1 luxury/trophy/coastal asset relevance
# +1 hospitality/leisure relevance
# +1 €6M–€12M appears compatible

ROWS = [
    {
        "city": "Dubai",
        "company_name": "Knight Frank UAE",
        "type": "luxury_agency",
        "contact_name": "Nicholas Spencer",
        "contact_role": "Partner - Head of Prime Residential; Private Capital and Family Enterprises MENA",
        "email": "nicholas.spencer@me.knightfrank.com",
        "phone": "+971 54 584 4365",
        "website": "https://www.knightfrank.ae",
        "linkedin_company": "https://www.linkedin.com/company/knightfrankmena",
        "linkedin_contact": "https://www.linkedin.com/in/nicholas-spencer-846466b8",
        "investment_focus": "Prime residential; Private Capital and Family Enterprises advisory; International Project Sales sourcing homes worldwide for MENA clients",
        "geographic_focus": "UAE/GCC private clients buying into the UK, Europe and other prime global markets",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.knightfrank.ae/residential/international-project-sales",
        "source_2": "https://www.knightfrank.ae/site-assets/pdf/private-capital-brochure-mena.pdf",
        "notes": "BUYER-ORIGIN: International Project Sales page states the Dubai team facilitates interest in the UK, Europe and other prime global markets for investors and individual buyers, including bespoke property search. Official Private Capital brochure names Nicholas Spencer as Partner, Private Capital and Family Enterprises MENA, and publishes nicholas.spencer@me.knightfrank.com and +971 54 584 4365. People page confirms he advises family offices on luxury residential in the UK and GCC and works with private banks. Italy is not named specifically. Score 8: +3 UAE UHNW/FO access, +2 international luxury RE, +2 Europe mandate, +1 trophy residential. Direct email taken from Knight Frank's own MENA PDF, not inferred.",
    },
    {
        "city": "Dubai",
        "company_name": "Savills Middle East",
        "type": "luxury_agency",
        "contact_name": "Andrew Cummings",
        "contact_role": "Head of Residential Agency, Middle East",
        "email": "international@savills.me",
        "phone": "+971 4 365 7700",
        "website": "https://www.savills.me",
        "linkedin_company": "https://www.linkedin.com/company/savillsmiddleeast",
        "linkedin_contact": "https://www.linkedin.com/in/ancummings",
        "investment_focus": "Prime and branded residential agency plus cross-border private-client sales via the Savills international network",
        "geographic_focus": "UAE and wider Middle East clients, with published London/international residential distribution",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.savills.co.uk/insight-and-opinion/savills-news/382799/savills-presents-london-and-dubai-s-most-exclusive-residences-at-cityscape-global-riyadh",
        "source_2": "https://dubai.savills.ae/forms/contact-office.aspx?id=241187-0",
        "notes": "BUYER-ORIGIN: Official Savills release publishes international@savills.me for Middle East international residential enquiries. Cummings' public profile states he provides an international service selling properties in locations such as London and Oman alongside UAE prime stock, evidencing a UAE desk that works outbound as well as inbound. Italy not specifically evidenced. Personal email not used. Score 8: +3 UAE UHNW access, +2 international luxury RE, +2 Europe/London, +1 trophy.",
    },
    {
        "city": "Dubai",
        "company_name": "Christie's International Real Estate Dubai",
        "type": "luxury_agency",
        "contact_name": "Jackie Johns",
        "contact_role": "Managing Partner",
        "email": "info@christiesrealestatedubai.com",
        "phone": "+971 4 585 9074",
        "website": "https://www.christiesrealestatedubai.com",
        "linkedin_company": "https://www.linkedin.com/company/ciredxb",
        "linkedin_contact": "https://www.linkedin.com/in/jackie-johns-75048122",
        "investment_focus": "UHNW trophy residential; Private Office off-market advisory; global luxury referrals across the Christie's International Real Estate network including European affiliates",
        "geographic_focus": "Dubai, Abu Dhabi and Ras Al Khaimah desks serving local UHNW clients with access to 50+ countries",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.christiesrealestatedubai.com/the-journal/new-office-opening-in-media-city/",
        "source_2": "https://www.christiesrealestatedubai.com/enquiries/",
        "notes": "BUYER-ORIGIN: Dubai Private Office is the relevant access point to UAE UHNW buyers, even though Christie's also has Italian affiliates; do not redirect to Italy. Official July 2025 announcement names Jackie Johns and Dinesh Chhatwani as Managing Partners and publishes +971 4 585 9074 and info@christiesrealestatedubai.com. Company describes a Private Office for UHNW trophy assets and rare real estate worldwide. Italy not named on the Dubai site. Score 8: +3 UAE UHNW, +2 international luxury network, +2 Europe via network, +1 trophy.",
    },
    {
        "city": "Dubai",
        "company_name": "Dubai Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Chris Whitehead",
        "contact_role": "Managing Partner",
        "email": "",
        "phone": "+971 4 455 0896",
        "website": "https://sothebysrealty.ae",
        "linkedin_company": "https://www.linkedin.com/company/dubaisothebysinternationalrealty",
        "linkedin_contact": "https://www.linkedin.com/in/chwhitehead",
        "investment_focus": "Super-prime and blue-chip residential; private-client advisory; international Sotheby's International Realty referrals",
        "geographic_focus": "Dubai flagship serving regional UHNW, with group leadership also covering KSA and UK super-prime",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "partially_verified",
        "source_1": "https://sothebysrealty.ae/management/chris-whitehead/",
        "source_2": "https://sothebysrealty.ae/contact-us/",
        "notes": "BUYER-ORIGIN: Dubai flagship Managing Partner is positioned in regional and international private-client markets; Sotheby's International Realty network includes Italian affiliates, but the UAE office is the buyer-origin channel. Contact page publishes +971 4 455 0896; only email on that page is pr@sothebysrealty.ae (press), so sales email is empty. Score 8: +3 UAE UHNW, +2 international luxury network, +2 UK/international super-prime, +1 trophy. Italy not specifically evidenced from the Dubai desk.",
    },
    {
        "city": "Abu Dhabi",
        "company_name": "Abu Dhabi Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Emmanuel Aymes",
        "contact_role": "Private Client Real Estate Advisor",
        "email": "customercare@abudhabi-sothebysrealty.ae",
        "phone": "+971 4 455 0860",
        "website": "https://abudhabi-sothebysrealty.ae",
        "linkedin_company": "https://www.linkedin.com/company/abudhabi-sothebys-international-realty",
        "linkedin_contact": "https://www.linkedin.com/in/emmanuel-aymes-263b76112",
        "investment_focus": "Luxury residential sales and international Sotheby's referrals for Abu Dhabi private clients",
        "geographic_focus": "Abu Dhabi UHNW families with claimed cross-border prime markets including London and France",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://abudhabi-sothebysrealty.ae/en/contact-us",
        "source_2": "https://www.linkedin.com/company/abudhabi-sothebys-international-realty",
        "notes": "BUYER-ORIGIN: Separate affiliate from the Dubai Sotheby's office; relevant only as access to Abu Dhabi private clients who buy internationally. Official contact page: Office 610, Dar Al Salam Tower, Corniche; customercare@abudhabi-sothebysrealty.ae; +971 4 455 0860. Aymes' public LinkedIn describes UHNW families and cross-border prime including London and France. Score capped at 7 because Italy is not evidenced and the named contact is an advisor rather than Managing Partner. Distinct from Dubai Sotheby's row.",
    },
    {
        "city": "Dubai",
        "company_name": "Engel & Völkers Dubai",
        "type": "private_office",
        "contact_name": "Daniel Abdul Hadi",
        "contact_role": "CEO Middle East",
        "email": "dubai@engelvoelkers.com",
        "phone": "+971 4 422 3500",
        "website": "https://www.engelvoelkers.com/ae/en/shops/dubai-private-office",
        "linkedin_company": "https://www.linkedin.com/company/engel&voelkers-dubai",
        "linkedin_contact": "https://www.linkedin.com/in/danielhadi",
        "investment_focus": "Private Office off-market luxury advisory in Dubai and worldwide via the Engel & Völkers global network, including Italian shops",
        "geographic_focus": "UAE Private Office connected to Engel & Völkers shops across Europe including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.engelvoelkers.com/ae/en/imprint",
        "source_2": "https://www.engelvoelkers.com/ae/en/shops/dubai-private-office",
        "notes": "BUYER-ORIGIN: Official Private Office page states exclusive off-market luxury advisory in Dubai and worldwide via the global network; Italy interest is via the brand's Italian shop network, not a published Dubai-to-Amalfi mandate. Imprint: Engel and Voelkers Real Estate LLC, Al Khail Plaza Floor 7; CEO Middle East Daniel Abdul Hadi; dubai@engelvoelkers.com; +971 4 422 3500. Company posts show Private Office advisors travelling to European E&V offices. Amalfi relevance is moderate (Italian coastal shops exist in the network). Score 8.",
    },
    {
        "city": "Dubai",
        "company_name": "BARNES Dubai",
        "type": "private_office",
        "contact_name": "Saber Zeroual",
        "contact_role": "Director of Private Client Office",
        "email": "",
        "phone": "+971 4 449 1087",
        "website": "https://www.barnes-international.com/en/contact/united-arab-emirates/barnes-dubai.html",
        "linkedin_company": "https://www.linkedin.com/company/barnes-dubai",
        "linkedin_contact": "https://www.linkedin.com/in/saber-zeroual-98b91b103",
        "investment_focus": "Ultra-luxury residential and Private Client Office advisory; art-de-vivre assets through the BARNES network including Italy",
        "geographic_focus": "Dubai as Middle East HQ, with BARNES offices across France, Italy and other European luxury destinations",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "partially_verified",
        "source_1": "https://www.barnes-international.com/en/contact/united-arab-emirates/barnes-dubai.html",
        "source_2": "https://www.linkedin.com/in/saber-zeroual-98b91b103",
        "notes": "BUYER-ORIGIN: Keep the Dubai Private Client Office, do not redirect to BARNES Italy. Official agency page: Emaar Square, Building 4, Office 703, Downtown Dubai. Company LinkedIn publishes +971 4 449 1087. Saber Zeroual's public LinkedIn lists current role as Director of Private Client Office serving HNW/UHNW and family offices (his written mandate is Dubai/Abu Dhabi luxury; Italy access is via the BARNES European network). Media email marketing.dubai@barnes-international.com is press-only so sales email is empty. Score 8: +3 UAE UHNW, +2 international luxury, +2 Italy offices, +1 trophy.",
    },
    {
        "city": "Dubai",
        "company_name": "John Taylor Dubai",
        "type": "luxury_agency",
        "contact_name": "Andrew Cleator",
        "contact_role": "Managing Director, Middle East",
        "email": "dubai@john-taylor.com",
        "phone": "+971 4 451 6543",
        "website": "https://john-taylor.ae",
        "linkedin_company": "https://www.linkedin.com/company/john-taylor-dubai-uae",
        "linkedin_contact": "https://www.linkedin.com/in/andrew-cleator-1059a33",
        "investment_focus": "Prime and super-prime residential sales for international UHNW clients; Riviera and Italian luxury-agency heritage",
        "geographic_focus": "Dubai desk connected to John Taylor offices in Monaco, the French Riviera, Milan and other European luxury markets",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://john-taylor.ae/en/contact",
        "source_2": "https://www.john-taylor.com/luxury-real-estate-agency/dubai/",
        "notes": "BUYER-ORIGIN: Highest-confidence UAE luxury desk for an Amalfi trophy home because the Dubai UHNW team sits inside a Riviera/Italian agency group (Milan publicly listed) rather than a Dubai-only broker. Official contact: Office 1607, Sidra Tower, Sheikh Zayed Road; +971 4 451 6543; dubai@john-taylor.com. Company LinkedIn announced Andrew Cleator as Managing Director, Middle East. Amalfi relevance is moderate (Italian/Riviera coastal trophy DNA, not a published Amalfi listing desk). Score 9: +3 UAE UHNW, +2 international luxury, +2 Italy/Riviera, +1 trophy, +1 ticket compatibility.",
    },
    {
        "city": "Dubai",
        "company_name": "Fine & Country Dubai Invest",
        "type": "luxury_agency",
        "contact_name": "Simon Pitkin",
        "contact_role": "CEO",
        "email": "dubai.invest@fineandcountry.com",
        "phone": "+971 55 114 8943",
        "website": "https://www.fineandcountry.ae/dubai-invest-estate-agents",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Premium and investment residential; international Fine & Country referrals including Italy",
        "geographic_focus": "Dubai office inside a network that publicly lists Italy among country sites",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.fineandcountry.ae/dubai-invest-estate-agents/contact",
        "source_2": "https://www.fineandcountry.ae/legal-notice-impressum",
        "notes": "BUYER-ORIGIN: Downgraded from prior score 8. Official contact lists Simon Pitkin as CEO; dubai.invest@fineandcountry.com; sales +971 55 114 8943. Fine & Country's UAE site includes Italy in its country network, which supports a referral path, but the Dubai Invest office's published mandate is Dubai investment stock rather than a documented outbound Italian search desk. Roman Realty L.L.C. trading as Fine & Country Dubai Invest. Score 7: +3 UAE clients, +2 network luxury, +2 Italy network, no extra trophy/coastal evidence.",
    },
    {
        "city": "Dubai",
        "company_name": "Nest Seekers International",
        "type": "luxury_agency",
        "contact_name": "Djawad Nawrozzadeh",
        "contact_role": "Managing Director - UAE",
        "email": "djawad@nestseekers.com",
        "phone": "+971 4 284 6366",
        "website": "https://www.nestseekers.com",
        "linkedin_company": "https://www.linkedin.com/company/nest-seekers-international",
        "linkedin_contact": "https://www.linkedin.com/in/djawad-nawrozzadeh-418573150",
        "investment_focus": "Ultra-luxury residential sales and international referral network including published Italy coverage",
        "geographic_focus": "Dubai office of a global Nest Seekers platform that lists Italy among international offices",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.nestseekers.com/Offices/nest-seekers-dubai",
        "source_2": "https://www.nestseekers.com/agent/djawad-nawrozzadeh/",
        "notes": "BUYER-ORIGIN: Dubai Managing Director is the UAE-buyer channel; do not treat the Italian Nest Seekers presence as the prospect. Official Dubai office: Office 07, Duja Tower, Trade Centre 1; +971 4 284 6366. Official listing pages publish djawad@nestseekers.com. Distinct from local brokers using nestseekersdubai.com. Score 8.",
    },
    {
        "city": "Dubai",
        "company_name": "Smeralda Emirates Estate",
        "type": "international_property_advisor",
        "contact_name": "Alessandra Lambroni",
        "contact_role": "Founder",
        "email": "",
        "phone": "+971 56 301 9813",
        "website": "https://www.smeraldaemirates.com/en/",
        "linkedin_company": "https://www.linkedin.com/company/smeraldaemirates",
        "linkedin_contact": "https://www.linkedin.com/in/alessandralambroni",
        "investment_focus": "Luxury residential brokerage connecting Dubai and Costa Smeralda / Porto Cervo; villas and coastal resorts",
        "geographic_focus": "Dubai (Business Bay, RERA licence 2111614) and Porto Cervo, Sardinia",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "partially_verified",
        "source_1": "https://www.smeraldaemirates.com/en/",
        "source_2": "https://www.smeraldaemirates.com/en/about-us/",
        "notes": "BUYER-ORIGIN: One of the few publicly evidenced UAE-Italy trophy-coast bridges. Official site confirms dual offices and positions the firm as moving demanding clients between Dubai and Porto Cervo. Founder Dr. Alessandra Lambroni named on the about page. No public email; WhatsApp +971 56 301 9813 (Dubai) and +39 349 8307519 (Italy). Boutique scale; also offers UAE company-formation services. Amalfi relevance is moderate: Italian luxury-coastal mandate (Sardinia, not Campania). Score 8.",
    },
    {
        "city": "Dubai",
        "company_name": "Grandi Private Office",
        "type": "international_property_advisor",
        "contact_name": "Simone Grandi",
        "contact_role": "Founder and Managing Director",
        "email": "",
        "phone": "",
        "website": "https://www.grandiprivateoffice.com/",
        "linkedin_company": "https://www.linkedin.com/company/grandi-private-office",
        "linkedin_contact": "https://www.linkedin.com/in/simonegrandi1",
        "investment_focus": "Independent super-prime buying advisor and portfolio manager for HNWI and family offices",
        "geographic_focus": "Offices in London and Dubai; sourcing across London, Italy, Dubai, Abu Dhabi, Saudi Arabia and the wider GCC",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "partially_verified",
        "source_1": "https://www.grandiprivateoffice.com/",
        "source_2": "https://www.linkedin.com/in/simonegrandi1",
        "notes": "BUYER-ORIGIN: Official site states operations in London and Dubai and specialises in sourcing exceptional properties for clients across London, Italy, Dubai, Abu Dhabi, Saudi Arabia and the GCC, acting exclusively for the purchaser. Founder Simone Grandi is Italian and publicly listed as director of GRANDI PRIVATE OFFICE LIMITED (UK company 14934642). LinkedIn places the firm in London with UAE presence; Dubai is recorded as the UAE operating city because that is the GCC buyer-origin desk. No public email or phone on the homepage (contact form only), so those fields are empty. Score 9: +3 GCC/UAE buyer representation, +2 international luxury, +2 Italy named, +1 trophy, +1 ticket compatibility.",
    },
    {
        "city": "Dubai",
        "company_name": "Origin Private Office",
        "type": "private_office",
        "contact_name": "Georgina Atkinson",
        "contact_role": "Managing Partner",
        "email": "",
        "phone": "",
        "website": "https://www.originpo.com",
        "linkedin_company": "https://www.linkedin.com/company/originpo",
        "linkedin_contact": "https://www.linkedin.com/in/georginaatkinson",
        "investment_focus": "Relationship-led ultra-prime private office: cross-border acquisitions, sales and lifestyle execution for globally mobile UHNW clients",
        "geographic_focus": "Dubai and Abu Dhabi offices plus Singapore and New York; network covering London and other luxury markets",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "partially_verified",
        "source_1": "https://www.originpo.com/",
        "source_2": "https://www.originpo.com/about",
        "notes": "BUYER-ORIGIN: Contact updated from Melbourne-based Ross Savas to Dubai-based Managing Partner Georgina Atkinson (House of Origin Real Estate L.L.C., Dubai BRN 50604 on Property Finder). Official about page names Atkinson among leadership. Dubai office: The One Tower, Sheikh Zayed Road. No public email or phone on official pages, so those fields remain empty; aggregator emails were not used. Italy not named. Score 8 for UAE UHNW cross-border execution, not because the brand is new.",
    },
    {
        "city": "Dubai",
        "company_name": "Allsopp & Allsopp Private Office",
        "type": "private_office",
        "contact_name": "Charlie King",
        "contact_role": "Partner, Private Office",
        "email": "charlie@allsoppandallsopp.com",
        "phone": "+971 4 429 4444",
        "website": "https://www.allsoppandallsopp.com/private-office",
        "linkedin_company": "https://www.linkedin.com/company/allsopp-%26-allsopp",
        "linkedin_contact": "",
        "investment_focus": "UHNW and family-office advisory; off-market residential at AED 25 million and above; claimed global as well as local consulting",
        "geographic_focus": "Dubai trophy residential; Private Office page says advisors consult clients globally and locally",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "AED 25M+ private-office threshold (about €6M+)",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.allsoppandallsopp.com/private-office",
        "source_2": "https://www.allsoppandallsopp.com/dubai/about-us/our-agents/charlie-king",
        "notes": "BUYER-ORIGIN: Downgraded. Parent is a large Dubai brokerage; this row is the Private Office only. Official page specialises in AED 25M+ Dubai stock and says the team consults on matters globally and locally, but evidenced inventory and press are Dubai trophy homes, not Italian sourcing. Charlie King is named Partner on the official agent page with charlie@allsoppandallsopp.com. Ticket threshold is compatible with €6M–€12M. Score 6: +3 UAE UHNW access, +1 trophy, +1 ticket; international luxury and Italy/Europe not independently evidenced.",
    },
    {
        "city": "Dubai",
        "company_name": "Morgan's Private Office",
        "type": "private_office",
        "contact_name": "Mansour Daou",
        "contact_role": "Private Client Advisor",
        "email": "info@morgansrealty.com",
        "phone": "+971 4 241 8886",
        "website": "https://www.morgansrealty.com/private_offices",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "UHNW and family-office advisory; tailored searches and acquisitions for investment or second-home requirements; branded-residence research",
        "geographic_focus": "Middle East Private Office in Dubai claiming global deal flow; published featured listings are Dubai trophy assets",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "featured private listings from about AED 25M to AED 250M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.morgansrealty.com/private_offices",
        "source_2": "https://www.morgansrealty.com/contact",
        "notes": "BUYER-ORIGIN: Official Private Office page says the Middle East desk transacts for UHNW clients and family offices globally and will search/acquire a second home. Contact page: Concord Tower, Media City; info@morgansrealty.com; +971 4 241 8886. Named Private Client Advisor Mansour Daou. Site navigation includes International Properties, but featured stock is Dubai ultra-prime, so outbound Italy is not evidenced. Score 6.",
    },
    {
        "city": "Dubai",
        "company_name": "Driven Properties",
        "type": "luxury_agency",
        "contact_name": "Abdullah Al Ajaji",
        "contact_role": "Founder and CEO",
        "email": "info@drivenproperties.com",
        "phone": "+971 4 429 7040",
        "website": "https://www.drivenproperties.com",
        "linkedin_company": "https://www.linkedin.com/company/driven-properties-real-estate",
        "linkedin_contact": "",
        "investment_focus": "Luxury residential brokerage; Forbes Global Properties exclusive UAE member; European luxury listings via Spain office",
        "geographic_focus": "Dubai HQ with published luxury offices in Spain (Madrid / Costa del Sol / Balearics)",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.drivenproperties.es/en",
        "source_2": "https://www.forbesglobalproperties.com/members/driven-properties",
        "notes": "BUYER-ORIGIN: Downgraded. Forbes Global Properties UAE member with a real European luxury desk in Spain, which is a plausible path for UAE clients buying coastal Europe. Parent brokerage is broader than trophy-only and Italy is not evidenced. Official Spain-site footer: Office 101, Emaar Square 3, Downtown Dubai; +971 4 429 7040; info@drivenproperties.com. Score 6.",
    },
    {
        "city": "Abu Dhabi",
        "company_name": "Eagle Hills",
        "type": "real_estate_investor",
        "contact_name": "Mohamed Alabbar",
        "contact_role": "Chairman",
        "email": "info@eaglehills.com",
        "phone": "+971 2 497 9999",
        "website": "https://eaglehills.com",
        "linkedin_company": "https://www.linkedin.com/company/eagle-hills",
        "linkedin_contact": "",
        "investment_focus": "Large-scale mixed-use and luxury hospitality real estate, including Italian heritage hotel and estate projects",
        "geographic_focus": "Abu Dhabi HQ with projects across Europe, Africa and the Middle East, including Grand Hotel Des Bains, Venice",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "typical developments far above €6M–€12M; unknown for single-asset acquisitions",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://eaglehills.com/contact-us/",
        "source_2": "https://www.agbi.com/real-estate/2025/11/alabbar-to-convert-italian-castle-into-luxury-resort/",
        "notes": "BUYER-ORIGIN: UAE principal capital with documented Italian luxury/hospitality activity. Official contact: 9th Floor, Capital Plaza Towers, Corniche Street, Abu Dhabi; info@eaglehills.com; +971 2 497 9999. Company lists Grand Hotel Des Bains, Venice. AGBI/Bloomberg: Mohamed Alabbar bought Castello di Antognolla in Umbria for about $55 million as a personal investment to convert into a Six Senses resort. Institutional tickets are larger than €6M–€12M; included as a strategic UAE-Italy hospitality/trophy path, not as a likely bidder at this ticket. Amalfi relevance moderate (Italian heritage hospitality, not Campania).",
    },
    {
        "city": "Dubai",
        "company_name": "Jumeirah Group",
        "type": "hospitality_investor",
        "contact_name": "Edgar Ollé",
        "contact_role": "Global Vice President of Development, Hotels & Branded Residences",
        "email": "development@jumeirah.com",
        "phone": "+971 4 366 5070",
        "website": "https://www.jumeirah.com",
        "linkedin_company": "https://www.linkedin.com/company/jumeirah",
        "linkedin_contact": "https://www.linkedin.com/in/edgar-oll%C3%A9-33195628",
        "investment_focus": "Luxury hotel and branded-residence development and management; European coastal and city hotels",
        "geographic_focus": "Dubai-headquartered (Dubai Holding); Europe including Capri, London, Mallorca and Geneva",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "strong",
        "estimated_ticket": "unknown; typical hotels larger than €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.jumeirah.com/en/jumeirah-group/contact-us",
        "source_2": "https://www.jumeirah.com/en/stay/italy/jumeirah-capri-palace",
        "notes": "BUYER-ORIGIN: Dubai Holding/Jumeirah is UAE hospitality capital with an operating Italian coastal luxury hotel, Jumeirah Capri Palace in Anacapri, adjacent to the Amalfi Coast. Official corporate contact publishes development@jumeirah.com and HQ Level 5, Building 5, Dubai Design District; +971 4 366 5070. Edgar Ollé role is from public LinkedIn; the verified email is the published development inbox. More likely as hospitality/operator or branded-residence introduction than as acquirer of a single €6M–€12M residence. Score 9 because Capri is the strongest Amalfi-adjacent UAE hospitality proof-point found.",
    },
    {
        "city": "Dubai",
        "company_name": "DAMAC Group / DAMAC Capital",
        "type": "family_office",
        "contact_name": "Hussain Sajwani",
        "contact_role": "Founder and Chairman",
        "email": "connect@damacgroup.com",
        "phone": "+971 4 401 6204",
        "website": "https://www.damacgroup.com",
        "linkedin_company": "https://www.linkedin.com/company/damac-group",
        "linkedin_contact": "",
        "investment_focus": "Family investment office alongside property development; hotels and resorts, European residential (London Nine Elms), Italian fashion (Roberto Cavalli) and data centres",
        "geographic_focus": "Dubai HQ with disclosed activity in the UK, US, Maldives and Italy (fashion brand; Edgnex data-centre plans in Pregnana Milanese)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "family-office tickets described in third-party databases from about $1M–$50M; typical operating deals much larger",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.damacgroup.com/en-gb/contactus/",
        "source_2": "https://www.prnewswire.com/news-releases/damac-chairman-hussain-sajwanis-private-investment-firm-acquires-italian-fashion-brand-icon-roberto-cavalli-300966623.html",
        "notes": "BUYER-ORIGIN: Sajwani family capital (DAMAC Capital / DICO / Vision Investments) is UAE-origin private capital with Italy exposure via Roberto Cavalli and a reported Milan-area data centre, plus London luxury residential and a hotels & resorts pillar. Official group contact: DAMAC Executive Heights, Barsha Heights; connect@damacgroup.com; +971 4 401 6204. Do not treat DAMAC Properties sales offices as the prospect (those sell own Dubai developments). Amalfi relevance is weak: Italy exposure is fashion/infrastructure, not Campania trophy homes. Score 7.",
    },
    {
        "city": "Abu Dhabi",
        "company_name": "Abu Dhabi Capital Group",
        "type": "private_capital",
        "contact_name": "H.E. Abubaker Al Khoori",
        "contact_role": "Group Chief Executive Officer",
        "email": "info@abudhabicapital.ae",
        "phone": "+971 2 652 3999",
        "website": "https://www.adcg.ae",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Institutional private investment house with real estate, hospitality (Story Hospitality / The H Dubai) and global fund holdings",
        "geographic_focus": "Abu Dhabi HQ; official site claims presence across the Middle East, Europe, Asia, Africa and North America; hospitality described as luxury hotels in exclusive locations",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "institutional; typical deals larger than €6M–€12M; unknown for single trophy homes",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.adcg.ae/contact",
        "source_2": "https://www.adcg.ae/what-we-do-detail/7",
        "notes": "BUYER-ORIGIN: Official contact: CI Tower, Al Bateen Street, Abu Dhabi; info@abudhabicapital.ae; +971 2 652 3999. Who-we-are page names H.E. Abubaker Al Khoori as Group CEO. Real-estate page: income-yielding properties including The H Dubai, plus shareholdings in prime developments and funds globally. Hospitality portfolio includes Story Seychelles. Italy not specifically evidenced; included as UAE private capital with hospitality and European geographic claim, not as a villa broker. Score 7.",
    },
    {
        "city": "Dubai",
        "company_name": "FIVE Holdings",
        "type": "hospitality_investor",
        "contact_name": "Kabir Mulchandani",
        "contact_role": "Founder and Chairman",
        "email": "investor.relations@fiveglobalholdings.com",
        "phone": "+971 4 423 2879",
        "website": "https://five-holdings.com",
        "linkedin_company": "https://www.linkedin.com/company/fiveglobalholdings",
        "linkedin_contact": "",
        "investment_focus": "Vertically integrated luxury hotels, branded entertainment hospitality and related real estate",
        "geographic_focus": "Dubai hotels plus FIVE Zurich and Pacha/Destino hospitality assets in Ibiza, Spain",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown; typical owned hotels larger than €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://five-holdings.com/home/",
        "source_2": "https://www.five-holdings.com/wp-content/uploads/2024/04/FIVE-reports-69-revenue-growth-and-55-EBITDA-growth-in-FY-2023.pdf",
        "notes": "BUYER-ORIGIN: Dubai-headquartered hospitality owner with European coastal leisure DNA (Ibiza) relevant to an Amalfi hospitality/leisure reading. Official FY2023 PDF publishes investor.relations@fiveglobalholdings.com. Company LinkedIn lists +971 4 423 2879. Italy not evidenced. Score 8: +3 UAE capital, +2 international luxury hospitality, +2 European coastal, +1 leisure.",
    },
    {
        "city": "Dubai",
        "company_name": "Al Habtoor Group",
        "type": "hospitality_investor",
        "contact_name": "Khalaf Ahmad Al Habtoor",
        "contact_role": "Founder and Chairman",
        "email": "",
        "phone": "+971 4 394 1444",
        "website": "https://www.habtoor.com",
        "linkedin_company": "https://www.linkedin.com/company/al-habtoor-group",
        "linkedin_contact": "",
        "investment_focus": "Luxury hotel ownership and real estate; European trophy hotels",
        "geographic_focus": "Dubai HQ with owned hotels in Vienna, London, Budapest and elsewhere",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "disclosed European hotel deals well above €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.habtoor.com/en/25/contact/",
        "source_2": "https://www.hotel-online.com/news/al-habtoor-investment-acquires-starwoods-hotel-imperial-a-luxury-collection",
        "notes": "BUYER-ORIGIN: UAE family capital with documented European trophy-hotel ownership (Hotel Imperial Vienna, Hilton London Wembley). Official contact: Al Wasl Road, Al Safa 2; +971 4 394 1444; no public investment email. Italy not evidenced; ticket size of disclosed deals is larger than this asset. Score 7.",
    },
    {
        "city": "Dubai",
        "company_name": "JA Resorts & Hotels",
        "type": "hospitality_investor",
        "contact_name": "Ralph Porciani",
        "contact_role": "Chief Executive Officer",
        "email": "",
        "phone": "+971 4 814 5555",
        "website": "https://www.jaresortshotels.com",
        "linkedin_company": "https://www.linkedin.com/company/jaresorts",
        "linkedin_contact": "",
        "investment_focus": "Luxury and heritage hotels and resorts; recent European hotel acquisitions",
        "geographic_focus": "Dubai-headquartered (Dutco Group); UAE, Maldives and UK (Scotland) hotels",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "unknown; UK hotel acquisitions larger than €6M–€12M",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.travelandtourworld.com/news/article/ja-resorts-hotels-expands-into-uk-with-mar-hall-golf-spa-resort-and-the-bruntsfield-marking-major-milestone-in-global-growth/",
        "source_2": "https://source.jaresortshotels.com/contact-us",
        "notes": "BUYER-ORIGIN: Dutco/JA is UAE hospitality capital that has been buying European heritage hospitality (Mar Hall; The Bruntsfield, Scotland). Published hotel emails are reservations-only. Phone +971 4 814 5555. CEO Ralph Porciani named in acquisition coverage. Fit is as a hospitality acquirer of characterful European assets, not a residential broker. Score 7.",
    },
    {
        "city": "Dubai",
        "company_name": "Arzan Investment Management",
        "type": "hospitality_investor",
        "contact_name": "Hubert Viriot",
        "contact_role": "Partner, Hospitality",
        "email": "",
        "phone": "",
        "website": "https://www.arzanim.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Hospitality, residential and special-situations real estate; GCC hospitality fund platform; EMEA opportunistic deals",
        "geographic_focus": "DIFC HQ with London and New York offices; European hospitality sourcing; Portugal hotel affiliates",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "disclosed Dubai hotel deal $325M; typical tickets larger than €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.arzanim.com/",
        "source_2": "https://www.zawya.com/en/press-release/companies-news/arzan-investment-management-enters-binding-sale-and-purchase-agreement-for-fairmont-palm-dubai-da4tn5dq",
        "notes": "BUYER-ORIGIN: DIFC hospitality investor with an explicit European hospitality mandate (Viktor Persson focused on GCC and European opportunities; Portugal hotel operating background on the team). Official site: 601, Gate Village 8, DIFC. Zawya: AIM agreed to acquire Fairmont The Palm for $325M. No public email/phone on the contact page. Disclosed tickets are larger than this asset. Score 7.",
    },
    {
        "city": "Dubai",
        "company_name": "SKH Family Office",
        "type": "family_office",
        "contact_name": "Saqr Kamal Hasan",
        "contact_role": "Founder and Chairman",
        "email": "info@skhfamilyoffice.com",
        "phone": "+971 4 401 9195",
        "website": "https://skhfamilyoffice.com/",
        "linkedin_company": "https://www.linkedin.com/company/skh-fo",
        "linkedin_contact": "https://www.linkedin.com/in/saqr-hasan-0b0714171",
        "investment_focus": "Single-family office across hospitality, real estate, private equity and private credit; luxury coastal hospitality (The Cove Rotana Resort)",
        "geographic_focus": "DIFC Dubai HQ; UAE hospitality; international real estate examples are mainly UK/NL/US logistics plus London serviced apartments (Viridian)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "AED 500 million disclosed for Cove Rotana; unknown for single-asset tickets",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://skhfamilyoffice.com/",
        "source_2": "https://www.journaldespalaces.com/en/pressrelease-77018-united-arab-emirates-group-or-hotel-buyout-skh-family-office-completes-strategic-acquisition-of-the-cove-rotana-resort-ras-al-khaimah.html",
        "notes": "BUYER-ORIGIN: Verified DIFC family office with coastal hospitality ownership. Official site: Level 4, Gate Village Building 5, DIFC; info@skhfamilyoffice.com; 04 401 9195. Journal des Palaces (14 January 2026) reported acquisition of The Cove Rotana Resort, Ras Al Khaimah. International RE examples on the site are industrial/logistics plus London serviced apartments, not Italian trophy homes. Score 7: UAE family capital + hospitality + coastal asset, without Italy proof.",
    },
    {
        "city": "Abu Dhabi",
        "company_name": "AlNowais Investments",
        "type": "family_office",
        "contact_name": "Hussain Al Nowais",
        "contact_role": "Chairman",
        "email": "info@alnowais.com",
        "phone": "+971 2 6918000",
        "website": "https://www.alnowais.com",
        "linkedin_company": "https://www.linkedin.com/company/alnowais-investments",
        "linkedin_contact": "https://www.linkedin.com/in/hussain-al-nowais-a5806959",
        "investment_focus": "Family-controlled principal investments including a dedicated real-estate and hospitality division (Park Rotana, Rotana stakes, Saadiyat Rotana)",
        "geographic_focus": "Abu Dhabi HQ; UAE hospitality assets plus a mixed-use project in Johor Bahru, Malaysia",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "no",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "group real-estate investments exceed AED 3 billion; unknown for single-asset acquisitions",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "verified",
        "source_1": "https://www.alnowais.com/contact-us/",
        "source_2": "https://www.alnowais.com/our-businness/core-businesses/al-nowais-real-estate/",
        "notes": "BUYER-ORIGIN: Downgraded. Genuine Abu Dhabi family capital with hospitality, but no Italy/Europe luxury-residential evidence and disclosed tickets are far above €6M–€12M. Official contact: P.O. Box 54457, Abu Dhabi; +971 2 6918000; info@alnowais.com. Distinct from the Rotana operator (removed this run). Kept only as a contactable UAE hospitality family office. Score 5.",
    },
    {
        "city": "Dubai",
        "company_name": "SHUAA Capital",
        "type": "real_estate_investor",
        "contact_name": "",
        "contact_role": "",
        "email": "info@shuaa.com",
        "phone": "+971 4 330 3600",
        "website": "https://www.shuaa.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Real estate investment, asset management and hospitality funds; high-end residential platforms including Northacre in the UK",
        "geographic_focus": "UAE, UK and Eastern Europe real estate; Saudi hospitality funds",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.shuaa.com/contact-us",
        "source_2": "https://www.shuaa.com/what-we-do/asset-management/real-estate/real-estate-fund-management",
        "notes": "BUYER-ORIGIN: UAE platform with European luxury-residential (Northacre, UK) and hospitality funds. Official contact: The H Hotel Dubai, Office Tower 15th Floor, Office 1502; info@shuaa.com; +971 4 330 3600. Named real-estate MD not published. Italy not evidenced. Score 6.",
    },
    {
        "city": "Dubai",
        "company_name": "Solida Capital",
        "type": "real_estate_investor",
        "contact_name": "Joao Saracho",
        "contact_role": "Managing Director",
        "email": "contact@solidacapital.com",
        "phone": "+971 54 581 6191",
        "website": "https://www.solidacapital.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Proprietary and partnered European real estate across offices, hospitality, student housing and residential; Gulf-to-Europe capital bridge",
        "geographic_focus": "DIFC Dubai HQ deploying into Central and Eastern Europe (Warsaw, Bucharest) with stated ambition to channel Middle Eastern capital into Europe",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "no",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown; firm says it can make relatively small investments as well as significant equity commitments",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.solidacapital.com/about-us/",
        "source_2": "https://www.solidacapital.com/contact/",
        "notes": "BUYER-ORIGIN: DIFC-headquartered investor whose Managing Director publicly describes bringing Gulf capital into European real estate. Official contact: Gate Village 3, 1st Floor, DIFC; +971 545816191; contact@solidacapital.com. Geographic focus is Poland/Romania rather than Italy, so italy_interest=no. Included as a UAE-based European RE principal, not as an Amalfi specialist. Score 6.",
    },
    {
        "city": "Dubai",
        "company_name": "Investbridge Capital",
        "type": "private_equity_real_estate",
        "contact_name": "",
        "contact_role": "",
        "email": "",
        "phone": "+971 4 451 3234",
        "website": "https://investbridge.capital",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Alternative investment and asset management with a real-estate practice focused on hospitality assets and niche opportunities across the capital stack; GCC LP placement",
        "geographic_focus": "DFSA-regulated DIFC firm with a London office; GCC LP coverage",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://investbridge.capital/",
        "source_2": "https://www.dfsa.ae/public-register/firms/investbridge-capital-limited",
        "notes": "BUYER-ORIGIN: DIFC hospitality-real-estate investor/placement platform that can introduce GCC LP capital, not a residential luxury broker. Official site: Gate Village 6, Level 6, DIFC; +971 4 451 3234. No public email on the homepage. Score 6.",
    },
    {
        "city": "Dubai",
        "company_name": "Handle Private Capital",
        "type": "other_relevant",
        "contact_name": "",
        "contact_role": "",
        "email": "info@handle.ae",
        "phone": "+971 4 313 2435",
        "website": "https://handle.ae",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Execution advisory for family offices and private capital, including UAE–EU family-office investment structures",
        "geographic_focus": "Dubai with EU holding jurisdictions such as Luxembourg, Ireland and the Netherlands",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "5",
        "priority": "C",
        "verification_status": "verified",
        "source_1": "https://handle.ae/private-capital/contact-us/",
        "source_2": "https://handle.ae/private-capital/investor-governance/family-office-mandates/uae-eu-family-office-investments/",
        "notes": "BUYER-ORIGIN: Downgraded. Not a broker or principal buyer. Official contact previously verified: Standard Chartered Tower, Emaar Square; info@handle.ae; +971 4 313 2435. Separate page describes structuring UAE–EU family-office investments, so it can be an introducer to UAE families allocating into Europe, not a qualified Amalfi buyer itself. Score 5.",
    },
    {
        "city": "Dubai",
        "company_name": "JLL Hotels & Hospitality MEA",
        "type": "other_relevant",
        "contact_name": "Amr Nady",
        "contact_role": "Head of Hotels & Hospitality MEA; Managing Director, Global Hotel Desk",
        "email": "",
        "phone": "",
        "website": "https://www.jll.com",
        "linkedin_company": "https://www.linkedin.com/company/jll-mena",
        "linkedin_contact": "https://www.linkedin.com/in/amr-nady-0b1b15a",
        "investment_focus": "Hotel investment sales, advisory and cross-border hospitality transactions for Middle Eastern capital",
        "geographic_focus": "Dubai / MEA platform advising regional investors on international hotel strategies, including Europe",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown; recent advised deals much larger than €6M–€12M",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.linkedin.com/in/amr-nady-0b1b15a",
        "source_2": "https://www.linkedin.com/company/jll-mena",
        "notes": "BUYER-ORIGIN: Introducer to UAE/MENA hospitality capital rather than a residential agency. Amr Nady's public profile states he advises Middle Eastern investors on international hotel investment strategies via JLL's Global Hotel Desk, including trophy-hotel work in the UK and Northern Europe. No public JLL email confirmed. Relevant if the Amalfi asset is positioned as boutique hospitality. Score 7.",
    },
    {
        "city": "Dubai",
        "company_name": "CBRE MENA Hotels & Tourism",
        "type": "other_relevant",
        "contact_name": "Ali Manzoor",
        "contact_role": "Head of Hospitality / Senior Director, Hotels & Tourism",
        "email": "",
        "phone": "",
        "website": "https://www.cbre.ae/services/property-types/hotels",
        "linkedin_company": "https://www.linkedin.com/company/cbre-mena",
        "linkedin_contact": "https://www.linkedin.com/in/ali-manzoor-88546562",
        "investment_focus": "Hotel investment advisory, valuations, operator selection and cross-border hospitality assignments",
        "geographic_focus": "UAE and MENA, with a regional team covering cross-border hospitality work",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.cbre.ae/services/property-types/hotels",
        "source_2": "https://www.linkedin.com/in/ali-manzoor-88546562",
        "notes": "BUYER-ORIGIN: Hospitality-investment introducer for a mixed-use/leisure reading of the Italian asset. Official CBRE UAE hotels page names Ali Manzoor, Ben Parkins and Christopher Robson. No public email/phone on that page. Score 6.",
    },
    {
        "city": "Dubai",
        "company_name": "Colliers MENA Hospitality & Tourism",
        "type": "other_relevant",
        "contact_name": "Nicolas Nasra",
        "contact_role": "Director - Hospitality & Tourism Advisory; Head of Hotel Advisory",
        "email": "",
        "phone": "+971 55 769 9797",
        "website": "https://www.colliers.com/en-ae/services/hospitality-services",
        "linkedin_company": "https://www.linkedin.com/company/colliers",
        "linkedin_contact": "",
        "investment_focus": "Hospitality, leisure and tourism advisory including transaction support, operator search and coastal/wellness destinations",
        "geographic_focus": "UAE and wider MENA; case work includes luxury beachfront and wellness destinations",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.colliers.com/en-ae/services/hospitality-services",
        "source_2": "https://www.colliers.com/en-ae/united-arab-emirates/cities/dubai",
        "notes": "BUYER-ORIGIN: Relevant if the Amalfi asset is positioned as boutique hospitality/leisure. Official hospitality page names Nicolas Nasra as Head of Hotel Advisory, covering hotels, resorts, branded residences, wellness, marinas and leisure, with buy- and sell-side transaction advisory. Mobile +971 55 769 9797 published on that page. No email published. Score 6.",
    },
]


def priority_from_score(score: str) -> str:
    n = int(score)
    if n >= 8:
        return "A"
    if n >= 6:
        return "B"
    return "C"


def qa(rows: list[dict]) -> None:
    errors: list[str] = []
    names: dict[str, str] = {}
    domains: dict[str, str] = {}
    emails: dict[str, str] = {}
    for i, row in enumerate(rows, start=1):
        missing = [h for h in HEADERS if h not in row]
        if missing:
            errors.append(f"row {i} missing keys {missing}")
            continue
        if row["country"] != COUNTRY:
            errors.append(f"{row['company_name']}: bad country")
        if row["type"] not in ALLOWED_TYPE:
            errors.append(f"{row['company_name']}: bad type {row['type']}")
        if row["buyer_origin_relevance"] not in ALLOWED_BUYER_ORIGIN:
            errors.append(f"{row['company_name']}: bad buyer_origin")
        if row["italy_interest"] not in ALLOWED_ITALY:
            errors.append(f"{row['company_name']}: bad italy_interest")
        if row["amalfi_coast_relevance"] not in ALLOWED_AMALFI:
            errors.append(f"{row['company_name']}: bad amalfi")
        if row["luxury_real_estate"] not in ALLOWED_LUXURY:
            errors.append(f"{row['company_name']}: bad luxury")
        if row["hospitality_interest"] not in ALLOWED_HOSP:
            errors.append(f"{row['company_name']}: bad hospitality")
        if row["verification_status"] not in ALLOWED_VERIF:
            errors.append(f"{row['company_name']}: bad verification")
        if row["priority"] not in ALLOWED_PRIORITY:
            errors.append(f"{row['company_name']}: bad priority")
        if row["priority"] != priority_from_score(row["fit_score"]):
            errors.append(
                f"{row['company_name']}: priority {row['priority']} != score {row['fit_score']}"
            )
        if not (1 <= int(row["fit_score"]) <= 10):
            errors.append(f"{row['company_name']}: fit_score out of range")
        if row["priority"] == "A" and row["buyer_origin_relevance"] not in {"strong", "moderate"}:
            errors.append(f"{row['company_name']}: Priority A needs strong/moderate buyer origin")
        email = row["email"].strip()
        if email and not EMAIL_RE.match(email):
            errors.append(f"{row['company_name']}: invalid email {email}")
        for url_field in ("website", "linkedin_company", "linkedin_contact", "source_1", "source_2"):
            val = row[url_field].strip()
            if val and not URL_RE.match(val):
                errors.append(f"{row['company_name']}: invalid URL in {url_field}: {val}")
        key = row["company_name"].strip().lower()
        if key in names:
            errors.append(f"duplicate company_name: {row['company_name']}")
        names[key] = row["company_name"]
        if email:
            el = email.lower()
            if el in emails:
                errors.append(f"duplicate email {email}")
            emails[el] = row["company_name"]
        site = row["website"].strip().lower().rstrip("/")
        if site:
            if site in domains and names.get(key) != row["company_name"]:
                errors.append(f"duplicate website {site}")
            domains[site] = row["company_name"]
        if row["last_verified"] != LAST_VERIFIED:
            errors.append(f"{row['company_name']}: last_verified")
    if errors:
        raise SystemExit("QA failed:\n" + "\n".join(errors))


def main() -> None:
    for row in ROWS:
        row["country"] = COUNTRY
        row["last_verified"] = LAST_VERIFIED
        for h in HEADERS:
            row.setdefault(h, "")
    qa(ROWS)
    out = Path("/workspace/data/real-estate-prospects/united-arab-emirates.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for row in ROWS:
            writer.writerow({h: row.get(h, "") for h in HEADERS})

    n = len(ROWS)
    n_a = sum(1 for r in ROWS if r["priority"] == "A")
    n_b = sum(1 for r in ROWS if r["priority"] == "B")
    n_c = sum(1 for r in ROWS if r["priority"] == "C")
    n_email = sum(1 for r in ROWS if r["email"].strip())
    print(f"Wrote {n} rows to {out}")
    print(f"Priority A={n_a} B={n_b} C={n_c} verified_email={n_email}")


if __name__ == "__main__":
    main()
