#!/usr/bin/env python3
"""Generate the UAE luxury real-estate prospect CSV from verified research notes."""

from __future__ import annotations

import csv
from pathlib import Path

HEADERS = [
    "country",
    "city",
    "company_name",
    "type",
    "contact_name",
    "contact_role",
    "email",
    "phone",
    "website",
    "linkedin_company",
    "linkedin_contact",
    "investment_focus",
    "geographic_focus",
    "estimated_ticket",
    "italy_interest",
    "luxury_real_estate",
    "hospitality_interest",
    "fit_score",
    "verification_status",
    "source_1",
    "source_2",
    "notes",
    "last_verified",
]

LAST_VERIFIED = "2026-08-27"
COUNTRY = "United Arab Emirates"

ROWS = [
    {
        "city": "Dubai",
        "company_name": "Knight Frank UAE",
        "type": "luxury_agency",
        "contact_name": "Nicholas Spencer",
        "contact_role": "Partner - Head of Prime Residential; Private Capital & Family Enterprises MENA",
        "email": "privateoffice@knightfrank.com",
        "phone": "+971 4 451 2000",
        "website": "https://www.knightfrank.ae",
        "linkedin_company": "https://www.linkedin.com/company/knightfrankmena",
        "linkedin_contact": "https://www.linkedin.com/in/nicholas-spencer-846466b8",
        "investment_focus": "Prime and super-prime residential; private capital and family-office advisory; international project sales",
        "geographic_focus": "UAE and GCC, with international sales into the UK and other prime markets",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://www.knightfrank.ae/contact/people/nicholas-spencer-aeme276",
        "source_2": "https://www.knightfrank.ae/en/residential/international-project-sales",
        "notes": "Official Knight Frank UAE people page confirms Spencer as Partner and Head of Prime Residential advising private clients and family offices on prime property across the UK and Gulf. International Project Sales page states the Dubai team facilitates interest in the UK, Europe and other prime global markets. Direct people-page email is not published; Private Office email is taken from Knight Frank's official Private Office materials. Dubai HQ: Media One Tower, Dubai Media City. Direct lines published for Spencer: +971 4 426 7640 / +971 54 584 4365.",
    },
    {
        "city": "Dubai",
        "company_name": "Savills Middle East",
        "type": "luxury_agency",
        "contact_name": "Andrew Cummings",
        "contact_role": "Head of Residential Agency, Middle East",
        "email": "international@savills.me",
        "phone": "+971 4 365 7700",
        "website": "https://www.savills.me",
        "linkedin_company": "https://www.linkedin.com/company/savillsmiddleeast",
        "linkedin_contact": "https://www.linkedin.com/in/ancummings",
        "investment_focus": "Prime and branded residential agency, international residential marketing and cross-border private-client sales",
        "geographic_focus": "UAE (Dubai, Abu Dhabi) and wider Middle East, with London/international residential distribution",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://www.savills.co.uk/insight-and-opinion/savills-news/382799/savills-presents-london-and-dubai-s-most-exclusive-residences-at-cityscape-global-riyadh",
        "source_2": "https://dubai.savills.ae/forms/contact-office.aspx?id=241187-0",
        "notes": "Official Savills press release publishes international@savills.me and +971 4 365 7799 for Middle East international residential enquiries. Dubai office contact page lists 22nd floor, Arenco Tower, Sheikh Zayed Road, +971 4 365 7700. Cummings is publicly identified as Head of Residential Agency Middle East; personal email not used because it was not confirmed on a Savills domain page. Privacy policy also publishes dubai@savills.me as a general Dubai address.",
    },
    {
        "city": "Dubai",
        "company_name": "Christie's International Real Estate Dubai",
        "type": "luxury_agency",
        "contact_name": "Jackie Johns",
        "contact_role": "Managing Partner",
        "email": "info@christiesrealestatedubai.com",
        "phone": "+971 4 585 9074",
        "website": "https://www.christiesrealestatedubai.com",
        "linkedin_company": "https://www.linkedin.com/company/ciredxb",
        "linkedin_contact": "https://www.linkedin.com/in/jackie-johns-75048122",
        "investment_focus": "UHNW and trophy residential; Private Office off-market advisory; global luxury referrals across the Christie's International Real Estate network",
        "geographic_focus": "Dubai, Abu Dhabi and Ras Al Khaimah, with affiliate coverage in 50+ countries including European luxury markets",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://www.christiesrealestatedubai.com/the-journal/new-office-opening-in-media-city/",
        "source_2": "https://www.christiesrealestatedubai.com/enquiries/",
        "notes": "Official July 2025 company announcement names Jackie Johns and Dinesh Chhatwani as Managing Partners and publishes +971 4 585 9074 and info@christiesrealestatedubai.com. Firm describes a Private Office for UHNW trophy assets and a multilingual agent base with access to rare real estate worldwide. Offices: DIFC, Bay Square, World Trade Centre and Dubai Media City. Company LinkedIn also publishes privateoffice@ciredubai.com for the Private Office desk; the website enquiry email is used here because it is on the official domain.",
    },
    {
        "city": "Dubai",
        "company_name": "Dubai Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Chris Whitehead",
        "contact_role": "Managing Partner",
        "email": "",
        "phone": "+971 4 455 0896",
        "website": "https://sothebysrealty.ae",
        "linkedin_company": "https://www.linkedin.com/company/dubaisothebysinternationalrealty",
        "linkedin_contact": "https://www.linkedin.com/in/chwhitehead",
        "investment_focus": "Super-prime and blue-chip residential; private-client advisory; international Sotheby's International Realty referrals",
        "geographic_focus": "Dubai flagship, with group leadership also covering KSA and the UK super-prime markets",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "partially_verified",
        "source_1": "https://sothebysrealty.ae/management/chris-whitehead/",
        "source_2": "https://sothebysrealty.ae/contact-us/",
        "notes": "Official management page confirms Chris Whitehead as Managing Partner for the Dubai flagship, positioned in regional and international private-client markets. Contact page publishes +971 4 455 0896 and WhatsApp +971 50 816 1409; the only email on that page is pr@sothebysrealty.ae (PR), so sales email is left empty. Head office: EMAAR Business Park, Building 4, Sheikh Zayed Road. Group Chairman & CEO George Azar publicly comments on UAE/UK/KSA ultra-prime acquisitions; personal emails not published.",
    },
    {
        "city": "Abu Dhabi",
        "company_name": "Abu Dhabi Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "",
        "contact_role": "",
        "email": "customercare@abudhabi-sothebysrealty.ae",
        "phone": "+971 4 455 0860",
        "website": "https://abudhabi-sothebysrealty.ae",
        "linkedin_company": "https://www.linkedin.com/company/abudhabi-sothebys-international-realty",
        "linkedin_contact": "",
        "investment_focus": "Luxury residential sales and international Sotheby's International Realty referrals for Abu Dhabi private clients",
        "geographic_focus": "Abu Dhabi, with access to the global Sotheby's International Realty network",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://abudhabi-sothebysrealty.ae/en/contact-us",
        "source_2": "https://www.linkedin.com/company/abudhabi-sothebys-international-realty",
        "notes": "Official contact page lists Office 610, Dar Al Salam Tower, Corniche Street, Al Danah, Abu Dhabi; customercare@abudhabi-sothebysrealty.ae; +971 4 455 0860; WhatsApp +971 54 727 9623. Separate affiliate from the Dubai Sotheby's office. Named Abu Dhabi decision-maker not published on the contact page.",
    },
    {
        "city": "Dubai",
        "company_name": "Engel & Völkers Dubai",
        "type": "luxury_agency",
        "contact_name": "Daniel Abdul Hadi",
        "contact_role": "CEO Middle East",
        "email": "dubai@engelvoelkers.com",
        "phone": "+971 4 422 3500",
        "website": "https://www.engelvoelkers.com/ae/en",
        "linkedin_company": "https://www.linkedin.com/company/engel&voelkers-dubai",
        "linkedin_contact": "https://www.linkedin.com/in/danielhadi",
        "investment_focus": "Luxury homes, villas and investment properties; Private Office off-market advisory with global Engel & Völkers referrals",
        "geographic_focus": "Dubai, Abu Dhabi and Ras Al Khaimah, connected to Engel & Völkers shops across Europe including Italy",
        "estimated_ticket": "unknown",
        "italy_interest": "yes",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://www.engelvoelkers.com/ae/en/imprint",
        "source_2": "https://www.engelvoelkers.com/ae/en/shops/dubai-private-office",
        "notes": "Official imprint names Engel and Voelkers Real Estate LLC, Al Khail Plaza Floor 7, Jumeirah Village Triangle; CEO Middle East Daniel Abdul Hadi; dubai@engelvoelkers.com; +971 4 422 3500; RERA 16081. Private Office shop page states exclusive off-market luxury advisory in Dubai and worldwide via the global network. Italy interest is via the brand's Italian shop network, not a published Dubai-to-Amalfi mandate.",
    },
    {
        "city": "Dubai",
        "company_name": "BARNES Dubai",
        "type": "luxury_agency",
        "contact_name": "",
        "contact_role": "",
        "email": "",
        "phone": "+971 4 449 1087",
        "website": "https://www.barnes-international.com/en/contact/united-arab-emirates/barnes-dubai.html",
        "linkedin_company": "https://www.linkedin.com/company/barnes-dubai",
        "linkedin_contact": "",
        "investment_focus": "Ultra-luxury residential; international private-client referrals; art-de-vivre and lifestyle assets through the BARNES network",
        "geographic_focus": "Dubai as Middle East HQ, with BARNES offices across France, Italy and other European luxury destinations",
        "estimated_ticket": "unknown",
        "italy_interest": "yes",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "partially_verified",
        "source_1": "https://www.barnes-international.com/it/contatto/emirati-arabi-uniti/barnes-dubai.html",
        "source_2": "https://www.zawya.com/en/press-release/companies-news/barnes-international-establishes-strategic-partnership-with-dubai-land-department-bm1k8pxq",
        "notes": "Official BARNES International agency page lists Emaar Square, Building 4, Office 703, Downtown Dubai. Zawya press release states BARNES Dubai is the first Middle Eastern branch and regional HQ; media email marketing.dubai@barnes-international.com is press-only so sales email is left empty. Company LinkedIn publishes +971 4 449 1087. Strong fit because BARNES operates Italian offices and a UHNW European client network; named Dubai MD not published on the agency page.",
    },
    {
        "city": "Dubai",
        "company_name": "John Taylor Dubai",
        "type": "luxury_agency",
        "contact_name": "Andrew Cleator",
        "contact_role": "Managing Director, Middle East",
        "email": "dubai@john-taylor.com",
        "phone": "+971 4 451 6543",
        "website": "https://john-taylor.ae",
        "linkedin_company": "https://www.linkedin.com/company/john-taylor-dubai-uae",
        "linkedin_contact": "https://www.linkedin.com/in/andrew-cleator-1059a33",
        "investment_focus": "Prime and super-prime residential sales for international UHNW clients",
        "geographic_focus": "Dubai, connected to John Taylor offices in Monaco, the French Riviera, Milan and other European luxury markets",
        "estimated_ticket": "unknown",
        "italy_interest": "yes",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "verification_status": "verified",
        "source_1": "https://john-taylor.ae/en/contact",
        "source_2": "https://www.john-taylor.com/luxury-real-estate-agency/dubai/",
        "notes": "Official Dubai contact page lists Office 1607, Sidra Tower, Sheikh Zayed Road; +971 4 451 6543; dubai@john-taylor.com. John Taylor (Dassault Artcurial Group) has a 150-year Riviera luxury-agency heritage and publicly lists Milan among its offices. Company LinkedIn announced Andrew Cleator as Managing Director for the Middle East in 2026; previously Associate Partner at Knight Frank MENA and Managing Director at Luxhabitat Sotheby's International Realty. Highest agency fit for an Amalfi Coast trophy home because of the Italian/Riviera network plus a Dubai UHNW desk.",
    },
    {
        "city": "Dubai",
        "company_name": "Fine & Country Dubai Invest",
        "type": "luxury_agency",
        "contact_name": "Simon Pitkin",
        "contact_role": "CEO",
        "email": "dubai.invest@fineandcountry.com",
        "phone": "+971 55 114 8943",
        "website": "https://www.fineandcountry.ae/dubai-invest-estate-agents",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Premium and investment residential; international Fine & Country referrals",
        "geographic_focus": "Dubai, with Fine & Country offices in Italy and other European markets",
        "estimated_ticket": "unknown",
        "italy_interest": "yes",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://www.fineandcountry.ae/dubai-invest-estate-agents/contact",
        "source_2": "https://www.fineandcountry.ae/legal-notice-impressum",
        "notes": "Official contact page lists Simon Pitkin as CEO; dubai.invest@fineandcountry.com; sales +971 55 114 8943; CEO mobile +971 50 314 0071. Registered as Roman Realty L.L.C. trading as Fine & Country Dubai Invest, Office 1103-10, The One Tower, Barsha Heights. Fine & Country's UAE site includes Italy in its country network, supporting cross-border introductions. Separate Palm Jumeirah Fine & Country office exists; this row is the investment-focused Dubai office.",
    },
    {
        "city": "Dubai",
        "company_name": "LuxuryProperty.com",
        "type": "luxury_agency",
        "contact_name": "Jason Hayes",
        "contact_role": "Founder and Chairman",
        "email": "hello@luxuryproperty.com",
        "phone": "+971 4 563 5900",
        "website": "https://www.luxuryproperty.com",
        "linkedin_company": "https://www.linkedin.com/company/luxury-property-com",
        "linkedin_contact": "https://www.linkedin.com/in/jasonhayes-luxuryproperty",
        "investment_focus": "Luxury residential brokerage plus a global marketplace for branded residences, hospitality assets and other high-value lifestyle assets",
        "geographic_focus": "Dubai HQ with published offices in London Mayfair and New York",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "verification_status": "verified",
        "source_1": "https://www.luxuryproperty.com/contact",
        "source_2": "https://www.luxuryproperty.com/team/jason_hayes",
        "notes": "Official contact schema publishes hello@luxuryproperty.com, +971 4 563 5900 and 204 Bay Square 2, Business Bay, Dubai. Founder/Chairman Jason Hayes is named on the official team page. Business mixes brokerage with a luxury marketplace; included because it markets exceptional real estate and hospitality assets to HNW/UHNW buyers from a Dubai base, not as a mass portal.",
    },
    {
        "city": "Dubai",
        "company_name": "Chestertons MENA",
        "type": "luxury_agency",
        "contact_name": "John Stevens",
        "contact_role": "Chief Executive Officer",
        "email": "dubai@chestertons.com",
        "phone": "+971 4 381 0200",
        "website": "https://www.chestertonsmena.com",
        "linkedin_company": "https://www.linkedin.com/company/chestertonsmena",
        "linkedin_contact": "https://www.linkedin.com/in/johnstevens2",
        "investment_focus": "Residential and commercial agency, valuation and advisory; UK-heritage luxury brand in the UAE",
        "geographic_focus": "Dubai and Abu Dhabi, with the historic Chestertons network in the UK",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "verification_status": "verified",
        "source_1": "https://www.chestertonsmena.com/contact/",
        "source_2": "https://www.linkedin.com/company/chestertonsmena",
        "notes": "Official contact page lists Office 2503, Marina Plaza, Dubai Marina; dubai@chestertons.com; +971 4 381 0200. Abu Dhabi office: Tamouh Tower, Al Reem Island, abudhabi@chestertons.com. John Stevens is identified as CEO on the company LinkedIn. Mix of consultancy and residential; included as a UK luxury-heritage firm with UAE UHNW reach, not as a mass off-plan broker.",
    },
    {
        "city": "Dubai",
        "company_name": "Hamptons International Dubai",
        "type": "luxury_agency",
        "contact_name": "",
        "contact_role": "",
        "email": "enquiries@hamptons.ae",
        "phone": "+971 4 366 1662",
        "website": "https://www.hamptons.ae",
        "linkedin_company": "https://www.linkedin.com/company/hamptonsdxb",
        "linkedin_contact": "",
        "investment_focus": "Residential sales and letting with UK Hamptons heritage and international marketing of Dubai property",
        "geographic_focus": "Dubai, with the historic Hamptons brand in the UK",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "6",
        "verification_status": "verified",
        "source_1": "https://www.hamptons.ae/en/contact-us/",
        "source_2": "https://www.hamptons.ae/en/sell-property-in-dubai/",
        "notes": "Official contact page lists enquiries@hamptons.ae; +971 4 366 1662; head office Emaar Business Park, The Greens, Building 3, First Floor. Sell page states the firm can market property to international as well as local buyers. Emaar-group affiliated brokerage; broader than pure trophy, but the UK luxury brand and published international marketing capability are relevant for UHNW introductions. Named sales MD not published on the contact page.",
    },
    {
        "city": "Dubai",
        "company_name": "Allsopp & Allsopp Private Office",
        "type": "luxury_agency",
        "contact_name": "",
        "contact_role": "",
        "email": "",
        "phone": "+971 4 429 4444",
        "website": "https://www.allsoppandallsopp.com/private-office",
        "linkedin_company": "https://www.linkedin.com/company/allsopp-%26-allsopp",
        "linkedin_contact": "",
        "investment_focus": "UHNW and family-office advisory; off-market residential at AED 25 million and above",
        "geographic_focus": "Dubai trophy residential, with claimed global UHNW marketing",
        "estimated_ticket": "AED 25M+ private-office threshold (about €6M+)",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "verification_status": "partially_verified",
        "source_1": "https://www.allsoppandallsopp.com/private-office",
        "source_2": "https://www.allsoppandallsopp.com/dubai/about-us/news-videos/1753-an-update-from-allsopp-allsopp",
        "notes": "Official Private Office page states the division serves HNWI/UHNWI and family offices and specialises in properties valued at AED 25 million and above, with off-market presentation and international marketing. Parent firm is a large Dubai brokerage; this row is the private-office division only. No dedicated Private Office email is published on that page (parent media email e.bates@allsoppandallsopp.com is press-only). Phone is the published company line. Ticket threshold is compatible with a €6M–€12M Italian estate.",
    },
    {
        "city": "Dubai",
        "company_name": "Origin Private Office",
        "type": "luxury_agency",
        "contact_name": "Ross Savas",
        "contact_role": "Senior Managing Partner",
        "email": "",
        "phone": "",
        "website": "https://www.originpo.com",
        "linkedin_company": "https://www.linkedin.com/company/originpo",
        "linkedin_contact": "",
        "investment_focus": "Private-office, concierge and ultra-luxury brokerage for globally mobile UHNW clients; off-market acquisitions and sales",
        "geographic_focus": "Offices in Dubai, Abu Dhabi, Singapore and New York; claims 10+ luxury markets",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "verification_status": "partially_verified",
        "source_1": "https://www.originpo.com/",
        "source_2": "https://www.originpo.com/about",
        "notes": "Official site names Ross Savas as Senior Managing Partner and Georgina Atkinson as Managing Partner. Dubai office: The One Tower, Sheikh Zayed Road; Abu Dhabi office: Sky Tower, Al Reem Island. No public email or phone is published on the homepage or about page, so those fields are empty. Included because it is a relationship-led UHNW private office with cross-border real-estate execution, a plausible introduction channel for a trophy Italian coastal estate.",
    },
    {
        "city": "Dubai",
        "company_name": "Driven Properties",
        "type": "luxury_agency",
        "contact_name": "Abdullah Al Ajaji",
        "contact_role": "Founder and CEO",
        "email": "info@drivenproperties.com",
        "phone": "+971 4 429 7040",
        "website": "https://www.drivenproperties.com",
        "linkedin_company": "https://www.linkedin.com/company/driven-properties-real-estate",
        "linkedin_contact": "",
        "investment_focus": "Luxury residential brokerage; Forbes Global Properties exclusive UAE member; European luxury listings via Spain office",
        "geographic_focus": "Dubai HQ with published luxury offices in Spain (Madrid), plus other international branches",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "verification_status": "verified",
        "source_1": "https://www.drivenproperties.es/en",
        "source_2": "https://www.forbesglobalproperties.com/members/driven-properties",
        "notes": "Forbes Global Properties lists Driven as its UAE member. Official Spain-site footer publishes Dubai HQ at Office 101, Emaar Square 3, Downtown Dubai; +971 4 429 7040; info@drivenproperties.com. Spain office lists Costa del Sol, Madrid and Balearic Islands luxury stock, evidencing a European luxury desk. Parent brokerage is broader than trophy-only; included for the FGP network and European buyer/listing capability. Founder/CEO Abdullah Al Ajaji is publicly identified; personal email not published.",
    },
    {
        "city": "Dubai",
        "company_name": "V Capital",
        "type": "luxury_agency",
        "contact_name": "",
        "contact_role": "",
        "email": "advisory@vcapital.ae",
        "phone": "+971 55 554 0762",
        "website": "https://www.vcapital.ae",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Private portfolio curation of Dubai trophy and waterfront villas for HNIs, family offices and global buyers",
        "geographic_focus": "Dubai ultra-luxury districts; inbound global capital including European buyers",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "verification_status": "verified",
        "source_1": "https://www.vcapital.ae/",
        "source_2": "https://www.vcapital.ae/",
        "notes": "Official site publishes advisory@vcapital.ae and WhatsApp +971 55 554 0762 and describes private curation of trophy assets, waterfront villas and branded residences exclusively for HNIs and family offices. Mandate is primarily Dubai inbound rather than Italian outbound, so fit is as a UHNW introducer rather than an Italy specialist. Named principal not published on the homepage.",
    },
    {
        "city": "Dubai",
        "company_name": "Espace Real Estate",
        "type": "luxury_agency",
        "contact_name": "John Lyons",
        "contact_role": "Managing Director",
        "email": "",
        "phone": "+971 4 306 9999",
        "website": "https://www.espace.ae",
        "linkedin_company": "https://www.linkedin.com/company/espace-real-estate",
        "linkedin_contact": "",
        "investment_focus": "Prime Dubai residential sales and leasing, including AED 10M–30M+ villas",
        "geographic_focus": "Dubai prime villa and townhouse communities",
        "estimated_ticket": "unknown",
        "italy_interest": "no",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "6",
        "verification_status": "partially_verified",
        "source_1": "https://www.espace.ae/meet-the-team-detail/john-lyons",
        "source_2": "https://www.espace.ae/contact",
        "notes": "Recognised Dubai prime/luxury specialist. Official team page names John Lyons as Managing Director. Company LinkedIn publishes +971 4 306 9999. Contact page has no published email, so email is empty. Italy/international desk not evidenced; included as a UHNW Dubai villa specialist that may know resident buyers of European second homes. Score capped because activity is Dubai-centric.",
    },
    {
        "city": "Dubai",
        "company_name": "Exclusive Links Real Estate Brokers",
        "type": "luxury_agency",
        "contact_name": "Zarah Evans",
        "contact_role": "Director / Partner",
        "email": "enquiry@exclusive-links.com",
        "phone": "+971 4 399 4937",
        "website": "https://www.exclusive-links.com",
        "linkedin_company": "https://www.linkedin.com/company/exclusive-links-real-estate-brokers",
        "linkedin_contact": "",
        "investment_focus": "Residential brokerage including an Elite Collection for higher-value homes; international client base",
        "geographic_focus": "Dubai, with company presence also cited in the UK, South Africa, Ireland and Brazil",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "5",
        "verification_status": "verified",
        "source_1": "https://www.exclusive-links.com/contact-exclusive-links/",
        "source_2": "https://www.linkedin.com/company/exclusive-links-real-estate-brokers",
        "notes": "Official contact page lists enquiry@exclusive-links.com and +971 4 399 4937 / +971 50 378 1097. Directors Louise Heatley and Zarah Evans are named in company materials. Mix of general brokerage and higher-end stock; included only as a Priority B introducer, not a trophy specialist. Italy coverage not evidenced.",
    },
    {
        "city": "Abu Dhabi",
        "company_name": "Eagle Hills",
        "type": "real_estate_investor",
        "contact_name": "Mohamed Alabbar",
        "contact_role": "Chairman",
        "email": "info@eaglehills.com",
        "phone": "+971 2 497 9999",
        "website": "https://eaglehills.com",
        "linkedin_company": "https://www.linkedin.com/company/eagle-hills",
        "linkedin_contact": "",
        "investment_focus": "Large-scale mixed-use and luxury hospitality real estate development, including European hotel assets",
        "geographic_focus": "UAE HQ with projects across Europe, Africa and the Middle East, including Grand Hotel Des Bains, Venice",
        "estimated_ticket": "typical developments far above €6M–€12M; unknown for single-asset acquisitions",
        "italy_interest": "yes",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://eaglehills.com/contact-us/",
        "source_2": "https://www.bloomberg.com/news/articles/2025-11-18/burj-khalifa-developer-eyes-italy-in-global-property-push",
        "notes": "Official contact page lists 9th Floor, Capital Plaza Towers, Corniche Street, Abu Dhabi; info@eaglehills.com; +971 2 497 9999. Company site lists Grand Hotel Des Bains, Venice among projects. Bloomberg reported Mohamed Alabbar separately bought Castello di Antognolla in Umbria for about $55 million as a personal investment. Institutional tickets are typically much larger than €6M–€12M; included because of demonstrated Italian luxury/hospitality activity and as a strategic introduction path, not as a likely bidder at this ticket.",
    },
    {
        "city": "Dubai",
        "company_name": "Jumeirah Group",
        "type": "hospitality_investor",
        "contact_name": "Edgar Ollé",
        "contact_role": "Global Vice President of Development, Hotels & Branded Residences",
        "email": "development@jumeirah.com",
        "phone": "+971 4 366 5000",
        "website": "https://www.jumeirah.com",
        "linkedin_company": "https://www.linkedin.com/company/jumeirah",
        "linkedin_contact": "https://www.linkedin.com/in/edgar-oll%C3%A9-33195628",
        "investment_focus": "Luxury hotel and branded-residence development and management; European coastal and city hotels",
        "geographic_focus": "Dubai-headquartered (Dubai Holding); Europe including Capri, London, Mallorca and Geneva",
        "estimated_ticket": "unknown; typical hotels larger than €6M–€12M",
        "italy_interest": "yes",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://www.jumeirah.com/en/jumeirah-group/contact-us",
        "source_2": "https://www.jumeirah.com/en/stay/italy/jumeirah-capri-palace",
        "notes": "Official corporate contact page publishes Jumeirah Development Department email development@jumeirah.com and +971 4 366 5000 / +971 4 366 5070; HQ Level 5, Building 5, Dubai Design District. Jumeirah Capri Palace in Anacapri is an operating Italian coastal luxury hotel in the portfolio. Role of Edgar Ollé is from his public LinkedIn as Global VP Development; the published development inbox is the verified email. More likely as a hospitality/operator introduction than as an acquirer of a single €6M–€12M residence.",
    },
    {
        "city": "Dubai",
        "company_name": "Al Habtoor Group",
        "type": "hospitality_investor",
        "contact_name": "Khalaf Ahmad Al Habtoor",
        "contact_role": "Founder and Chairman",
        "email": "",
        "phone": "+971 4 394 1444",
        "website": "https://www.habtoor.com",
        "linkedin_company": "https://www.linkedin.com/company/al-habtoor-group",
        "linkedin_contact": "",
        "investment_focus": "Luxury hotel ownership and real estate; European trophy hotels",
        "geographic_focus": "Dubai HQ with owned hotels in Vienna, London, Budapest and elsewhere",
        "estimated_ticket": "disclosed European hotel deals well above €6M–€12M",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "verification_status": "partially_verified",
        "source_1": "https://www.habtoor.com/en/25/contact/",
        "source_2": "https://www.hotel-online.com/news/al-habtoor-investment-acquires-starwoods-hotel-imperial-a-luxury-collection",
        "notes": "Official contact page lists Al Wasl Road, Al Safa 2, PO Box 25444, Dubai and +971 4 394 1444; no public sales/investment email on that page. Press coverage of Al Habtoor Investment's acquisition of Hotel Imperial Vienna for $78.8 million and Hilton London Wembley evidences European luxury-hotel ownership. Included as a hospitality investor with European trophy-hotel DNA; ticket size of disclosed deals is larger than this asset.",
    },
    {
        "city": "Dubai",
        "company_name": "Kerzner International",
        "type": "hospitality_investor",
        "contact_name": "",
        "contact_role": "Development",
        "email": "Development@kerzner.com",
        "phone": "+971 4 524 4000",
        "website": "https://www.kerzner.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Ultra-luxury resorts and branded residences (Atlantis, One&Only and related brands)",
        "geographic_focus": "Global corporate office in Dubai; luxury resort destinations worldwide",
        "estimated_ticket": "unknown; typical resorts far above €6M–€12M",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "verification_status": "verified",
        "source_1": "https://www.kerzner.com/contact-us",
        "source_2": "https://www.kerzner.com/contact-us",
        "notes": "Official contact page lists Global Corporate Office at One Central, The Offices Building 2, 9th Floor, World Trade Centre, Dubai; +971 4 524 4000; Development@kerzner.com. Relevant as a luxury coastal/resort operator that might consider a southern-Italy hospitality conversion, not as a likely buyer of a single villa at this ticket. Named development principal not published on the contact page.",
    },
    {
        "city": "Dubai",
        "company_name": "JA Resorts & Hotels",
        "type": "hospitality_investor",
        "contact_name": "Ralph Porciani",
        "contact_role": "Chief Executive Officer",
        "email": "",
        "phone": "+971 4 814 5555",
        "website": "https://www.jaresortshotels.com",
        "linkedin_company": "https://www.linkedin.com/company/jaresorts",
        "linkedin_contact": "",
        "investment_focus": "Luxury and heritage hotels and resorts; recent European hotel acquisitions",
        "geographic_focus": "Dubai-headquartered (Dutco Group); UAE, Maldives and UK (Scotland) hotels",
        "estimated_ticket": "unknown; UK hotel acquisitions larger than €6M–€12M",
        "italy_interest": "unclear",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "verification_status": "partially_verified",
        "source_1": "https://www.travelandtourworld.com/news/article/ja-resorts-hotels-expands-into-uk-with-mar-hall-golf-spa-resort-and-the-bruntsfield-marking-major-milestone-in-global-growth/",
        "source_2": "https://source.jaresortshotels.com/contact-us",
        "notes": "JA Resorts, part of Dutco Group, acquired Mar Hall Golf & Spa Resort and The Bruntsfield in Scotland, evidencing a strategy of buying European heritage hospitality assets. Published hotel emails are reservations-only, so corporate investment email is empty. Phone is the published Dubai hotel/corporate line +971 4 814 5555. CEO Ralph Porciani is named in acquisition coverage. Fit is as a hospitality acquirer of characterful European assets, not a residential broker.",
    },
    {
        "city": "Dubai",
        "company_name": "FIVE Holdings",
        "type": "hospitality_investor",
        "contact_name": "Kabir Mulchandani",
        "contact_role": "Founder and Chairman",
        "email": "investor.relations@fiveglobalholdings.com",
        "phone": "+971 4 423 2879",
        "website": "https://five-holdings.com",
        "linkedin_company": "https://www.linkedin.com/company/fiveglobalholdings",
        "linkedin_contact": "",
        "investment_focus": "Vertically integrated luxury hotels, branded entertainment hospitality and related real estate",
        "geographic_focus": "Dubai hotels plus FIVE Zurich and Pacha/Destino hospitality assets in Ibiza, Spain",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "verification_status": "verified",
        "source_1": "https://five-holdings.com/home/",
        "source_2": "https://www.five-holdings.com/wp-content/uploads/2024/04/FIVE-reports-69-revenue-growth-and-55-EBITDA-growth-in-FY-2023.pdf",
        "notes": "Official site confirms Dubai luxury hotels and FIVE Zurich. FY2023 results PDF publishes investor.relations@fiveglobalholdings.com and describes the Pacha Group acquisition in Spain (Ibiza hotels/nightlife). Company LinkedIn lists +971 4 423 2879 and Boulevard Plaza Tower 1 office. European coastal leisure DNA is relevant to an Amalfi-coast hospitality/leisure reading of the asset; typical owned hotels are larger than €6M–€12M.",
    },
    {
        "city": "Dubai",
        "company_name": "Arzan Investment Management",
        "type": "hospitality_investor",
        "contact_name": "Hubert Viriot",
        "contact_role": "Partner, Hospitality",
        "email": "",
        "phone": "",
        "website": "https://www.arzanim.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Hospitality, residential and special-situations real estate; GCC hospitality fund platform; EMEA and US opportunistic deals",
        "geographic_focus": "DIFC HQ with London and New York offices; European hospitality sourcing; Portugal hotel affiliates",
        "estimated_ticket": "disclosed Dubai hotel deal $325M; typical tickets larger than €6M–€12M",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "verification_status": "partially_verified",
        "source_1": "https://www.arzanim.com/",
        "source_2": "https://www.zawya.com/en/press-release/companies-news/arzan-investment-management-enters-binding-sale-and-purchase-agreement-for-fairmont-palm-dubai-da4tn5dq",
        "notes": "Official site: 601, Gate Village 8, DIFC, Dubai. Hubert Viriot leads hospitality strategy; Viktor Persson is Director, Hospitality focused on GCC and European hospitality opportunities; Carlos Leal previously ran Pine Cliffs Resort (Algarve) and Sheraton Cascais. Zawya: AIM agreed to acquire Fairmont The Palm for $325M. No public email/phone on the contact page. Included as a DIFC hospitality investor with an explicit European hospitality mandate; disclosed tickets are larger than this asset.",
    },
    {
        "city": "Dubai",
        "company_name": "SHUAA Capital",
        "type": "real_estate_investor",
        "contact_name": "",
        "contact_role": "",
        "email": "info@shuaa.com",
        "phone": "+971 4 330 3600",
        "website": "https://www.shuaa.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Real estate investment, asset management and hospitality funds; high-end residential platforms including Northacre in the UK",
        "geographic_focus": "UAE, UK and Eastern Europe real estate; Saudi hospitality funds",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "verification_status": "verified",
        "source_1": "https://www.shuaa.com/contact-us",
        "source_2": "https://www.shuaa.com/what-we-do/asset-management/real-estate/real-estate-fund-management",
        "notes": "Official contact page: The H Hotel Dubai, Office Tower 15th Floor, Office 1502; info@shuaa.com; +971 4 330 3600. Annual-report and platform pages describe real-estate activity including high-end residential (Northacre, UK) and Eastern Europe, plus CMA-regulated Saudi hospitality funds. Named real-estate MD not published on the contact page. Italy not specifically evidenced; included as a UAE platform with European luxury-residential and hospitality capability.",
    },
    {
        "city": "Dubai",
        "company_name": "MAG Group Holding",
        "type": "real_estate_investor",
        "contact_name": "Talal Moafaq Al Gaddah",
        "contact_role": "Senior Executive Vice Chairman; CEO, MAG Property Development",
        "email": "info@mag.ae",
        "phone": "+971 4 325 4660",
        "website": "https://www.mag.ae",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Luxury wellness real estate and hospitality (Keturah / Ritz-Carlton Residences) plus European residential development",
        "geographic_focus": "Dubai DIFC HQ; Stabio Garden Living by Keturah in Switzerland, near the Italian border",
        "estimated_ticket": "disclosed Swiss project about $213M; unknown for single-asset acquisitions",
        "italy_interest": "unclear",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "verification_status": "verified",
        "source_1": "https://www.mag.ae/wp-content/uploads/2025/08/MAG-Group-Holding-Company-Profile.pdf",
        "source_2": "https://www.investmentmonitor.ai/news/mag-to-open-new-residential-project-in-switzerland/",
        "notes": "Official group profile PDF lists MAG Group Holding, 26th & 27th Floor, South Tower, Emirates Financial Towers, DIFC; info@mag.ae; +971 4 325 4660. Keturah is the luxury wellness/hospitality brand, including Ritz-Carlton Residences Dubai. Investment Monitor reported a $212.62m Stabio, Switzerland residential project. European activity is Switzerland rather than Italy; included as a UAE luxury/hospitality developer with a European beachhead.",
    },
    {
        "city": "Abu Dhabi",
        "company_name": "Rotana Hotel Management Corporation",
        "type": "hospitality_investor",
        "contact_name": "Makram El Zyr",
        "contact_role": "Corporate Vice President, Development",
        "email": "",
        "phone": "+971 2 699 4444",
        "website": "https://development.rotana.com/en/",
        "linkedin_company": "https://www.linkedin.com/company/rotana",
        "linkedin_contact": "",
        "investment_focus": "Hotel management, franchising and development partnerships across the Middle East, Africa, Eastern Europe and Turkey",
        "geographic_focus": "Abu Dhabi HQ; 22 countries including Eastern Europe and Turkey",
        "estimated_ticket": "unknown",
        "italy_interest": "no",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "5",
        "verification_status": "partially_verified",
        "source_1": "https://development.rotana.com/en/",
        "source_2": "https://about.rotana.com/en/ourcompany/corporateexecutives",
        "notes": "Rotana's development portal and corporate executives page name Makram El Zyr as Corporate Vice President, Development. Company LinkedIn lists Abu Dhabi HQ and +971 2 699 4444. No public development email was confirmed on the fetched pages. Geographic focus is MENA/Eastern Europe/Turkey rather than Italy; included only as a Priority B hospitality operator that might consider a southern-Italy management contract.",
    },
    {
        "city": "Ras Al Khaimah",
        "company_name": "RAK Hospitality Holding",
        "type": "hospitality_investor",
        "contact_name": "",
        "contact_role": "",
        "email": "",
        "phone": "+971 7 203 6000",
        "website": "https://rakhospitalityholding.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Hotel ownership and hospitality asset management in Ras Al Khaimah (Ritz-Carlton Al Wadi, Rixos, Hilton, Pullman and others)",
        "geographic_focus": "Ras Al Khaimah / Al Marjan Island",
        "estimated_ticket": "unknown",
        "italy_interest": "no",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "5",
        "verification_status": "partially_verified",
        "source_1": "https://rakhospitalityholding.com/contact-us/",
        "source_2": "https://rakhospitalityholding.com/contact-us/",
        "notes": "Official contact page invites general and investment enquiries at +971 7 203 6000, PO Box 86000, Ras Al Khaimah; no public email published. Portfolio is RAK-centric luxury/upscale hotels. Included as a UAE hospitality owner that takes investment enquiries; no Italy evidence, so Priority B only.",
    },
    {
        "city": "Dubai",
        "company_name": "Handle Private Capital",
        "type": "private_capital",
        "contact_name": "",
        "contact_role": "",
        "email": "info@handle.ae",
        "phone": "+971 4 313 2435",
        "website": "https://handle.ae",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Execution advisory for family offices and private capital, including UAE–EU family-office investment structures",
        "geographic_focus": "Dubai (DIFC/onshore) with EU holding jurisdictions such as Luxembourg, Ireland and the Netherlands",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "verification_status": "verified",
        "source_1": "https://handle.ae/private-capital/contact-us/",
        "source_2": "https://handle.ae/private-capital/investor-governance/family-office-mandates/uae-eu-family-office-investments/",
        "notes": "Official contact page: Standard Chartered Tower, Emaar Square, Downtown Dubai; info@handle.ae; +971 4 313 2435 / +971 50 504 3000. Separate page describes structuring and executing UAE–EU family-office investments. Not a broker or principal buyer; included as a private-capital introducer to UAE family offices allocating into European assets.",
    },
    {
        "city": "Dubai",
        "company_name": "EuroGulf Partners",
        "type": "other_relevant",
        "contact_name": "",
        "contact_role": "",
        "email": "care@eurogulfpartners.com",
        "phone": "+971 50 865 8585",
        "website": "https://eurogulfpartners.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Curated premium real estate and residency-linked investments in the UAE and Portugal",
        "geographic_focus": "Dubai and Lisbon/Porto; Portugal coastal estates (Lisbon Riviera, Comporta, Algarve)",
        "estimated_ticket": "UAE selections described from AED 2M+",
        "italy_interest": "no",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "5",
        "verification_status": "verified",
        "source_1": "https://eurogulfpartners.com/contact/",
        "source_2": "https://eurogulfpartners.com/services/real-estate/",
        "notes": "Official contact page lists Al Fattan Business Centre, JBR, Dubai; +971 50 865 8585; care@eurogulfpartners.com. Real-estate page describes off-market premium property in the UAE and Portugal. No Italy mandate; included as a Priority B UAE–Europe luxury-property advisor that already works coastal European estates.",
    },
    {
        "city": "Dubai",
        "company_name": "JLL Hotels & Hospitality MEA",
        "type": "other_relevant",
        "contact_name": "Amr Nady",
        "contact_role": "Head of Hotels & Hospitality MEA; Managing Director, Global Hotel Desk",
        "email": "",
        "phone": "",
        "website": "https://www.jll.com",
        "linkedin_company": "https://www.linkedin.com/company/jll-mena",
        "linkedin_contact": "https://www.linkedin.com/in/amr-nady-0b1b15a",
        "investment_focus": "Hotel investment sales, advisory and cross-border hospitality transactions for Middle Eastern capital",
        "geographic_focus": "Dubai / MEA platform advising regional investors on international hotel strategies, including Europe",
        "estimated_ticket": "unknown; recent advised deals much larger than €6M–€12M",
        "italy_interest": "unclear",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "verification_status": "partially_verified",
        "source_1": "https://www.linkedin.com/in/amr-nady-0b1b15a",
        "source_2": "https://www.linkedin.com/company/jll-mena",
        "notes": "Amr Nady's public profile states he advises Middle Eastern investors on international hotel investment strategies via JLL's Global Hotel Desk and previously worked on trophy-hotel sales in the UK and Northern Europe. JLL MENA HQ is listed as Emaar Square, Building 1, Office 403, Dubai. No public JLL email was confirmed, so email is empty. Relevant as an introducer to UAE hospitality capital, not as a residential agency.",
    },
    {
        "city": "Dubai",
        "company_name": "CBRE MENA Hotels & Tourism",
        "type": "other_relevant",
        "contact_name": "Ali Manzoor",
        "contact_role": "Head of Hospitality / Senior Director, Hotels & Tourism",
        "email": "",
        "phone": "",
        "website": "https://www.cbre.ae/services/property-types/hotels",
        "linkedin_company": "https://www.linkedin.com/company/cbre-mena",
        "linkedin_contact": "https://www.linkedin.com/in/ali-manzoor-88546562",
        "investment_focus": "Hotel investment advisory, valuations, operator selection and cross-border hospitality assignments",
        "geographic_focus": "UAE and MENA, with a regional team covering cross-border hospitality work",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "verification_status": "partially_verified",
        "source_1": "https://www.cbre.ae/services/property-types/hotels",
        "source_2": "https://www.linkedin.com/in/ali-manzoor-88546562",
        "notes": "Official CBRE UAE hotels page names Ali Manzoor, Ben Parkins and Christopher Robson (Director, Hotels & Tourism) and describes investment advisory for hotel properties plus cross-border MENA assignments. No public email/phone on that page. Included as a hospitality-investment introducer for a mixed-use/leisure reading of the Italian asset.",
    },
    {
        "city": "Dubai",
        "company_name": "Colliers MENA Hospitality & Tourism",
        "type": "other_relevant",
        "contact_name": "Nicolas Nasra",
        "contact_role": "Director - Hospitality & Tourism Advisory; Head of Hotel Advisory",
        "email": "",
        "phone": "+971 55 769 9797",
        "website": "https://www.colliers.com/en-ae/services/hospitality-services",
        "linkedin_company": "https://www.linkedin.com/company/colliers",
        "linkedin_contact": "",
        "investment_focus": "Hospitality, leisure and tourism advisory including transaction support, operator search and coastal/wellness destinations",
        "geographic_focus": "UAE and wider MENA; case work includes luxury beachfront and wellness destinations",
        "estimated_ticket": "unknown",
        "italy_interest": "unclear",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "6",
        "verification_status": "partially_verified",
        "source_1": "https://www.colliers.com/en-ae/services/hospitality-services",
        "source_2": "https://www.colliers.com/en-ae/united-arab-emirates/cities/dubai",
        "notes": "Official hospitality page names Nicolas Nasra as Head of Hotel Advisory at Colliers MENA, covering hotels, resorts, branded residences, wellness, marinas and leisure, with buy- and sell-side transaction advisory. Mobile +971 55 769 9797 is published on that page. No email published. Relevant if the Amalfi asset is positioned as boutique hospitality/leisure rather than a pure residence.",
    },
]


def main() -> None:
    out = Path("/workspace/data/real-estate-prospects/united-arab-emirates.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for row in ROWS:
            full = {h: row.get(h, "") for h in HEADERS}
            full["country"] = COUNTRY
            full["last_verified"] = LAST_VERIFIED
            writer.writerow(full)
    print(f"Wrote {len(ROWS)} rows to {out}")


if __name__ == "__main__":
    main()
