#!/usr/bin/env python3
"""Generate the Australia luxury buyer/capital prospect CSV from verified research notes."""

from __future__ import annotations

import csv
from pathlib import Path

HEADERS = [
    "country",
    "city",
    "company_name",
    "type",
    "contact_name",
    "contact_role",
    "email",
    "phone",
    "website",
    "linkedin_company",
    "linkedin_contact",
    "investment_focus",
    "geographic_focus",
    "buyer_origin_relevance",
    "italy_interest",
    "amalfi_coast_relevance",
    "estimated_ticket",
    "luxury_real_estate",
    "hospitality_interest",
    "fit_score",
    "priority",
    "verification_status",
    "source_1",
    "source_2",
    "notes",
    "last_verified",
]

LAST_VERIFIED = "2026-08-27"
COUNTRY = "Australia"

ROWS = [
    {
        "city": "Melbourne",
        "company_name": "Knight Frank Australia Private Office",
        "type": "private_office",
        "contact_name": "Ari Petrovs",
        "contact_role": "Partner, Head of Private Office, Australia",
        "email": "",
        "phone": "+61 413 778 424",
        "website": "https://www.knightfrank.com.au/private-office",
        "linkedin_company": "https://www.linkedin.com/company/knight-frank-australia",
        "linkedin_contact": "",
        "investment_focus": "UHNW/HNWI and family-office real-estate advisory across residential, commercial, rural and capital markets; global acquisition, sale and investment strategy",
        "geographic_focus": "Australia Private Office connected to Knight Frank Private Offices in London, Dubai, Hong Kong, Singapore, New York and Jeddah, plus Knight Frank associate agencies in Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.knightfrank.com.au/private-office",
        "source_2": "https://www.knightfrank.com.au/blog/2025/12/04/knight-frank-launches-a-private-office-in-australia",
        "notes": "Official Australian Private Office page and December 2025 Knight Frank announcement name Ari Petrovs as Partner, Head of Private Office, Australia, working exclusively with UHNWIs, HNWIs, family offices and their advisers on acquisition, sales and investment strategy across every real-estate sector. The Australian office is one of seven dedicated Private Office teams and is explicitly designed to connect Australian private clients to Knight Frank specialists across geographies, including through the McGrath and Bayleys partnerships. Knight Frank publishes an Italian Homes capability and has expanded Italian associate coverage (including Rome and Cortina in 2026) alongside a London Italian desk, so Italy access is via the global network rather than a published Australia-to-Amalfi mandate. Direct email is not published on the people page; mobile +61 413 778 424 is from the Knight Frank launch materials republished by Commo. Do not use marketing@au.knightfrank.com for this mandate.",
    },
    {
        "city": "Sydney",
        "company_name": "McGrath Estate Agents — International and Private Clients",
        "type": "luxury_agency",
        "contact_name": "Adam Ross",
        "contact_role": "Head of International and Private Clients",
        "email": "adamross@mcgrath.com.au",
        "phone": "+61 409 663 051",
        "website": "https://www.mcgrath.com.au/agents/adam-ross-a1VJ1000000bvr7MAA",
        "linkedin_company": "https://www.linkedin.com/company/mcgrath-estate-agents",
        "linkedin_contact": "https://www.linkedin.com/in/adam-ross-3510841a",
        "investment_focus": "Super-prime residential above about $10 million; UHNW, developer and family-office private clients; international referrals via the Knight Frank/McGrath partnership",
        "geographic_focus": "Australia, with published international private-client work including premium developments such as Crown Residences One Barangaroo and The Towers at Waldorf Astoria New York",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "typically above A$10 million for the private-client desk (compatible with €6M–€12M)",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.mcgrath.com.au/agents/adam-ross-a1VJ1000000bvr7MAA",
        "source_2": "https://www.knightfrank.com.au/blog/2025/12/04/knight-frank-launches-a-private-office-in-australia",
        "notes": "Official McGrath agent profile identifies Adam Ross as the firm's super-prime specialist handling assets above the $10 million segment, with more than $1 billion in career sales, and states he serves UHNW individuals, developers and family offices with a wide local and overseas network. The same Knight Frank Private Office launch names him as McGrath Head of International and Private Clients and a Private Office ambassador, so this row is the McGrath-side access to Australian UHNW buyers rather than a duplicate of the Knight Frank Private Office desk. Email adamross@mcgrath.com.au and mobile 0409 663 051 are published on the official agent profile. Italy/Amalfi coverage is via the Knight Frank partnership, not a published McGrath Italy mandate. Distinct from generic McGrath suburban brokerage.",
    },
    {
        "city": "Sydney",
        "company_name": "Private Property Global",
        "type": "luxury_agency",
        "contact_name": "Ken Jacobs",
        "contact_role": "Director — Asia Pacific & Middle East",
        "email": "",
        "phone": "+61 407 190 152",
        "website": "https://www.forbesglobalproperties.com/members/private-property-global",
        "linkedin_company": "https://www.linkedin.com/company/ppgforbesglobalproperties",
        "linkedin_contact": "https://www.linkedin.com/in/ken-jacobs-17203b245",
        "investment_focus": "Trophy homes and houses of historical or architectural significance above A$5 million, without geographical boundaries; off-market UHNW advisory through Forbes Global Properties",
        "geographic_focus": "Sydney, Melbourne and Gold Coast trophy stock, with Forbes Global Properties international brokerage relationships",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "specialises above A$5 million; recent advertised trophy stock includes A$20 million–A$74 million harbour and estate listings",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.forbesglobalproperties.com/members/private-property-global",
        "source_2": "https://www.forbesglobalproperties.com/agents/ken-jacobs-2",
        "notes": "Forbes Global Properties member page states Private Property Global is the only Australian-based residential agency specialising in property above $5 million without geographical boundaries, with a 20-year record at the top of the Australian prestige market and an exclusive UHNW database. Ken Jacobs is listed as Director — Asia Pacific & Middle East with office mobile +61 407 190 152. Melbourne office is published by REIV at Goldfields House, Level 10, 627 Chapel Street, South Yarra. Direct sales email is not published on the FGP member or agent pages, so email is left empty. Fit is as an Australian trophy-home introducer to UHNW principals who already buy at or above the Amalfi ticket; Italy is via the FGP global network, not a published Amalfi mandate.",
    },
    {
        "city": "Sydney",
        "company_name": "Christie's International Real Estate Sydney",
        "type": "luxury_agency",
        "contact_name": "Darren Curtis",
        "contact_role": "Principal",
        "email": "darren@ciresydney.com.au",
        "phone": "+61 2 9328 1422",
        "website": "https://www.ciresydney.com.au/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Top-end luxury residential without geographical boundaries; UHNW vendors and purchasers of mansions, waterfronts, city penthouses and rural estates",
        "geographic_focus": "New South Wales, with the Christie's International Real Estate affiliate network spanning nearly 50 countries including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown; principal works the top end of any luxury market",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.ciresydney.com.au/team/697774",
        "source_2": "https://www.globenewswire.com/news-release/2023/05/24/2675331/0/en/Christie-s-International-Real-Estate-Eyes-Growth-in-Australia-Behind-Leading-Luxury-Brokers.html",
        "notes": "Official team page names Darren Curtis as Principal; office 02 9328 1422; mobile 0406 761 840; darren@ciresydney.com.au. Bio states he built his foundations in Notting Hill and Holland Park, London, has been with Christie's International Real Estate Sydney since 2006, and works without geographical boundaries at the top end of any luxury market for Australia's most capable vendors and purchasers. May 2023 Christie's release confirms he owns the Sydney affiliate (formerly Prestige Homes of Australia) and was expanding into Queensland. Italy is a published Christie's International Real Estate destination market; this row is the Australian buyer-origin desk, not the Italian affiliate. Distinct from the Victoria and WA/SA Christie's affiliates.",
    },
    {
        "city": "Melbourne",
        "company_name": "Christie's International Real Estate Victoria",
        "type": "luxury_agency",
        "contact_name": "Sean Cussell",
        "contact_role": "Principal",
        "email": "sean@cirevictoria.com.au",
        "phone": "+61 3 9867 6666",
        "website": "https://www.christiesrealestate.com/real-estate-offices/melbourne/328/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "High-end residential sales including municipal record prices and estates; international Christie's affiliate referrals",
        "geographic_focus": "Greater Melbourne and Victorian prestige markets, with Christie's International Real Estate coverage including Europe",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "disclosed Victorian records include a A$30 million bayside apartment",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.christiesrealestate.com/real-estate-offices/melbourne/328/",
        "source_2": "https://www.prestigehomes.com.au/staff/sean-cussell/",
        "notes": "Official Christie's International Real Estate Melbourne office page lists 2 Daly Street, South Yarra, +61 425 787 979, and names Sean Cussell as Team Principal with current price records in five Victorian municipalities including a A$30 million bayside apartment. Prestige Homes staff page publishes sean@cirevictoria.com.au, 03 9867 6666 and mobile 0425 787 979, and quotes Cussell on selling prestigious property 'whether in Europe, Asia or in America'. Separate affiliate from the Sydney Christie's office. Italy interest is via the Christie's network and his published Europe comment, not a dedicated Amalfi listing desk.",
    },
    {
        "city": "Sydney",
        "company_name": "Sydney Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Michael Pallier",
        "contact_role": "Managing Director",
        "email": "michael.pallier@sydneysothebysrealty.com",
        "phone": "+61 417 371 522",
        "website": "https://sydneysothebysrealty.com/agents",
        "linkedin_company": "https://www.linkedin.com/company/sydney-sotheby's-international-realty",
        "linkedin_contact": "https://www.linkedin.com/in/michael-pallier-1b818375",
        "investment_focus": "Extraordinary and luxury lifestyle homes; global Sotheby's International Realty private-client referrals",
        "geographic_focus": "Sydney harbour, eastern suburbs and associated NSW offices including Byron Bay, with the global SIR network including Italy Sotheby's offices covering the Amalfi Coast and Capri",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://sydneysothebysrealty.com/agents",
        "source_2": "https://www.italy-sothebysrealty.com/en/about-us/",
        "notes": "Official agents page lists Michael Pallier as Managing Director with 0417 371 522 and michael.pallier@sydneysothebysrealty.com. The firm describes itself as entrusted with extraordinary Sydney and global-market homes as part of Sotheby's International Realty. Italy Sotheby's International Realty separately publishes 15 Italian offices and destination coverage including Campania, the Amalfi Coast and Capri, so Australian-origin buyer introductions are plausible through the SIR referral network rather than because this row is an Italian agency. Assistant emails on the same page (alina.setter@sydneysir.com; melanie@sydneysir.com) are support only. Distinct from Melbourne, Queensland and Western Australia SIR affiliates.",
    },
    {
        "city": "Melbourne",
        "company_name": "Melbourne Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Mitch Armstrong",
        "contact_role": "CEO & Head of Projects",
        "email": "mitch.armstrong@msir.com.au",
        "phone": "+61 3 9008 4223",
        "website": "https://melbournesothebysrealty.com/office/headquarters-melbourne",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Luxury residential sales and projects across Melbourne, Bayside and the Mornington Peninsula; global SIR referrals",
        "geographic_focus": "Melbourne and Mornington Peninsula, connected to Italy Sotheby's International Realty and the wider SIR network",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://melbournesothebysrealty.com/office/headquarters-melbourne",
        "source_2": "https://www.italy-sothebysrealty.com/en/about-us/",
        "notes": "Official Headquarters Melbourne page lists 168 Williams Road, Prahran VIC 3181; corporate@msir.com.au; (+61) 3 9008 4223; and names Mitch Armstrong as CEO & Head of Projects with mitch.armstrong@msir.com.au. Separate Stonnington principals Antoinette Nido and Max Ruttner are published on the Stonnington office page; this row uses the CEO as the best firm-level contact for international UHNW introductions. Italy/Amalfi relevance is the SIR network (Italy SIR publishes Amalfi Coast and Capri coverage), not a Melbourne-published Amalfi mandate. Distinct from Sydney Sotheby's International Realty.",
    },
    {
        "city": "Brisbane",
        "company_name": "Queensland Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Paul Arthur",
        "contact_role": "Founder & CEO",
        "email": "paul.arthur@qldsir.com",
        "phone": "+61 466 776 700",
        "website": "https://queenslandsothebysrealty.com/our-team",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Luxury and lifestyle residential across Queensland coastal and hinterland markets; global SIR referrals",
        "geographic_focus": "Brisbane, Gold Coast, Noosa, Whitsundays, Port Douglas and other Queensland offices, with SIR network access including Italy",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://queenslandsothebysrealty.com/our-team",
        "source_2": "https://queenslandsothebysrealty.com/why-choose-us",
        "notes": "Official team page names Paul Arthur as Founder & CEO with +61 466 776 700 and paul.arthur@qldsir.com. The firm markets Queensland's remarkable homes through the Sotheby's International Realty global network. Score is below the Sydney/Melbourne SIR rows because the published book is more Queensland lifestyle/coastal than documented UHNW international-acquisition advisory, but Queensland UHNW and the SIR Italy network remain a credible buyer-origin path. Distinct SIR affiliate from Sydney, Melbourne and WA.",
    },
    {
        "city": "Perth",
        "company_name": "Western Australia Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Brian Smith",
        "contact_role": "Director",
        "email": "brian.smith@wasothebysrealty.com.au",
        "phone": "+61 477 188 856",
        "website": "https://wasothebysrealty.com.au/our-offices",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Luxury residential for local and international clients in Western Australia; SIR global referrals",
        "geographic_focus": "Perth and Western Australia, connected to the global Sotheby's International Realty network including Italy",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://wasothebysrealty.com.au/our-offices",
        "source_2": "https://www.italy-sothebysrealty.com/en/about-us/",
        "notes": "Official offices page lists Unit 1, 100 Terrace Road, Perth WA 6000 and a Margaret River office; 08 6317 9970; admin@wasothebysrealty.com.au. Brian Smith is a published Perth contact with brian.smith@wasothebysrealty.com.au and +61 477 188 856. The firm states it serves local and international clients. Italy relevance is the SIR network (Italy Sotheby's publishes Amalfi Coast and Capri coverage). Distinct from Christie's International Real Estate WA/SA.",
    },
    {
        "city": "Perth",
        "company_name": "Christie's International Real Estate Western Australia and South Australia",
        "type": "luxury_agency",
        "contact_name": "Shelley Scorer",
        "contact_role": "Chief Executive Officer",
        "email": "",
        "phone": "",
        "website": "https://www.christiesrealestate.com/real-estate-agents/shelley-scorer/30924/",
        "linkedin_company": "",
        "linkedin_contact": "https://www.linkedin.com/in/shelley-scorer-493a38333",
        "investment_focus": "Luxury residential in Perth, Adelaide and surrounding countryside including vineyard country; Christie's global affiliate network",
        "geographic_focus": "Western Australia and South Australia, with Christie's International Real Estate coverage including Italy and other European luxury markets",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.globenewswire.com/news-release/2024/10/29/2970438/0/en/Christie-s-International-Real-Estate-Launches-in-Western-Australia-and-South-Australia.html",
        "source_2": "https://www.christiesrealestate.com/real-estate-agents/shelley-scorer/30924/",
        "notes": "October 2024 Christie's International Real Estate release names Shelley Scorer as leading the new Western Australia and South Australia affiliate, joining existing Sydney and Victoria affiliates. LinkedIn identifies her as CEO of Christie's International Real Estate WA SA. Direct email and phone were not published in the launch release (media contact on that release is a US Christie's number, not used here). Buyer-origin fit is Perth/Adelaide UHNW via the Christie's network; the launch text emphasises inbound international buyers into WA/SA as well as outbound network access, so score is capped below the longer-established Sydney/Victoria affiliates.",
    },
    {
        "city": "Perth",
        "company_name": "Fine & Country Australia",
        "type": "luxury_agency",
        "contact_name": "Amy Gohil",
        "contact_role": "Licensee / Director, Fine & Country Perth",
        "email": "perth@fineandcountry.com",
        "phone": "+61 451 248 101",
        "website": "https://www.fineandcountry.au/perth-real-estate-agents/contact",
        "linkedin_company": "https://www.linkedin.com/company/fine-&-country",
        "linkedin_contact": "",
        "investment_focus": "International luxury residential brokerage and referral; Australian prestige homes marketed through the Fine & Country global network",
        "geographic_focus": "Perth office with advertised Australian prestige listings including Sydney harbour-side stock, plus Fine & Country offices in Italy and 300+ locations worldwide",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "advertised Australian listings include A$8 million–A$12 million prestige homes",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.fineandcountry.au/perth-real-estate-agents/contact",
        "source_2": "https://www.fineandcountry.it/en/team/silvio-gallo",
        "notes": "Official Perth contact page publishes perth@fineandcountry.com, +61 451 248 101, and names Amy Gohil as Licensee/Director and Vivek Gohil as Director. Fine & Country describes Perth as Australia's first truly international residential brokerage with a global referral programme. Fine & Country Italy (Milan) publicly covers Lombardy lakes and states the vision extends to the Neapolitan Coast and Italian islands, supporting a real Italy referral path. Personal emails for the Gohils are not published; the official Perth inbox is used. This is the Australian office serving Australian clients, not a redirect to the Milan affiliate.",
    },
    {
        "city": "Melbourne",
        "company_name": "Kay & Burton",
        "type": "luxury_agency",
        "contact_name": "Ross Savas",
        "contact_role": "Managing Director",
        "email": "rsavas@kayburton.com.au",
        "phone": "+61 418 322 994",
        "website": "https://www.kayburton.com.au/702347/ross-savas",
        "linkedin_company": "https://www.linkedin.com/company/kay-&-burton",
        "linkedin_contact": "https://www.linkedin.com/in/rosssavas",
        "investment_focus": "Melbourne and Mornington Peninsula prestige residential for private clients, families and institutions; international division focused mainly on inbound demand for Australian property",
        "geographic_focus": "Melbourne and the Mornington Peninsula, with an international division connected across 50+ countries and company presence also cited in the UK, France, US and Malaysia",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown; among Australia's leading prestige agencies by headline home-sale results",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.kayburton.com.au/international-services/",
        "source_2": "https://www.linkedin.com/in/rosssavas",
        "notes": "Kay & Burton is a 1938 Melbourne prestige house and trusted advisor to private clients and families. Ross Savas is Managing Director; his public LinkedIn publishes rsavas@kayburton.com.au and +61 418 322 994 and states he consults a private-client database locally and globally. The International division under Jamie Mi is explicitly about meeting growing international demand for Australian property (inbound), so it is not treated as an Italy-buying desk. Include because Melbourne UHNW relationships are real and the firm has published UK/France presence; do not treat the international desk as proof of Amalfi buyer representation. Italy interest remains unclear.",
    },
    {
        "city": "Melbourne",
        "company_name": "Marshall White",
        "type": "luxury_agency",
        "contact_name": "John Bongiorno",
        "contact_role": "Group Sales Director",
        "email": "john.bongiorno@marshallwhite.com.au",
        "phone": "+61 418 328 056",
        "website": "https://www.marshallwhite.com.au/our-story",
        "linkedin_company": "https://www.linkedin.com/company/marshall-white-&-co",
        "linkedin_contact": "",
        "investment_focus": "Premium and prestige residential sales, off-market private-client work and auctions across Melbourne's inner east, Bayside and Mornington Peninsula",
        "geographic_focus": "Metropolitan Melbourne, Bayside and Mornington Peninsula; international buyers are mentioned as a client type, but the published business is domestic prestige",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "no",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "unknown; long-run leader in Melbourne prestige including Toorak, Brighton and Sorrento",
        "luxury_real_estate": "yes",
        "hospitality_interest": "no",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.marshallwhite.com.au/our-story",
        "source_2": "https://www.marshallwhite.com.au/office/boroondara",
        "notes": "Included only as a Melbourne UHNW introducer, not as an international Italy specialist. Official story page positions Marshall White as Melbourne's leading privately owned prestige agency since 1964, trusted by generations of Melbourne families, private investors and international buyers, with off-market private-client channels. John Bongiorno is named Group Sales Director on office pages with john.bongiorno@marshallwhite.com.au and 0418 328 056; general inbox contactus@marshallwhite.com.au and 03 9822 9999. No demonstrated Italy or European acquisition desk; score capped accordingly. General firm email is not used because the director email is published.",
    },
    {
        "city": "Brisbane",
        "company_name": "Propert-it",
        "type": "international_property_advisor",
        "contact_name": "Fabrizio Fiorino",
        "contact_role": "Director",
        "email": "info@propert-it.com.au",
        "phone": "",
        "website": "https://propert-it.com.au/",
        "linkedin_company": "https://www.linkedin.com/company/propert-it",
        "linkedin_contact": "https://www.linkedin.com/in/fabrizio-fiorino-325a8a61",
        "investment_focus": "Buyer-side sourcing, title investigation and negotiation assistance for Italian residential property, including villas, coastal homes and historic apartments",
        "geographic_focus": "Brisbane-based advisory covering Italy including Tuscany, the Amalfi Coast and Rome, serving Australian clients buying in Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "strong",
        "estimated_ticket": "unknown; public materials say they assist 'for any pocket', so €6M–€12M compatibility is unproven",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://propert-it.com.au/about-us/",
        "source_2": "https://propert-it.com.au/contact/",
        "notes": "Rare Australian-based Italy buyer representative. Official site explicitly offers Tuscany villas, Amalfi Coast coastal gems and Roman palazzi, with sourcing, title investigation and negotiation. About page names Fabrizio Fiorino, an Italian-registered lawyer now in Australia, as Director. Contact page publishes info@propert-it.com.au and Brisbane, QLD. LinkedIn company page is a one-person 2023 boutique. Strong Italy/Amalfi relevance and genuine Australian-origin buyers; score is not Priority A because public language includes mid-market/'any pocket' purchase assistance and there is no published evidence of €6M–€12M trophy execution. Do not use fabrizio@fiorinolaw.com.au here; that domain was not verified on the Propert-it site.",
    },
    {
        "city": "Brisbane",
        "company_name": "North South Real Estate",
        "type": "international_property_advisor",
        "contact_name": "Nik Seirlis",
        "contact_role": "Private advisor / principal (with Aika Seirlis)",
        "email": "",
        "phone": "+61 7 3229 5000",
        "website": "https://www.nsre.com.au/international-real-estate-investment-opportunities",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Cross-border prestige acquisitions for Australian and international buyers, currently featuring Spain (including La Zagaleta) and Dubai luxury/new developments; prestige sales typically A$1 million–A$45 million",
        "geographic_focus": "Australia-based (Brisbane/Gold Coast) advising buyers into Spain, Dubai and other international markets; also domestic prestige",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "no",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "prestige range published as A$1 million–A$45 million",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.nsre.com.au/international-real-estate-investment-opportunities",
        "source_2": "https://www.nsre.com.au/contact",
        "notes": "Australia-based cross-border advisor whose international page names Nik & Aika Seirlis, publishes +61 411 555 355 and +61 456 126 908 for a La Zagaleta villa mandate, and states they onboard UHNW individuals and family offices. Contact page confirms they handle international properties in Dubai and Spain and a A$1 million–A$45 million prestige range; office 07 3229 5000. No Italy or Amalfi evidence, and Dubai stock includes branded off-plan towers, so this is not an Italy specialist. Included because it is a genuine Australian desk placing HNW capital into European luxury (Spain) at tickets that can overlap €6M–€12M. No public email on those pages.",
    },
    {
        "city": "Sydney",
        "company_name": "Savills Australia & New Zealand",
        "type": "international_property_advisor",
        "contact_name": "Paul Roberts",
        "contact_role": "Chief Executive Officer, Australia and New Zealand",
        "email": "",
        "phone": "+61 411 363 544",
        "website": "https://www.savills.com.au/people/paul-roberts.aspx",
        "linkedin_company": "https://www.linkedin.com/company/savills-australia-nz",
        "linkedin_contact": "",
        "investment_focus": "Full-service real estate including cross-border investment and access to the global Savills Private Office / Super Prime Residential network",
        "geographic_focus": "Australia and New Zealand with Savills global coverage including Savills Italy Super Prime Residential and the Savills Private Office",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.savills.com.au/people/paul-roberts.aspx",
        "source_2": "https://www.savills.com/insight-and-opinion/savills-news/362690/new-super-prime-residential-head-for-savills-italy",
        "notes": "Official people page names Paul Roberts as CEO Australia and New Zealand, Level 25, 1 Farrer Place, Sydney, direct +61 411 363 544, office +61 2 8215 8888. No personal email is published on that page. Savills Australia also publishes a Cross Border Investments service. Savills appointed Angelo Savioli Head of Super Prime Residential, Savills Italy, and a member of the Savills Private Office, with Jonathan Hewlett stating clients are increasingly looking to invest in Italy. The Australian company is more commercial than a dedicated UHNW residential private office; include as a network path from Australian capital into Savills Italy super-prime, not as a trophy-residential brokerage. Do not treat Savills Italy itself as the prospect.",
    },
    {
        "city": "Melbourne",
        "company_name": "Mutual Trust",
        "type": "family_office",
        "contact_name": "Jeff Steiner",
        "contact_role": "Partner, Head of Family Office Advisory",
        "email": "enquiry.mel@mutualtrust.com.au",
        "phone": "+61 3 9605 9500",
        "website": "https://www.mutualtrust.com.au/",
        "linkedin_company": "https://www.linkedin.com/company/mutual-trust-pty-ltd",
        "linkedin_contact": "",
        "investment_focus": "Multi-family office for several hundred of Australia's most successful families, including family-office advisory, wealth, real-asset/direct property consulting and dedicated Property Services across residential and commercial assets",
        "geographic_focus": "Melbourne HQ with Sydney, Brisbane, Adelaide and Perth; client families are Australian-origin UHNW with some international investment via manager relationships",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown; client base is intergenerational Australian family wealth, so €6M–€12M is plausible as a personal/lifestyle allocation rather than a fund ticket",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.mutualtrust.com.au/our-people/",
        "source_2": "https://www.mutualtrust.com.au/wp-content/uploads/2026/05/WealthMatters-Behindthefacade-1.pdf",
        "notes": "Australia's leading modern multi-family office after the 2017 combination with The Myer Family Company. Official people page names Jeff Steiner as Partner, Head of Family Office Advisory, and Phil Harkness as CEO and Managing Partner. Contact page/header publishes enquiry.mel@mutualtrust.com.au; Melbourne Level 32, 360 Collins Street, +61 3 9605 9500. Wealth Matters direct-property note states Mutual Trust is highly selective on direct property and works with specialist investment managers. Property Services page describes strategic advice across residential and commercial property assets. No public Italy or Amalfi evidence; included as a high-quality intermediary to Australian family capital, not as a committed Italy allocator. Personal emails are not published.",
    },
    {
        "city": "Sydney",
        "company_name": "LGT Wealth Management Australia",
        "type": "private_office",
        "contact_name": "Michael Chisholm",
        "contact_role": "Chief Executive Officer",
        "email": "",
        "phone": "",
        "website": "https://www.lgtwm.com/au-en/about-lgt/our-company",
        "linkedin_company": "https://www.linkedin.com/company/lgt-wealth-management-australia",
        "linkedin_contact": "https://www.linkedin.com/in/michael-chisholm-842b8b12",
        "investment_focus": "Private wealth and family-office advice to Australian HNW/UHNW families; access to LGT Group global private-banking capabilities including alternatives",
        "geographic_focus": "Australian offices in Sydney, Melbourne, Brisbane, Adelaide and Perth; parent LGT Group is the Liechtenstein Princely Family's private bank with European heritage",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown; firm advises on approximately A$43 billion of client assets",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.lgtwm.com/au-en/about-lgt/our-company",
        "source_2": "https://www.lgtwm.com/au-en/about-lgt/our-people/michael-chisholm-289290",
        "notes": "Former Crestone / UBS Wealth Management Australia, acquired by LGT (Princely Family of Liechtenstein) in 2022 and rebranded LGT Wealth Management in 2025. Official people page names Michael Chisholm as CEO. Public profiles state ~350 staff and ~A$43bn client assets serving HNW families and family offices. Benjamin Marks is a published Partner specialising in entrepreneurs and family offices, but no direct email is published for either person. No dedicated international-property desk was evidenced; Europe relevance is the LGT parent platform and client capability, not a published Italy real-estate programme. Privacy-officer emails were not used. Include as an Australian UHNW capital introducer with a European private-bank parent.",
    },
    {
        "city": "Melbourne",
        "company_name": "Salter Brothers Hospitality",
        "type": "hospitality_investor",
        "contact_name": "Raphael Antonini",
        "contact_role": "Chief Development Officer",
        "email": "raphael.antonini@salterbrothershospitality.com",
        "phone": "",
        "website": "https://salterbrothershospitality.com/our-partners/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Boutique luxury retreat hotels, estates and third-party hotel management (Spicers Retreats, Bannisters, Ardour Hotels & Estates); parent Salter Brothers also invests in premium hospitality assets in Asia",
        "geographic_focus": "Australia-focused operating platform with stated offshore-brand ambitions; parent investment offices in Melbourne, Sydney, Brisbane, Singapore and Tokyo",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "unknown; portfolio is multi-asset boutique luxury rather than a disclosed €6M–€12M single-villa ticket",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://salterbrothershospitality.com/our-partners/",
        "source_2": "https://www.hotelmanagement.com.au/2026/03/06/exclusive-era-of-ardouration/",
        "notes": "Official partners page asks prospects to talk to Chief Development Officer Raphael Antonini at raphael.antonini@salterbrothershospitality.com and describes Salter Brothers Hospitality as Australia's leading operator of luxury retreat hotels, including Spicers and Bannisters, with growth in luxury hospitality in Australia and beyond. Hotel Management (March 2026) quotes CEO Tash Tobias that the Ardour brand is intended to be global, with Australia first and offshore opportunities after a domestic ramp. Parent Salter Brothers has invested in Hotel Indigo Changi Airport with Tokyo Century. Relevant if the Amalfi asset is positioned as boutique hospitality/leisure rather than a pure residence. No published Italy deal. Parent offices: Level 9, 477 Collins Street, Melbourne.",
    },
    {
        "city": "Sydney",
        "company_name": "Lowy Family Group",
        "type": "family_office",
        "contact_name": "",
        "contact_role": "",
        "email": "",
        "phone": "",
        "website": "",
        "linkedin_company": "https://www.linkedin.com/company/lowy-family-group-lfg",
        "linkedin_contact": "",
        "investment_focus": "Single-family office of the Lowy family; long-term listed equities, real estate and technology; historically built Westfield into a global shopping-centre owner including London and other international trophy retail",
        "geographic_focus": "Offices in New York, Los Angeles and Sydney; real-estate DNA is global commercial/retail rather than Italian coastal residential",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "weak",
        "estimated_ticket": "disclosed family-office real-estate deals are far above €6M–€12M (for example a 2025 A$440 million Melbourne shopping-centre purchase via a backed manager); personal trophy-home tickets unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.linkedin.com/company/lowy-family-group-lfg",
        "source_2": "https://www.afr.com/property/commercial/lowy-family-goes-shopping-for-melbourne-mall-in-440m-deal-20250617-p5m7z4",
        "notes": "LFG is the Lowy family's private investment business and family office, with Sydney among its offices. Company LinkedIn states a long-term focus on listed equities, real estate and technology and recounts Westfield's international portfolio before the 2018 Unibail-Rodamco sale. AFR reported a 2025 return to Australian malls via a manager-backed A$440 million purchase. Included as Australian-origin family capital with deep real-estate literacy; not a likely bidder at €6M–€12M on an institutional mandate. No public investment email, named CIO, or Italy evidence. Named principals were not taken from unofficial rich-list commentary.",
    },
    {
        "city": "Melbourne",
        "company_name": "Little Group",
        "type": "family_office",
        "contact_name": "Paul Little AO",
        "contact_role": "Chairman and Founder",
        "email": "",
        "phone": "",
        "website": "https://www.little.com.au/",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Family investment company pursuing property (Little Projects, Little Real Estate), aviation, ferries and lifestyle opportunities aligned with the principals' interests",
        "geographic_focus": "Australia-centred; principals also have UK/US professional backgrounds via Jane Hansen's investment-banking career, but no published Italian real-estate programme",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.little.com.au/",
        "source_2": "https://www.little.com.au/",
        "notes": "Official site: family investment vehicle of Paul Little AO (former Toll Holdings MD) and Jane Hansen AO, formed in 2006 around property through Little Projects and Little Real Estate, later expanding into aviation, passenger ferries and lifestyle. Opportunities are pursued where the principals are passionate and can apply capital long term. No public email or phone on the homepage. Italy/Amalfi not evidenced. Included as an Australian family principal with property and lifestyle DNA that could, in principle, underwrite a trophy coastal asset; not as a demonstrated Italy buyer. Do not confuse with unrelated European 'little BIG hotels' or UK 'The Little Group Limited'.",
    },
]


def main() -> None:
    out = Path("/workspace/data/real-estate-prospects/australia.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for row in ROWS:
            full = {h: row.get(h, "") for h in HEADERS}
            full["country"] = COUNTRY
            full["last_verified"] = LAST_VERIFIED
            writer.writerow(full)
    print(f"Wrote {len(ROWS)} rows to {out}")


if __name__ == "__main__":
    main()
