#!/usr/bin/env python3
"""Generate the United States luxury real-estate prospect CSV from verified research notes.

Buyer-origin principle: every row must provide realistic access to US buyers or
US capital for a €6M–€12M Amalfi Coast luxury/trophy asset. Generic domestic
US brokerages and incompatible institutional funds are excluded.
"""

from __future__ import annotations

import csv
from pathlib import Path

HEADERS = [
    "country",
    "city",
    "company_name",
    "type",
    "contact_name",
    "contact_role",
    "email",
    "phone",
    "website",
    "linkedin_company",
    "linkedin_contact",
    "investment_focus",
    "geographic_focus",
    "buyer_origin_relevance",
    "italy_interest",
    "amalfi_coast_relevance",
    "estimated_ticket",
    "luxury_real_estate",
    "hospitality_interest",
    "fit_score",
    "priority",
    "verification_status",
    "source_1",
    "source_2",
    "notes",
    "last_verified",
]

LAST_VERIFIED = "2026-08-27"
COUNTRY = "United States"

ROWS = [
    {
        "city": "New York",
        "company_name": "Engel & Völkers Private Office",
        "type": "private_office",
        "contact_name": "Stuart N. Siegel",
        "contact_role": "Global Head, Engel & Völkers Private Office; President & CEO, Engel & Völkers Americas",
        "email": "nyc@evrealestate.com",
        "phone": "+1 212 616 7600",
        "website": "https://www.evprivateoffice.com",
        "linkedin_company": "https://www.linkedin.com/company/engel-&-völkers-private-office",
        "linkedin_contact": "https://www.linkedin.com/in/stuartnsiegel",
        "investment_focus": "Discreet UHNW multi-market residential advisory; private-office search across lifestyle and trophy assets",
        "geographic_focus": "United States (Americas HQ in New York) with a global Private Office advisor network including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "UHNW / compatible with €6M–€12M",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.prweb.com/releases/engel--volkers-reveals-lifestyle-priorities-are-shaping-global-investment-and-migration-trends-302635103.html",
        "source_2": "https://www.linkedin.com/posts/engel-%26-v%C3%B6lkers-private-office_privateoffice-2026marketreport-uhnw-activity-7443256050813730816-LqkS",
        "notes": "Official 8 Dec 2025 Private Office Market Report (New York dateline) quotes Siegel as Global Head and states Italy recorded the sharpest rise in international UHNWI enquiries, ahead of France, UAE and Spain. A 27 Mar 2026 Private Office post cites E&V Italia CEO Muhannad Al Salhi that more than one-third of Italian luxury transactions are international, with US buyers leading at about 20%. Siegel is NY-licensed (Engel & Volkers New York Real Estate LLC, 430 Park Ave 11th Fl). Direct personal email not published; nyc@evrealestate.com and +1 212 616 7600 are the published NYC office contacts. Amalfi is not named in the cited report; Campania/coastal Italy is a documented North American buyer market in E&V Italy commentary, so Amalfi relevance is scored moderate rather than strong.",
    },
    {
        "city": "New York",
        "company_name": "BARNES New York",
        "type": "luxury_agency",
        "contact_name": "Alison Graham",
        "contact_role": "Director, BARNES New York",
        "email": "al.graham@barnes-international.com",
        "phone": "+1 347 920 0970",
        "website": "https://barnes-newyork.com",
        "linkedin_company": "https://www.linkedin.com/company/barnes-international-realty",
        "linkedin_contact": "",
        "investment_focus": "UHNW residential; Invest Abroad cross-border acquisitions; off-market private-client work",
        "geographic_focus": "New York metro plus BARNES network including Italy and Sardinia",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://barnes-newyork.com/about",
        "source_2": "https://barnes-newyork.com/invest-abroad",
        "notes": "Official About page publishes Alison Graham's direct email and mobile and positions BARNES New York as serving UHNW clients via a 20+ country network. Invest Abroad by BARNES explicitly lists Italy and Sardinia among outbound destinations for clients investing beyond the US/France. Compass's Luxury Division international referral program (2023) names BARNES as the overseas partner for American citizens buying abroad, including off-market European inventory. Co-director Adrien Gouirand (a.gouirand@barnes-international.com, +1 917 909 9043) is Head of the Brazilian desk, so Graham is the better US-client contact. Office: 575 Park Avenue. Amalfi is not separately evidenced on the NY pages, hence moderate rather than strong.",
    },
    {
        "city": "New York",
        "company_name": "Knight Frank Private Office (Americas)",
        "type": "private_office",
        "contact_name": "Joey Vlasto",
        "contact_role": "Regional Head, Americas; USA contact, The Private Office",
        "email": "",
        "phone": "",
        "website": "https://www.knightfrank.com/private-office",
        "linkedin_company": "https://www.linkedin.com/company/knight-frank",
        "linkedin_contact": "https://www.linkedin.com/in/joey-vlasto",
        "investment_focus": "UHNW and family-office real-estate journeys across residential, investment and cross-border mandates",
        "geographic_focus": "United States / Americas clients into Knight Frank's global network, including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.knightfrank.com/global-assets/global-website/private-office/private-office-brochure_2025.pdf",
        "source_2": "https://www.knightfrank.com/regions/americas/team",
        "notes": "Knight Frank's 2025 Private Office brochure lists Joey Vlasto as the USA key contact, alongside a dedicated US Private Office. CoStar reported his 2023 promotion to Regional Head, Americas, based in New York, coordinating US client relationships and overseas requirements. Knight Frank publishes an Italian homes programme and Italian buying guides; that is network-level Italy access for US clients, not a documented Amalfi transaction, so Amalfi relevance is unclear. Parallel US Residential contact Jason Mansfield (Partner, Head of US Residential; +44 20 7861 1199 / +44 7710 881214; https://www.knightfrank.com/contact/people/jason-mansfield-00014344) leads transatlantic residential strategy from London. No Public Office email published for Vlasto; do not infer one.",
    },
    {
        "city": "New York",
        "company_name": "Savills Private Office (North America Desk)",
        "type": "private_office",
        "contact_name": "Rory McMullen",
        "contact_role": "Co-Head, The Private Office; Head of the North America Desk",
        "email": "",
        "phone": "+1 212 328 3977",
        "website": "https://www.savills.co.uk/services/buying-or-selling/private-office.aspx",
        "linkedin_company": "https://www.linkedin.com/company/savills",
        "linkedin_contact": "https://www.linkedin.com/in/rory-mcmullen",
        "investment_focus": "UHNW and family-office cross-border residential and real-estate advisory; outbound US capital into prime markets",
        "geographic_focus": "North American clients into Savills' global network, including Savills Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.savills.co.uk/people/savills-margaret-street/rory-mcmullen.aspx",
        "source_2": "https://www.savills.co.uk/services/buying-or-selling/private-office.aspx",
        "notes": "Official Savills people page describes McMullen as Co-Head of The Private Office and Head of the North America Desk, advising UHNW clients on investing outside domestic markets and connecting with family offices. Spear's 500 confirms he splits time between London and New York. Savills UK Private Office page publishes +1 212 328 3977 as the New York Private Office number; his London direct mobile +44 7803 013 362 and office +44 20 7499 8644 are on the people page. Savills operates in Italy (Milan/Rome), which supports Europe/Italy routing for US clients, but no Amalfi-specific mandate is published. Direct email not captured from a fully rendered people page; left empty rather than patterned. Savills North America has also hosted US residential referral events with The Corcoran Group.",
    },
    {
        "city": "New York",
        "company_name": "Nest Seekers International",
        "type": "luxury_agency",
        "contact_name": "Bianca D'Alessio",
        "contact_role": "Founder & CEO, The Masters Division; Managing Director, Nest Seekers Development Marketing; US–Italy bridge",
        "email": "bianca@nestseekers.com",
        "phone": "+1 914 282 8898",
        "website": "https://www.nestseekers.com",
        "linkedin_company": "https://www.linkedin.com/company/nest-seekers-international",
        "linkedin_contact": "https://www.linkedin.com/in/biancadalessio",
        "investment_focus": "US UHNW residential and development; cross-border luxury including Italian villas and coastal assets",
        "geographic_focus": "New York / Hamptons buyer base with Nest Seekers offices in Milan, Capri, Naples and coverage of the Amalfi Coast, Lake Como, Tuscany and Puglia",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "strong",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.nestseekers.com/Company/Press/milan-opens-the-reality-real-estate-agency-among-t",
        "source_2": "https://nestseekersmastersdivision.com/agent/bianca-dalessio",
        "notes": "US-headquartered brokerage (505 Park Ave) that opened Italian offices and was publicly described as the Italy–US bridge via Bianca D'Alessio, an Italian-American New York/Hamptons rainmaker. Press on the Nest Seekers site states the Milan office covers luxury homes across Italy including the Amalfi Coast, with Capri and Naples openings. Her Masters Division site publishes bianca@nestseekers.com and mobile +1 914 282 8898. Official Nest Seekers bio confirms a $10B portfolio and international markets. Alternative UHNW desk: Loy Carlos, President of The Office of Global Wealth (ABC@nestseekers.com, +1 212 252 8772 / +1 718 757 8219) — trophy NYC, less Italy-specific. Founder/CEO Eddie Shapiro: +1 646 443 3700; personal email not published.",
    },
    {
        "city": "New York",
        "company_name": "Compass Luxury Division",
        "type": "luxury_agency",
        "contact_name": "Felipe Hernandez",
        "contact_role": "Vice President; Head of Compass Luxury",
        "email": "",
        "phone": "",
        "website": "https://www.luxuryatcompass.com/barnes-international",
        "linkedin_company": "https://www.linkedin.com/company/compassinc",
        "linkedin_contact": "https://www.linkedin.com/in/felipe-hernandez-23b51815",
        "investment_focus": "US luxury and ultra-luxury residential; international referral of American buyers into BARNES/CIRE global inventory",
        "geographic_focus": "United States (largest US brokerage by sales volume) into BARNES destinations in Europe and Christie's International Real Estate affiliates in 50 countries",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.compass.com/newsroom/press-releases/4sdf81ekahBvcumTI44xh1/",
        "source_2": "https://www.luxuryatcompass.com/barnes-international",
        "notes": "Official Compass press release (26 June 2023) launched the Luxury Division international referral program with BARNES, described as particularly advantageous for American citizens purchasing properties abroad, including off-market luxury. Compass's own Luxury page states the program gives agents access to 1,300 BARNES agents and 150,000 international clients, and that Compass luxury clients buying overseas are referred to BARNES. Compass also owns the Christie's International Real Estate brand (100+ affiliates / 50 countries). A 6 Oct 2025 GlobeNewswire release (https://www.globenewswire.com/news-release/2025/10/06/3161420/0/en/Christie-s-International-Real-Estate-Expands-Footprint-in-Italy-Partnering-with-Luxury-Brokerage-Talamona-Real-Estate.html) confirms CIRE's Italy affiliates include Milan, Rome, Venice, Tuscany, Naples, Sardinia, South Tyrol and Lake Como (Talamona added for Piedmont/Liguria/Portofino). That is network-level Campania/coastal Italy access via CIRE, while the published Compass overseas-buyer path remains BARNES; Amalfi is still not named in Compass materials, so Amalfi stays unclear. Hernandez is publicly Head of Compass Luxury (press) and VP of Marketing (LinkedIn). Direct email not published.",
    },
    {
        "city": "New York",
        "company_name": "Charlie Attias Team at Compass (John Taylor partner)",
        "type": "luxury_agency",
        "contact_name": "Charlie Attias",
        "contact_role": "Team Lead; John Taylor US partner for New York",
        "email": "",
        "phone": "",
        "website": "https://www.compass.com/agents/charlie-attias/",
        "linkedin_company": "https://www.linkedin.com/company/compassinc",
        "linkedin_contact": "",
        "investment_focus": "Super-prime Manhattan and trophy residential; international exposure via John Taylor's European network",
        "geographic_focus": "New York UHNW clients, with John Taylor coverage in Italy, France, Monaco, Switzerland, Spain, Portugal and the UAE",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "team transacts well into and above the €6M–€12M band in NYC",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.compass.com/agents/charlie-attias/",
        "source_2": "https://www.john-taylor.com/jtblog/john-taylors-partnership-with-compass_post134/",
        "notes": "Official Compass bio: $4B+ career volume, licensed NY/NJ/FL, partnered with John Taylor across 30+ international markets. Official John Taylor announcement names the Charlie Attias Team as the New York partner for the Compass alliance. John Taylor's own site lists Italian cities (Florence, Milan) among its prestige markets. This is distinct from Compass Luxury Division corporate referrals: a producing NYC UHNW team with a direct European luxury-agency partnership. Personal email/phone not published on the Compass agent page fetch. Ticket evidence is NYC super-prime, which is compatible with €6M–€12M, not an Italian comparable.",
    },
    {
        "city": "New York",
        "company_name": "The Corcoran Group",
        "type": "luxury_agency",
        "contact_name": "Pamela Liebman",
        "contact_role": "President & CEO",
        "email": "pl@corcoran.com",
        "phone": "",
        "website": "https://www.corcoran.com",
        "linkedin_company": "https://www.linkedin.com/company/the-corcoran-group",
        "linkedin_contact": "",
        "investment_focus": "US luxury residential; international affiliate network including Italy",
        "geographic_focus": "New York and US luxury markets, with Corcoran Magri Properties (Lake Garda) as first European/Italy affiliate plus later Portugal and Germany affiliates",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://inhabit.corcoran.com/corcoran-welcomes-first-european-franchise-in-italy/",
        "source_2": "https://www.inman.com/2025/09/18/corcoran-makes-key-move-in-international-expansion-with-new-outpost-in-europes-finance-hub/",
        "notes": "Official Corcoran Inhabit announcement: first European affiliate is Corcoran Magri Properties, Lake Garda, Italy, announced by Pamela Liebman. That creates a direct US-brand path from Corcoran's American UHNW clients into an Italian affiliate (northern lakes, not Amalfi). Liebman is also quoted on subsequent European affiliate expansion (Germany). Corcoran has been paired with Savills North America for US residential referral collaboration. Liebman's official Corcoran agent page publishes pl@corcoran.com (the agent-page URL is bot-blocked from this environment; the address was captured from the live official page). Do not treat Corcoran Magri (Italy) as the prospect; the buyer origin is the US Corcoran client base. Amalfi not evidenced. Stephanie Anton (President, Corcoran Affiliates) is the international-affiliate operator if a functional alternative is needed.",
    },
    {
        "city": "Madison",
        "company_name": "Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Philip A. White, Jr.",
        "contact_role": "President & CEO",
        "email": "",
        "phone": "",
        "website": "https://www.sothebysrealty.com",
        "linkedin_company": "https://www.linkedin.com/company/sothebys-international-realty",
        "linkedin_contact": "",
        "investment_focus": "Global luxury residential referrals across company-owned US brokerages and 1,100+ offices in 86 countries, including Italy Sotheby's International Realty",
        "geographic_focus": "US company-owned brokerages plus global affiliate network; Italy covered by Italy Sotheby's International Realty (15 offices)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.prnewswire.com/news-releases/the-sothebys-international-realty-brand-outpaces-the-industry-tripling-the-us-sales-volume-growth-average-302700721.html",
        "source_2": "https://www.italy-sothebysrealty.com/en/about-us/",
        "notes": "US-headquartered luxury franchise (Anywhere Real Estate). Official 2025/26 brand release: nearly US$7 billion in global referrals and 1,100+ offices in 86 countries. Italy Sotheby's International Realty is a separate Italian operator with 15 offices (Milan, Rome, Naples, Florence, Como, etc.); Naples coverage is the closest published Italian coastal node to Amalfi, so Amalfi relevance is moderate via network, not a dedicated Amalfi desk. Do not redirect the prospect to the Italian affiliate: the US brand/company-owned brokerages are the access point to American UHNW buyers who can be referred into Italy. White is named President & CEO on official brand communications. Direct email not published. Score is for the referral machine, not celebrity of the Sotheby's name alone.",
    },
    {
        "city": "New York",
        "company_name": "Douglas Elliman (Elliman International)",
        "type": "luxury_agency",
        "contact_name": "Michael S. Liebowitz",
        "contact_role": "President & CEO, Douglas Elliman",
        "email": "",
        "phone": "",
        "website": "https://www.elliman.com",
        "linkedin_company": "https://www.linkedin.com/company/douglas-elliman-real-estate",
        "linkedin_contact": "",
        "investment_focus": "US luxury residential; newly launched Elliman International for high-end destination markets; Knight Frank referrals continue",
        "geographic_focus": "US luxury hubs (NY, Florida, California and others); Elliman International currently evidenced in France, Monaco and St. Barths, with Europe as a stated expansion region",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.inman.com/2025/06/02/douglas-elliman-sets-sights-abroad-with-international-expansion/",
        "source_2": "https://investor.wedbush.com/wedbush/article/bizwire-2026-8-7-douglas-elliman-inc-reports-second-quarter-2026-financial-results",
        "notes": "Largest-scale US luxury brokerage client base. 2025 launch of Elliman International after ending the exclusive Knight Frank partnership (referrals still continue). SEC commentary confirms licensed international presence in France, Monaco and St. Barths, not Italy. Italy therefore remains only via residual Knight Frank referral, not a dedicated Elliman Italy desk — hence italy_interest unclear and score 7 rather than 8–9. Liebowitz is the named CEO who launched the international division; investor email InvestorRelations@dougcorp.com is not a sales/private-office address and is not stored here. Direct sales email not published.",
    },
    {
        "city": "Miami",
        "company_name": "ONE Sotheby's International Realty",
        "type": "luxury_agency",
        "contact_name": "Daniel de la Vega",
        "contact_role": "Chief Executive Officer and President",
        "email": "ddelavega@onesothebysrealty.com",
        "phone": "+1 305 666 0562",
        "website": "https://www.onesothebysrealty.com",
        "linkedin_company": "https://www.linkedin.com/company/one-sotheby%27s-international-realty",
        "linkedin_contact": "https://www.linkedin.com/in/daniel-de-la-vega-38b0b1ba",
        "investment_focus": "South Florida ultra-luxury residential; global Sotheby's International Realty referral network",
        "geographic_focus": "Florida East Coast UHNW (US residents plus Latin American and growing European buyers) with SIR global reach including Italy",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "firm transacts well above €6M–€12M in Miami; Italian ticket unstated",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.onesothebysrealty.com/realestate/agent/daniel-de-la-vega/",
        "source_2": "https://www.prnewswire.com/news-releases/the-sothebys-international-realty-brand-outpaces-the-industry-tripling-the-us-sales-volume-growth-average-302700721.html",
        "notes": "Official agent page publishes ddelavega@onesothebysrealty.com, Coral Gables office +1 305 666 0562, and titles him CEO/President. ~$8–10B annual South Florida volume and 1,300+ associates. Buyer-origin is mixed: many clients are US persons in Miami, but a large share of Miami luxury demand is Latin American inbound — hence moderate rather than strong US-origin score. Italy access is via the SIR referral network, not a published ONE Sotheby's Italy desk. A second official URL variant lists ddelavega3@onesothebysrealty.com; the primary CEO page address is stored. Distinct from the Sotheby's International Realty brand row because Miami is a separate UHNW pool.",
    },
    {
        "city": "Miami",
        "company_name": "M Group at Compass (John Taylor partner)",
        "type": "luxury_agency",
        "contact_name": "Mathieu Rochette",
        "contact_role": "Co-lead, M Group; John Taylor US partner for Miami",
        "email": "",
        "phone": "",
        "website": "https://mgroupcompass.com",
        "linkedin_company": "https://www.linkedin.com/company/compassinc",
        "linkedin_contact": "",
        "investment_focus": "Miami Beach and South Florida luxury; local and international buy/sell via John Taylor",
        "geographic_focus": "Miami UHNW, with John Taylor's European and Italian network for outbound clients",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.john-taylor.com/jtblog/john-taylors-partnership-with-compass_post134/",
        "source_2": "https://mgroupcompass.com/",
        "notes": "Official John Taylor announcement names M Group (Mathieu Rochette and Matt Crane) as the Miami Compass partner, stating they buy and sell locally and abroad. M Group's own site repeats the John Taylor partnership and international positioning. Miami buyer origin is mixed US/international (similar caveat as ONE Sotheby's). Email mr@compass.com appears only on a third-party directory, not on the official Compass/M Group pages reviewed, so it is not stored. Co-lead Matt Crane is the other decision-maker.",
    },
    {
        "city": "Chicago",
        "company_name": "Luxury Portfolio International (LeadingRE)",
        "type": "international_property_advisor",
        "contact_name": "",
        "contact_role": "Luxury referral network (Leading Real Estate Companies of the World)",
        "email": "support@luxuryportfolio.com",
        "phone": "+1 312 424 0400",
        "website": "https://www.luxuryportfolio.com",
        "linkedin_company": "https://www.linkedin.com/company/luxury-portfolio-leading-real-estate-companies-of-the-world",
        "linkedin_contact": "",
        "investment_focus": "Marketing and cross-border referral of luxury homes among 250+ independent luxury brokerages",
        "geographic_focus": "US member firms into 35+ countries; Italy affiliates include firms such as Maior Capital (Sardinia / Costa Smeralda)",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.luxuryportfolio.com/it/contact",
        "source_2": "https://www.luxuryportfolio.com/en/brokers/maior-capital",
        "notes": "Chicago-based luxury arm of LeadingRE (161 N Clark St). Official contact page: +1 312 424 0400 and 800-621-6510. support@luxuryportfolio.com is published on the site's terms. Member directory includes Italian luxury firms (Maior Capital, Sardinia). This is a referral network among independent firms — access to US luxury buyers is real but indirect (via US member brokerages such as Brown Harris Stevens). Current named president was not locked after leadership changes (Paul Boomsma / Mickey Alam Khan tenures); executive email therefore not stored. Amalfi not named; Sardinia/Costa Smeralda is the evidenced Italian coastal node.",
    },
    {
        "city": "New York",
        "company_name": "Brown Harris Stevens",
        "type": "luxury_agency",
        "contact_name": "",
        "contact_role": "Referral & Relocation Services / luxury brokerage",
        "email": "",
        "phone": "",
        "website": "https://www.bhsusa.com/relocation",
        "linkedin_company": "https://www.linkedin.com/company/brown-harris-stevens",
        "linkedin_contact": "",
        "investment_focus": "East Coast luxury residential; global referrals via LeadingRE and Luxury Portfolio International",
        "geographic_focus": "New York, Hamptons, Palm Beach, Miami, Connecticut; LeadingRE coverage in 70+ countries including Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.bhsusa.com/relocation",
        "source_2": "https://www.leadingre.com/mediaroom/2023/06",
        "notes": "Privately owned US luxury firm with a dedicated Referral & Relocation Services division that explicitly cites LeadingRE (550 firms / 70 countries) and Luxury Portfolio as the mechanism for partnering 'anywhere in the world'. That is credible US-UHNW outbound access, but no BHS-authored Italy or Amalfi transaction evidence was found in this pass, so Italy remains unclear and the score stays at 7. Named relocation contacts on the Relo page were not captured with full verified titles/emails. Do not use a patterned executive email. Distinct from Luxury Portfolio corporate row: this is a producing US brokerage whose clients can be referred outbound.",
    },
    {
        "city": "New York",
        "company_name": "Living Italy",
        "type": "international_property_advisor",
        "contact_name": "",
        "contact_role": "Buyer-side advisory (US primary buyer market; New York liaison office)",
        "email": "info@livingitaly.it",
        "phone": "+39 06 86356054",
        "website": "https://www.livingitaly.it",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "Buyer-only representation of international, mainly US, clients acquiring distinctive Italian residential, estate and hospitality-conversion assets",
        "geographic_focus": "United States (primary buyer market and NY liaison) into Sicily, Puglia, Tuscany, Lake Como, Rome, Florence; Amalfi Coast listed on the firm's US-investor advisory page",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.livingitaly.it/work-with-us/",
        "source_2": "https://www.livingitaly.it/contact/",
        "notes": "Not an Italian listing agency pitching Amalfi inventory to random searchers: official partner page states primary buyer markets are the United States, UK and Canada, with a New York liaison office and a mandate to place pre-qualified US/UK buyers onto Italian listings. US-investor advisory page lists Amalfi Coast among target destinations and hospitality/rental conversion as a service line. HQ is Rome (Via Teodoro Monticelli); published email info@livingitaly.it and phone +39 06 86356054. No named US-based principal was published on the pages reviewed. Score 7 because the US-buyer channel is explicit, but €6M–€12M trophy/Amalfi closed deals are not documented and much of the advertised inventory (borghi, masserie) sits below this ticket.",
    },
    {
        "city": "Nyack",
        "company_name": "Dolce Living",
        "type": "international_property_advisor",
        "contact_name": "Lorenzo Mengoli",
        "contact_role": "Director",
        "email": "hello@dolce-living.com",
        "phone": "",
        "website": "https://dolce-living.com",
        "linkedin_company": "https://www.linkedin.com/company/dolcelivinghomes",
        "linkedin_contact": "",
        "investment_focus": "US-based buyer representation for Italian residential purchases, due diligence, renovation and remote closing",
        "geographic_focus": "New York / US clients buying across Italy",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://dolce-living.com/our-services/",
        "source_2": "https://news.marketersmedia.com/dolce-living-announces-opening-of-new-office-location-in-new-york/89150370",
        "notes": "US-headquartered (53 Hudson Ave Ste 234, Nyack, NY) buyer-side agency for Americans purchasing in Italy. Official site publishes hello@dolce-living.com. Director Lorenzo Mengoli is named in the Nyack office opening announcement. This is genuine US-origin access, but public materials describe a general Italian-purchase journey (codice fiscale, notaio, due diligence) rather than a documented UHNW/trophy or Amalfi €6M–€12M practice — hence luxury_real_estate unclear and fit 6. LinkedIn company page also lists +1 718 218 3058; not copied here because it was not on the official website pages reviewed.",
    },
    {
        "city": "San Francisco",
        "company_name": "Pacaso",
        "type": "private_capital",
        "contact_name": "Austin Allison",
        "contact_role": "CEO and Co-Founder",
        "email": "",
        "phone": "",
        "website": "https://www.pacaso.com",
        "linkedin_company": "https://www.linkedin.com/company/pacaso",
        "linkedin_contact": "",
        "investment_focus": "Acquisition of luxury second homes for US and international co-ownership; professionally managed Italian apartments/villas",
        "geographic_focus": "US HQ and US buyer financing into Italy (Florence, Milan, Rome) plus France and the UK",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "whole-home acquisitions in luxury second-home band; shares sold as 1/8 to 1/2",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.prnewswire.com/news-releases/pacaso-expands-european-footprint-with-entry-into-italy-302486392.html",
        "source_2": "https://resident.com/real-estate-news/2025/06/23/pacaso-enters-italy-with-co-ownership-homes-in-florence-milan-and-rome",
        "notes": "Official 19 June 2025 Pacaso release: US company (co-founded by Austin Allison and Spencer Rascoff) acquiring luxury homes in Florence, Milan and Rome, with financing for qualifying US buyers and Italian legal/tax partners. This is both a US capital source (Pacaso buys the asset) and a channel to US HNW co-owners. Not a classic single UHNW principal for a €6M–€12M trophy; the model is fractional and currently city-centre Italy, not Amalfi Coast. Still qualifies as US-origin capital actively buying Italian luxury residential. Direct executive email not published on the release. Third-party directories list support@pacaso.com / 1-844-272-2276 — not used because they were not on Pacaso's own release or site in this pass.",
    },
    {
        "city": "Beverly Hills",
        "company_name": "The Agency",
        "type": "luxury_agency",
        "contact_name": "Mauricio Umansky",
        "contact_role": "CEO and Founder",
        "email": "",
        "phone": "",
        "website": "https://www.theagencyre.com",
        "linkedin_company": "https://www.linkedin.com/company/the-agency",
        "linkedin_contact": "",
        "investment_focus": "US and global luxury residential, resort and vacation markets; first Italian office in Sardinia",
        "geographic_focus": "US-headquartered brokerage (165+ offices / 15 countries) with The Agency Sardinia as the Italian node; US buyers cited as a growing Sardinia client source",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "8",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.prweb.com/releases/the-agency-launches-office-in-sardinia-italy-302788025.html",
        "source_2": "https://www.linkedin.com/company/the-agency",
        "notes": "Official 2 June 2026 Agency release (Los Angeles): first Italy office is The Agency Sardinia, announced by founder/CEO Mauricio Umansky. Managing Partner Salvatore Baldinu states Sardinia attracts buyers from across Europe and increasingly the United States. James Ramsay (EVP, Franchise Division) is the corporate expansion contact. Do not treat The Agency Sardinia as the prospect — the buyer origin is The Agency's US UHNW clientele. Sardinia is Mediterranean trophy/coastal (Costa Smeralda analogue), which supports moderate Amalfi relevance as a similar coastal-trophy brief, not a documented Amalfi desk. Media contact on the release: Olivia Cyr, olivia.cyr@theagencyre.com, +1 508 868 8274 — PR, not stored as the decision-maker email. Direct Umansky email not taken from third-party agent aggregators.",
    },
    {
        "city": "Beverly Hills",
        "company_name": "Hilton & Hyland",
        "type": "luxury_agency",
        "contact_name": "Rick Hilton",
        "contact_role": "Chairman",
        "email": "info@hiltonhyland.com",
        "phone": "",
        "website": "https://hiltonhyland.com",
        "linkedin_company": "https://www.linkedin.com/company/hilton-&-hyland",
        "linkedin_contact": "",
        "investment_focus": "Beverly Hills and Los Angeles trophy estates; international marketing via Luxury Portfolio International and Forbes Global Properties",
        "geographic_focus": "California UHNW principals, with outbound reach through LPI and Forbes Global Properties (including Italian members)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "firm regularly transacts $10M+ in Los Angeles; Italian ticket unstated",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://hiltonhyland.com/about/the-hilton-and-hyland-story/",
        "source_2": "https://hiltonhyland.com/contact-us/",
        "notes": "Official story page: privately held Beverly Hills boutique serving LA's most affluent residents, with international presence via an exclusive Luxury Portfolio International relationship. Official contact page publishes info@hiltonhyland.com and 345 N. Maple Drive, Suite 120, Beverly Hills. Rick Hilton is named Chairman after co-founder Jeff Hyland's death. LABJ also notes a Forbes Global Properties affiliation. Italy/Amalfi activity is network-level only (LPI/FGP have Italian members), not a Hilton & Hyland Italy desk — hence italy_interest unclear and score 7. Direct personal email for Hilton not published.",
    },
    {
        "city": "New York",
        "company_name": "Forbes Global Properties",
        "type": "international_property_advisor",
        "contact_name": "Michael Jalbert",
        "contact_role": "Chief Executive Officer",
        "email": "",
        "phone": "",
        "website": "https://www.forbesglobalproperties.com",
        "linkedin_company": "https://www.linkedin.com/company/forbesglobalproperties",
        "linkedin_contact": "",
        "investment_focus": "Invitation-only luxury brokerage network connecting US member firms' buyers with exceptional homes worldwide",
        "geographic_focus": "US-headquartered network with Italian members including Ravagnan's (Venice), Maior Capital (Sardinia) and other regional firms",
        "buyer_origin_relevance": "moderate",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://www.forbesglobalproperties.com/about",
        "source_2": "https://www.forbesglobalproperties.com/insights/forbes-global-properties-continues-italy-expansion-welcoming-ravagnans",
        "notes": "US-headquartered (New York) invitation-only luxury network, exclusive real-estate partner of Forbes, led by CEO Michael Jalbert (official About page). Official releases document Italy expansion: Ravagnan's in Venice and Maior Capital exclusive in Sardinia. Access to US buyers is via US member brokerages (e.g. Hilton & Hyland, Hawaii Life, Willis Allen), so buyer_origin_relevance is moderate rather than a single private-office desk. Amalfi not named among current Italian members. No executive email on the About page; 2022 CEO appointment release lists only a Rubenstein PR contact, which is not stored. Managing Director Marcus Benussi previously expanded BHHS MAGGI in Milan — relevant Italy expertise inside the US network, not a substitute CEO contact.",
    },
    {
        "city": "New York",
        "company_name": "Summers Global Team at Compass",
        "type": "international_property_advisor",
        "contact_name": "Lee Summers",
        "contact_role": "Founder & Team Lead; Real Estate Advisor and Global Consultant",
        "email": "lee.summers@compass.com",
        "phone": "+1 917 330 4942",
        "website": "https://www.compass.com/agents/lee-summers/",
        "linkedin_company": "https://www.linkedin.com/company/compassinc",
        "linkedin_contact": "",
        "investment_focus": "Cross-border UHNW residential, wine estates and hospitality assets; private-client global search including Italy",
        "geographic_focus": "New York base with Compass partners in Italy plus Lake Como, Chianti, Rome and Tuscan hotel/estate coverage on her official page",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "moderate",
        "estimated_ticket": "NYC and global luxury; Tuscan hotel/estate briefs on her page sit at or above the €6M–€12M hospitality band",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://www.compass.com/agents/lee-summers/",
        "source_2": "https://www.compass.com/agents/summers-global-team/",
        "notes": "Official Compass profile publishes lee.summers@compass.com and mobile +1 917 330 4942. Summers is NYC-based, formerly SVP at Sotheby's International Realty, and states she is invited by Goldman Sachs, J.P. Morgan and HSBC to brief investors on global real estate. The same page names Italy among SGT agent locations, lists partners in Italy, and spotlights Lake Como, Chianti, a Rome villa, and a 32-room Tuscan hotel/spa estate — i.e. documented Italy luxury and hospitality inventory, not a generic Compass agent. Distinct from Compass Luxury Division corporate referrals and from the Charlie Attias/John Taylor producing team. Amalfi is not named (Como/Tuscany/Rome are), so Amalfi relevance is moderate. Mixed inbound/outbound clientele; US-origin access is still strong via the NYC desk and US private-bank speaking circuit.",
    },
    {
        "city": "Rye Brook",
        "company_name": "Houlihan Lawrence",
        "type": "luxury_agency",
        "contact_name": "Liz Nunan",
        "contact_role": "President & Chief Executive Officer",
        "email": "",
        "phone": "+1 914 220 7000",
        "website": "https://www.houlihanlawrence.com",
        "linkedin_company": "https://www.linkedin.com/company/houlihan-lawrence",
        "linkedin_contact": "https://www.linkedin.com/in/elizabethnunan",
        "investment_focus": "Luxury residential in New York's northern suburbs and Greenwich corridor; global relocation via Luxury Portfolio / LeadingRE",
        "geographic_focus": "Westchester, Greenwich and related family-office geography, with LPI outbound reach including Italian member firms",
        "buyer_origin_relevance": "strong",
        "italy_interest": "unclear",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://www.houlihanlawrence.com/our-team",
        "source_2": "https://www.luxuryportfolio.com/brokers/houlihan-lawrence-real-estate",
        "notes": "Official team page names Liz Nunan as President & CEO and publishes corporate office 800 Westchester Avenue, Suite N-505, Rye Brook, NY 10573, +1 914 220 7000. This is the dominant luxury brokerage in the Greenwich/Westchester family-office belt — a concentrated US UHNW/private-capital origin market. Luxury Portfolio lists Houlihan Lawrence as a member with a Global Relocation function. No Houlihan Lawrence-authored Italy or Amalfi mandate was found, so Italy remains unclear and the score is 6: real US-origin UHNW access, only network-level Europe. Direct executive email not published on the team page fetch.",
    },
    {
        "city": "Los Angeles",
        "company_name": "MoZaic Real Estate",
        "type": "international_property_advisor",
        "contact_name": "Monika Zakaryan",
        "contact_role": "Founder, Principal Broker and CEO; Certified International Property Specialist",
        "email": "mozaicrealty@gmail.com",
        "phone": "+1 310 728 9022",
        "website": "https://mozaicrealty.com",
        "linkedin_company": "",
        "linkedin_contact": "https://www.linkedin.com/in/mozaicrealty",
        "investment_focus": "US (Los Angeles) clients exploring Italian property; introductions to licensed Italian agents, counsel and tax advisors",
        "geographic_focus": "Los Angeles buyer origin; operating between Los Angeles and Milan",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "unknown",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "unclear",
        "fit_score": "6",
        "priority": "B",
        "verification_status": "verified",
        "source_1": "https://mozaicrealty.com/our-team/",
        "source_2": "https://www.linkedin.com/posts/mozaicrealty_italianrealestate-globalrealestate-internationalinvesting-activity-7440496130771283968-t8U2",
        "notes": "Official team page publishes mozaicrealty@gmail.com, +1 310 728 9022 and California DRE #01349331. Official bio states the CIPS designation is used to help US clients invest overseas. A 19 Mar 2026 LinkedIn post describes coordinating US clients into the Italian market via licensed local professionals, operating between Los Angeles and Milan. This is genuine US-origin access, but public materials do not evidence a UHNW/trophy or Amalfi €6M–€12M closed-deal record, so luxury_real_estate and Amalfi remain unclear and the score is 6. Gmail address is the one published on the company site, not a guessed pattern.",
    },
    {
        "city": "Denver",
        "company_name": "Exclusive Resorts",
        "type": "hospitality_investor",
        "contact_name": "Jim Reilly",
        "contact_role": "Director of Portfolio Procurement (Advisory)",
        "email": "",
        "phone": "+1 800 447 8988",
        "website": "https://exclusiveresorts.com",
        "linkedin_company": "https://www.linkedin.com/company/exclusive-resorts",
        "linkedin_contact": "https://www.linkedin.com/in/jim-reilly-467a6916",
        "investment_focus": "Members-only luxury destination club that owns and procures private residences for US high-net-worth members; parent Exclusive Collective also includes Inspirato and onefinestay",
        "geographic_focus": "Denver HQ serving US member families into a global owned-residence portfolio including the Amalfi Coast, Tuscany and Lake Como",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "strong",
        "estimated_ticket": "unknown (club acquires private residences into a ~$1B owned portfolio; individual villa prices not published)",
        "luxury_real_estate": "yes",
        "hospitality_interest": "yes",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://exclusiveresorts.com/residences/amalfi-coast-italy/",
        "source_2": "https://www.businesswire.com/news/home/20260203454331/en/The-Exclusive-Collective-and-Inspirato-Announce-Completion-of-Acquisition",
        "notes": "Official Amalfi Coast residences page lists two owned club villas (Villa Bella and Casa Praiano in Praiano). BusinessWire (3 Feb 2026) describes Exclusive Resorts as the flagship of The Exclusive Collective, with 4,000+ members, a ~$1B owned-residence portfolio, majority owner Steve Case, and CEO James Henderson (also CEO of The Exclusive Collective; LinkedIn https://www.linkedin.com/in/jjhenderson). Official contact page lists corporate HQ at 1601 19th Street, Suite 500, Denver, CO 80202 and phone 800-447-8988. Reilly is the published Director of Portfolio Procurement on LinkedIn (since 2014), i.e. the acquisitions function for adding residences. Direct personal email not published on official pages (automated fetches of exclusiveresorts.com return 403); MembershipDirector@exclusiveresorts.com appears on a club-journal page but is membership-facing, not procurement, so email is left empty rather than misdirected. This is US-origin hospitality/private-capital access that already deploys into Amalfi villas, not a generic US brokerage. Score 9 rather than 10 because the club buys for member use rather than a documented principal UHNW purchase of a €6M–€12M trophy.",
    },
    {
        "city": "New York",
        "company_name": "Columbus International",
        "type": "international_property_advisor",
        "contact_name": "Richard Tayar",
        "contact_role": "Founder & CEO",
        "email": "info@columbusintl.com",
        "phone": "+1 212 327 0160",
        "website": "https://columbusintl.com",
        "linkedin_company": "https://www.linkedin.com/company/columbusinternational",
        "linkedin_contact": "https://www.linkedin.com/in/richard-tayar-80279220",
        "investment_focus": "Cross-border luxury residential brokerage and advisory bridging US and Italian markets; American buyers into Italian trophy, coastal and historic assets",
        "geographic_focus": "New York HQ (Rockefeller Center) and Miami for US-origin clients; Milan and Florence/Tuscany on the Italian side, with firm commentary covering Lake Como and the Amalfi Coast",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "strong",
        "estimated_ticket": "unknown (firm commentary discusses ~€10M Milan examples and transatlantic luxury; no published Amalfi closed-deal price)",
        "luxury_real_estate": "yes",
        "hospitality_interest": "unclear",
        "fit_score": "9",
        "priority": "A",
        "verification_status": "verified",
        "source_1": "https://columbusintl.com/en/contact/",
        "source_2": "https://columbusintl.com/en/what-daniel-craigs-11-8m-sale-tells-us-about-transatlantic-luxury/",
        "notes": "Official contact page publishes Rockefeller Center, 1270 Sixth Avenue, 8th floor, New York, NY 10020; info@columbusintl.com; and +1 212 327 0160 (plus Italian 800.737.060). Tayar is named Founder & CEO on the firm's own pages, LinkedIn (New York-based; divides time with Florence), and a 16 Dec 2021 Firenze Made in Tuscany interview describing Columbus as a US–Italy bridge for American investors after New York, Miami and Milan. Firm article on transatlantic luxury explicitly names the Amalfi Coast and Lake Como as Italian markets where values have risen on a now-global buyer pool, and a separate Miami article attributes sharp Amalfi/Como waterfront gains to post-pandemic US-buyer demand. This is US-origin access, not an Italian listing agency; do not redirect to the Milan/Florence offices. Direct personal email for Tayar is not published; info@columbusintl.com is the official firm mailbox.",
    },
    {
        "city": "Miami",
        "company_name": "KRF Capital",
        "type": "private_capital",
        "contact_name": "Kyle Fox",
        "contact_role": "Founding Partner; Managing Member",
        "email": "",
        "phone": "+1 212 202 1730",
        "website": "https://www.krfcap.com",
        "linkedin_company": "",
        "linkedin_contact": "",
        "investment_focus": "US alternative / private capital across real estate, energy and credit; documented Italian deployment is a Tuscany luxury hotel and membership-club development",
        "geographic_focus": "US-headquartered (Miami) capital into US, Europe and LatAm; first disclosed Italian asset is Reggello (Florence province)",
        "buyer_origin_relevance": "strong",
        "italy_interest": "yes",
        "amalfi_coast_relevance": "unclear",
        "estimated_ticket": "~€30M development budget for the Reggello luxury hotel/membership club (above the €6M–€12M villa range)",
        "luxury_real_estate": "unclear",
        "hospitality_interest": "yes",
        "fit_score": "7",
        "priority": "B",
        "verification_status": "partially_verified",
        "source_1": "https://bebeez.it/real-estate-2/il-fondo-americano-di-private-equity-krf-capital-acquisisce-unarea-a-reggello-in-provincia-di-firenze-che-diventera-un-hotel-di-lusso/",
        "source_2": "https://www.krfcap.com/team/",
        "notes": "BeBeez, Financecommunity and Legalcommunity (June 2025) independently report KRF Capital as a US private-capital firm making its first Italian investment: acquisition of ~40 hectares in Reggello (Florence) to develop a luxury hotel and membership club, with ~€30 million of development capital; DLA Piper advised. Official krfcap.com/team names Kyle Fox as Founding Partner. SEC Form ADV aggregators list Krf Capital LLC (CRD 328334) in Miami at 2222 Ponce de Leon, 3rd Floor, Miami, FL 33134, with Kyle Rachel Fox as Managing Member / CCO and reported phone 212-202-1730; that phone is included as regulatory-directory evidence, not a marketing-site email. No public professional email found; left empty. Ticket and asset type are hospitality development at ~€30M, not a documented €6M–€12M Amalfi villa purchase, so score is 7 B and Amalfi remains unclear. Included because it is one of the few named US capital sources with a verified Italian luxury-hospitality acquisition.",
    },
]


def validate_rows(rows: list[dict]) -> None:
    allowed_types = {
        "luxury_agency",
        "private_office",
        "family_office",
        "real_estate_investor",
        "real_estate_fund",
        "private_equity_real_estate",
        "hospitality_investor",
        "private_capital",
        "international_property_advisor",
        "other_relevant",
    }
    allowed_bor = {"strong", "moderate", "weak", "unclear"}
    allowed_italy = {"yes", "no", "unclear"}
    allowed_amalfi = {"strong", "moderate", "weak", "unclear"}
    allowed_priority = {"A", "B", "C"}
    allowed_ver = {"verified", "partially_verified", "needs_review"}

    keys = set()
    for i, row in enumerate(rows, start=1):
        missing = [h for h in HEADERS if h not in ("country", "last_verified") and h not in row]
        if missing:
            raise SystemExit(f"Row {i} missing fields: {missing}")
        if row["type"] not in allowed_types:
            raise SystemExit(f"Row {i} bad type: {row['type']}")
        if row["buyer_origin_relevance"] not in allowed_bor:
            raise SystemExit(f"Row {i} bad buyer_origin_relevance")
        if row["italy_interest"] not in allowed_italy:
            raise SystemExit(f"Row {i} bad italy_interest")
        if row["amalfi_coast_relevance"] not in allowed_amalfi:
            raise SystemExit(f"Row {i} bad amalfi_coast_relevance")
        if row["priority"] not in allowed_priority:
            raise SystemExit(f"Row {i} bad priority")
        if row["verification_status"] not in allowed_ver:
            raise SystemExit(f"Row {i} bad verification_status")
        score = int(row["fit_score"])
        if not 1 <= score <= 10:
            raise SystemExit(f"Row {i} bad fit_score")
        if row["priority"] == "A" and score < 8:
            raise SystemExit(f"Row {i} priority A requires fit_score 8–10")
        if row["priority"] == "B" and not (6 <= score <= 7):
            raise SystemExit(f"Row {i} priority B should be 6–7")
        if row["priority"] == "C" and not (1 <= score <= 5):
            raise SystemExit(f"Row {i} priority C should be 1–5")
        email = row["email"].strip()
        if email and ("@" not in email or "." not in email.split("@")[-1]):
            raise SystemExit(f"Row {i} invalid email: {email}")
        key = (row["company_name"].strip().lower(), row["website"].strip().lower(), row["contact_name"].strip().lower())
        if key in keys:
            raise SystemExit(f"Row {i} duplicate key {key}")
        keys.add(key)


def main() -> None:
    validate_rows(ROWS)
    out = Path("/workspace/data/real-estate-prospects/united-states.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for row in ROWS:
            full = {h: row.get(h, "") for h in HEADERS}
            full["country"] = COUNTRY
            full["last_verified"] = LAST_VERIFIED
            writer.writerow(full)
    print(f"Wrote {len(ROWS)} rows to {out}")


if __name__ == "__main__":
    main()
